// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config14_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [8:0] p_read;
input  [8:0] p_read1;
input  [8:0] p_read2;
input  [8:0] p_read3;
input  [8:0] p_read4;
input  [8:0] p_read5;
input  [8:0] p_read6;
input  [8:0] p_read7;
input  [8:0] p_read8;
input  [8:0] p_read9;
input  [8:0] p_read11;
input  [8:0] p_read12;
input  [8:0] p_read13;
input  [8:0] p_read14;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;

wire   [15:0] r_V_fu_277_p2;
reg   [15:0] r_V_reg_6146;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] r_V_375_fu_241_p2;
reg   [14:0] r_V_375_reg_6159;
wire   [14:0] r_V_382_fu_275_p2;
reg   [14:0] r_V_382_reg_6178;
wire   [15:0] r_V_389_fu_252_p2;
reg   [15:0] r_V_389_reg_6191;
wire   [14:0] r_V_394_fu_237_p2;
reg   [14:0] r_V_394_reg_6201;
wire   [14:0] r_V_404_fu_271_p2;
reg   [14:0] r_V_404_reg_6220;
reg   [8:0] p_read181_reg_7534;
wire   [15:0] r_V_369_fu_6441_p2;
reg   [15:0] r_V_369_reg_7540;
wire   [15:0] r_V_381_fu_6548_p2;
reg   [15:0] r_V_381_reg_7545;
wire   [14:0] zext_ln1319_334_fu_6594_p1;
reg   [14:0] zext_ln1319_334_reg_7550;
wire   [15:0] tmp_fu_6816_p2;
reg   [15:0] tmp_reg_7555;
wire   [15:0] tmp2_fu_6822_p2;
reg   [15:0] tmp2_reg_7560;
wire   [15:0] tmp3_fu_6846_p2;
reg   [15:0] tmp3_reg_7565;
wire   [16:0] tmp4_fu_6862_p2;
reg   [16:0] tmp4_reg_7570;
wire   [15:0] tmp7_fu_6884_p2;
reg   [15:0] tmp7_reg_7575;
wire   [15:0] tmp9_fu_6890_p2;
reg   [15:0] tmp9_reg_7580;
wire   [15:0] tmp11_fu_6916_p2;
reg   [15:0] tmp11_reg_7585;
wire   [18:0] tmp12_fu_6928_p2;
reg   [18:0] tmp12_reg_7590;
wire   [15:0] tmp14_fu_6942_p2;
reg   [15:0] tmp14_reg_7595;
wire   [15:0] tmp16_fu_6972_p2;
reg   [15:0] tmp16_reg_7600;
wire   [19:0] tmp17_fu_6988_p2;
reg   [19:0] tmp17_reg_7605;
wire   [15:0] tmp21_fu_7002_p2;
reg   [15:0] tmp21_reg_7610;
wire   [8:0] r_V_386_fu_231_p0;
wire  signed [5:0] r_V_386_fu_231_p1;
wire    ap_block_pp0_stage0;
wire   [8:0] r_V_388_fu_233_p0;
wire   [5:0] r_V_388_fu_233_p1;
wire   [8:0] r_V_399_fu_234_p0;
wire   [14:0] zext_ln1319_348_fu_6752_p1;
wire   [6:0] r_V_399_fu_234_p1;
wire   [8:0] r_V_394_fu_237_p0;
wire   [14:0] zext_ln1319_342_fu_6681_p1;
wire  signed [5:0] r_V_394_fu_237_p1;
wire   [8:0] r_V_373_fu_239_p0;
wire   [6:0] r_V_373_fu_239_p1;
wire   [8:0] r_V_396_fu_240_p0;
wire  signed [5:0] r_V_396_fu_240_p1;
wire   [8:0] r_V_375_fu_241_p0;
wire   [14:0] zext_ln1319_325_fu_6506_p1;
wire  signed [5:0] r_V_375_fu_241_p1;
wire   [8:0] r_V_390_fu_243_p0;
wire   [14:0] zext_ln1319_338_fu_6627_p1;
wire   [6:0] r_V_390_fu_243_p1;
wire   [8:0] r_V_377_fu_247_p0;
wire   [6:0] r_V_377_fu_247_p1;
wire   [8:0] r_V_389_fu_252_p0;
wire  signed [6:0] r_V_389_fu_252_p1;
wire   [8:0] r_V_403_fu_253_p0;
wire  signed [5:0] r_V_403_fu_253_p1;
wire   [8:0] r_V_378_fu_254_p0;
wire   [6:0] r_V_378_fu_254_p1;
wire   [8:0] r_V_370_fu_256_p0;
wire   [5:0] r_V_370_fu_256_p1;
wire   [8:0] r_V_387_fu_257_p0;
wire   [6:0] r_V_387_fu_257_p1;
wire   [8:0] r_V_380_fu_259_p0;
wire   [6:0] r_V_380_fu_259_p1;
wire   [8:0] r_V_397_fu_260_p0;
wire  signed [6:0] r_V_397_fu_260_p1;
wire   [8:0] r_V_404_fu_271_p0;
wire  signed [5:0] r_V_404_fu_271_p1;
wire   [8:0] r_V_379_fu_272_p0;
wire  signed [6:0] r_V_379_fu_272_p1;
wire   [8:0] r_V_376_fu_273_p0;
wire   [6:0] r_V_376_fu_273_p1;
wire   [8:0] r_V_382_fu_275_p0;
wire  signed [5:0] r_V_382_fu_275_p1;
wire   [8:0] r_V_fu_277_p0;
wire  signed [6:0] r_V_fu_277_p1;
wire   [8:0] r_V_372_fu_280_p0;
wire  signed [5:0] r_V_372_fu_280_p1;
wire   [8:0] r_V_393_fu_286_p0;
wire  signed [5:0] r_V_393_fu_286_p1;
wire   [8:0] r_V_384_fu_288_p0;
wire   [6:0] r_V_384_fu_288_p1;
wire   [8:0] r_V_401_fu_289_p0;
wire   [6:0] r_V_401_fu_289_p1;
wire   [12:0] shl_ln_fu_6381_p3;
wire   [13:0] zext_ln1319_314_fu_6389_p1;
wire   [13:0] sub_ln1319_fu_6393_p2;
wire   [9:0] shl_ln1319_s_fu_6403_p3;
wire  signed [14:0] sext_ln1319_fu_6399_p1;
wire   [14:0] zext_ln1319_316_fu_6415_p1;
wire   [14:0] r_V_368_fu_6419_p2;
wire   [14:0] shl_ln1319_147_fu_6429_p3;
wire   [15:0] zext_ln1319_317_fu_6437_p1;
wire   [15:0] zext_ln1319_315_fu_6411_p1;
wire   [12:0] shl_ln1319_150_fu_6462_p3;
wire   [13:0] zext_ln1319_323_fu_6470_p1;
wire   [13:0] sub_ln1319_152_fu_6474_p2;
wire   [10:0] shl_ln1319_151_fu_6484_p3;
wire  signed [14:0] sext_ln1319_28_fu_6480_p1;
wire   [14:0] zext_ln1319_324_fu_6492_p1;
wire   [14:0] r_V_374_fu_6496_p2;
wire   [14:0] shl_ln1319_152_fu_6524_p3;
wire   [12:0] shl_ln1319_153_fu_6536_p3;
wire   [15:0] zext_ln1319_328_fu_6532_p1;
wire   [15:0] zext_ln1319_329_fu_6544_p1;
wire   [14:0] shl_ln1319_154_fu_6564_p3;
wire   [12:0] shl_ln1319_155_fu_6576_p3;
wire   [15:0] zext_ln1319_333_fu_6584_p1;
wire   [15:0] zext_ln1319_332_fu_6572_p1;
wire   [13:0] tmp_s_fu_6599_p3;
wire   [14:0] zext_ln1319_335_fu_6607_p1;
wire   [13:0] shl_ln1319_156_fu_6633_p3;
wire   [9:0] shl_ln1319_157_fu_6645_p3;
wire   [14:0] zext_ln1319_339_fu_6641_p1;
wire   [14:0] zext_ln1319_340_fu_6653_p1;
wire   [11:0] shl_ln1319_158_fu_6663_p3;
wire   [14:0] zext_ln1319_341_fu_6671_p1;
wire   [13:0] shl_ln1319_159_fu_6687_p3;
wire   [11:0] shl_ln1319_160_fu_6699_p3;
wire   [14:0] zext_ln1319_343_fu_6695_p1;
wire   [14:0] zext_ln1319_344_fu_6707_p1;
wire   [14:0] shl_ln1319_161_fu_6722_p3;
wire   [11:0] shl_ln1319_162_fu_6734_p3;
wire   [15:0] zext_ln1319_347_fu_6742_p1;
wire   [15:0] zext_ln1319_346_fu_6730_p1;
wire   [13:0] shl_ln1319_163_fu_6759_p3;
wire   [14:0] zext_ln1319_349_fu_6767_p1;
wire   [11:0] shl_ln1319_164_fu_6777_p3;
wire   [14:0] zext_ln1319_350_fu_6785_p1;
wire   [14:0] r_V_380_fu_259_p2;
wire   [14:0] r_V_384_fu_288_p2;
wire   [14:0] r_V_387_fu_257_p2;
wire   [14:0] r_V_393_fu_286_p2;
wire  signed [15:0] r_V_405_cast_fu_6812_p1;
wire   [15:0] r_V_392_cast_fu_6800_p1;
wire   [15:0] r_V_396_cast_fu_6804_p1;
wire   [15:0] r_V_399_cast_fu_6808_p1;
wire   [14:0] r_V_378_fu_254_p2;
wire  signed [15:0] sext_ln1316_14_fu_6502_p1;
wire  signed [15:0] sext_ln1316_fu_6425_p1;
wire   [15:0] r_V_383_fu_6588_p2;
wire   [14:0] r_V_392_fu_6675_p2;
wire   [15:0] addconv_fu_6832_p2;
wire   [15:0] r_V_390_cast_fu_6828_p1;
wire   [15:0] r_V_398_fu_6746_p2;
wire   [15:0] r_V_404_cast_fu_6842_p1;
wire   [15:0] tmp5_fu_6852_p2;
wire  signed [16:0] tmp5_cast_fu_6858_p1;
wire  signed [16:0] r_V_395_cast_fu_6838_p1;
wire   [14:0] r_V_373_fu_239_p2;
wire   [14:0] r_V_385_fu_6611_p2;
wire   [14:0] r_V_390_fu_243_p2;
wire   [14:0] r_V_399_fu_234_p2;
wire  signed [15:0] r_V_397_cast_fu_6872_p1;
wire   [15:0] r_V_385_cast_fu_6868_p1;
wire   [15:0] r_V_402_cast_fu_6876_p1;
wire   [15:0] r_V_411_cast_fu_6880_p1;
wire   [13:0] r_V_370_fu_256_p2;
wire   [13:0] r_V_388_fu_233_p2;
wire   [14:0] r_V_391_fu_6657_p2;
wire   [14:0] r_V_400_fu_6771_p2;
wire  signed [17:0] r_V_412_cast_cast_cast_cast_fu_6908_p1;
wire   [15:0] r_V_382_cast_fu_6896_p1;
wire   [15:0] r_V_397_fu_260_p2;
wire   [18:0] r_V_403_cast_fu_6904_p1;
wire   [18:0] r_V_412_cast_cast_cast_cast_cast_fu_6912_p1;
wire   [18:0] tmp13_fu_6922_p2;
wire   [18:0] r_V_400_cast_fu_6900_p1;
wire   [14:0] r_V_376_fu_273_p2;
wire   [14:0] r_V_401_fu_289_p2;
wire   [15:0] r_V_388_cast_fu_6934_p1;
wire   [15:0] r_V_413_cast_fu_6938_p1;
wire   [14:0] r_V_372_fu_280_p2;
wire   [14:0] r_V_377_fu_247_p2;
wire   [14:0] r_V_395_fu_6711_p2;
wire  signed [17:0] r_V_407_cast_cast_cast_cast_fu_6956_p1;
wire   [14:0] r_V_402_fu_6789_p2;
wire  signed [17:0] r_V_414_cast_cast_cast_cast_fu_6964_p1;
wire   [15:0] r_V_379_fu_272_p2;
wire   [15:0] r_V_389_cast_fu_6952_p1;
wire   [18:0] r_V_407_cast_cast_cast_cast_cast_fu_6960_p1;
wire   [18:0] r_V_414_cast_cast_cast_cast_cast_fu_6968_p1;
wire   [18:0] tmp18_fu_6978_p2;
wire   [19:0] tmp18_cast_fu_6984_p1;
wire  signed [19:0] r_V_384_cast_fu_6948_p1;
wire   [14:0] r_V_396_fu_240_p2;
wire   [14:0] r_V_403_fu_253_p2;
wire  signed [15:0] r_V_408_cast_fu_6994_p1;
wire  signed [15:0] r_V_415_cast_fu_6998_p1;
wire   [13:0] shl_ln1319_148_fu_7008_p3;
wire   [11:0] shl_ln1319_149_fu_7019_p3;
wire   [14:0] zext_ln1319_320_fu_7015_p1;
wire   [14:0] zext_ln1319_321_fu_7026_p1;
wire   [14:0] r_V_371_fu_7030_p2;
wire   [15:0] mult_V_fu_7036_p3;
wire  signed [18:0] sext_ln17_29_fu_7044_p1;
wire  signed [15:0] mult_V_31_fu_7056_p3;
wire   [14:0] r_V_386_fu_231_p2;
wire   [15:0] mult_V_32_fu_7072_p3;
wire   [16:0] tmp2_cast_fu_7098_p1;
wire   [16:0] r_V_381_cast_fu_7092_p1;
wire   [16:0] tmp1_fu_7101_p2;
wire   [17:0] tmp1_cast_fu_7107_p1;
wire  signed [17:0] tmp_cast_fu_7095_p1;
wire   [17:0] tmp11843_fu_7111_p2;
wire   [18:0] tmp_96_fu_7117_p3;
wire  signed [19:0] sext_ln859_32_fu_7125_p1;
wire  signed [17:0] tmp4_cast_fu_7138_p1;
wire  signed [17:0] tmp3_cast_fu_7135_p1;
wire   [17:0] tmp13437_fu_7141_p2;
wire   [18:0] tmp_97_fu_7147_p3;
wire  signed [19:0] sext_ln859_33_fu_7155_p1;
wire   [19:0] add_ln859_105_fu_7159_p2;
wire  signed [19:0] sext_ln17_30_fu_7080_p1;
wire   [16:0] tmp9_cast_fu_7178_p1;
wire  signed [16:0] r_V_cast_fu_7171_p1;
wire   [16:0] tmp8_fu_7181_p2;
wire  signed [17:0] tmp8_cast_fu_7187_p1;
wire  signed [17:0] tmp7_cast_fu_7175_p1;
wire   [17:0] tmp13935_fu_7191_p2;
wire   [18:0] tmp_98_fu_7197_p3;
wire  signed [19:0] sext_ln859_34_fu_7205_p1;
wire  signed [16:0] tmp11_cast_fu_7219_p1;
wire  signed [16:0] r_V_387_cast_fu_7215_p1;
wire   [16:0] tmp10_fu_7222_p2;
wire   [19:0] tmp12_cast_fu_7232_p1;
wire  signed [19:0] tmp10_cast_fu_7228_p1;
wire   [19:0] tmp14533_fu_7235_p2;
wire   [20:0] tmp_99_fu_7241_p3;
wire  signed [21:0] tmp146_fu_7249_p1;
wire   [16:0] tmp14_cast_fu_7263_p1;
wire  signed [16:0] r_V_406_cast_fu_7259_p1;
wire   [16:0] tmp14831_fu_7266_p2;
wire   [17:0] tmp_100_fu_7272_p3;
wire  signed [18:0] sext_ln859_35_fu_7280_p1;
wire   [18:0] add_ln859_109_fu_7284_p2;
wire  signed [20:0] sext_ln859_36_fu_7290_p1;
wire   [20:0] zext_ln17_23_fu_7052_p1;
wire  signed [20:0] tmp17_cast_fu_7303_p1;
wire  signed [20:0] tmp16_cast_fu_7300_p1;
wire   [20:0] tmp15330_fu_7306_p2;
wire   [21:0] tmp107_fu_7312_p3;
wire   [21:0] add_ln859_111_fu_7320_p2;
wire  signed [21:0] sext_ln17_26_fu_7068_p1;
wire  signed [17:0] r_V_393_cast_cast_cast_cast_fu_7332_p1;
wire  signed [18:0] r_V_401_cast_fu_7339_p1;
wire   [18:0] r_V_393_cast_cast_cast_cast_cast_fu_7335_p1;
wire  signed [18:0] tmp21_cast_fu_7349_p1;
wire   [18:0] tmp20_fu_7343_p2;
wire   [18:0] tmp16325_fu_7352_p2;
wire   [19:0] tmp_101_fu_7358_p3;
wire   [19:0] zext_ln17_fu_7048_p1;
wire  signed [19:0] sext_ln17_fu_7064_p1;
wire   [19:0] add_ln859_113_fu_7370_p2;
wire   [15:0] mult_V_33_fu_7084_p3;
wire   [15:0] add_ln859_114_fu_7380_p2;
wire  signed [20:0] sext_ln859_38_fu_7386_p1;
wire  signed [20:0] sext_ln859_37_fu_7366_p1;
wire   [20:0] add_ln859_115_fu_7390_p2;
wire  signed [21:0] sext_ln859_39_fu_7396_p1;
wire  signed [21:0] sext_ln859_fu_7376_p1;
wire   [19:0] x_V_fu_7209_p2;
wire   [13:0] tmp_268_fu_7406_p4;
wire   [21:0] x_V_39_fu_7253_p2;
wire   [20:0] x_V_40_fu_7294_p2;
wire   [14:0] tmp_269_fu_7430_p4;
wire   [21:0] x_V_41_fu_7326_p2;
wire   [19:0] x_V_42_fu_7165_p2;
wire   [13:0] tmp_270_fu_7454_p4;
wire   [19:0] x_V_43_fu_7129_p2;
wire   [13:0] tmp_271_fu_7468_p4;
wire   [21:0] x_V_44_fu_7400_p2;
wire  signed [15:0] sext_ln864_fu_7416_p1;
wire  signed [15:0] sext_ln864_15_fu_7440_p1;
wire  signed [15:0] sext_ln864_16_fu_7464_p1;
wire  signed [15:0] sext_ln864_17_fu_7478_p1;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
wire   [13:0] r_V_370_fu_256_p00;
wire   [14:0] r_V_372_fu_280_p00;
wire   [14:0] r_V_373_fu_239_p00;
wire   [15:0] r_V_379_fu_272_p00;
wire   [14:0] r_V_380_fu_259_p00;
wire   [14:0] r_V_382_fu_275_p00;
wire   [14:0] r_V_384_fu_288_p00;
wire   [13:0] r_V_388_fu_233_p00;
wire   [15:0] r_V_389_fu_252_p00;
wire   [15:0] r_V_397_fu_260_p00;
wire   [14:0] r_V_404_fu_271_p00;
wire   [15:0] r_V_fu_277_p00;

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U560(
    .din0(r_V_386_fu_231_p0),
    .din1(r_V_386_fu_231_p1),
    .dout(r_V_386_fu_231_p2)
);

tau_nn_mul_9ns_6ns_14_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_0_U561(
    .din0(r_V_388_fu_233_p0),
    .din1(r_V_388_fu_233_p1),
    .dout(r_V_388_fu_233_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U562(
    .din0(r_V_399_fu_234_p0),
    .din1(r_V_399_fu_234_p1),
    .dout(r_V_399_fu_234_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U563(
    .din0(r_V_394_fu_237_p0),
    .din1(r_V_394_fu_237_p1),
    .dout(r_V_394_fu_237_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U564(
    .din0(r_V_373_fu_239_p0),
    .din1(r_V_373_fu_239_p1),
    .dout(r_V_373_fu_239_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U565(
    .din0(r_V_396_fu_240_p0),
    .din1(r_V_396_fu_240_p1),
    .dout(r_V_396_fu_240_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U566(
    .din0(r_V_375_fu_241_p0),
    .din1(r_V_375_fu_241_p1),
    .dout(r_V_375_fu_241_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U567(
    .din0(r_V_390_fu_243_p0),
    .din1(r_V_390_fu_243_p1),
    .dout(r_V_390_fu_243_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U568(
    .din0(r_V_377_fu_247_p0),
    .din1(r_V_377_fu_247_p1),
    .dout(r_V_377_fu_247_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U569(
    .din0(r_V_389_fu_252_p0),
    .din1(r_V_389_fu_252_p1),
    .dout(r_V_389_fu_252_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U570(
    .din0(r_V_403_fu_253_p0),
    .din1(r_V_403_fu_253_p1),
    .dout(r_V_403_fu_253_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U571(
    .din0(r_V_378_fu_254_p0),
    .din1(r_V_378_fu_254_p1),
    .dout(r_V_378_fu_254_p2)
);

tau_nn_mul_9ns_6ns_14_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_0_U572(
    .din0(r_V_370_fu_256_p0),
    .din1(r_V_370_fu_256_p1),
    .dout(r_V_370_fu_256_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U573(
    .din0(r_V_387_fu_257_p0),
    .din1(r_V_387_fu_257_p1),
    .dout(r_V_387_fu_257_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U574(
    .din0(r_V_380_fu_259_p0),
    .din1(r_V_380_fu_259_p1),
    .dout(r_V_380_fu_259_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U575(
    .din0(r_V_397_fu_260_p0),
    .din1(r_V_397_fu_260_p1),
    .dout(r_V_397_fu_260_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U576(
    .din0(r_V_404_fu_271_p0),
    .din1(r_V_404_fu_271_p1),
    .dout(r_V_404_fu_271_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U577(
    .din0(r_V_379_fu_272_p0),
    .din1(r_V_379_fu_272_p1),
    .dout(r_V_379_fu_272_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U578(
    .din0(r_V_376_fu_273_p0),
    .din1(r_V_376_fu_273_p1),
    .dout(r_V_376_fu_273_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U579(
    .din0(r_V_382_fu_275_p0),
    .din1(r_V_382_fu_275_p1),
    .dout(r_V_382_fu_275_p2)
);

tau_nn_mul_9ns_7s_16_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_0_U580(
    .din0(r_V_fu_277_p0),
    .din1(r_V_fu_277_p1),
    .dout(r_V_fu_277_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U581(
    .din0(r_V_372_fu_280_p0),
    .din1(r_V_372_fu_280_p1),
    .dout(r_V_372_fu_280_p2)
);

tau_nn_mul_9ns_6s_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_0_U582(
    .din0(r_V_393_fu_286_p0),
    .din1(r_V_393_fu_286_p1),
    .dout(r_V_393_fu_286_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U583(
    .din0(r_V_384_fu_288_p0),
    .din1(r_V_384_fu_288_p1),
    .dout(r_V_384_fu_288_p2)
);

tau_nn_mul_9ns_7ns_15_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_0_U584(
    .din0(r_V_401_fu_289_p0),
    .din1(r_V_401_fu_289_p1),
    .dout(r_V_401_fu_289_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln864_fu_7416_p1;
        ap_return_1_int_reg <= {{x_V_39_fu_7253_p2[21:6]}};
        ap_return_2_int_reg <= sext_ln864_15_fu_7440_p1;
        ap_return_3_int_reg <= {{x_V_41_fu_7326_p2[21:6]}};
        ap_return_4_int_reg <= sext_ln864_16_fu_7464_p1;
        ap_return_5_int_reg <= sext_ln864_17_fu_7478_p1;
        ap_return_6_int_reg <= {{x_V_44_fu_7400_p2[21:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        p_read181_reg_7534 <= p_read1;
        r_V_369_reg_7540[15 : 1] <= r_V_369_fu_6441_p2[15 : 1];
        r_V_375_reg_6159 <= r_V_375_fu_241_p2;
        r_V_381_reg_7545[15 : 4] <= r_V_381_fu_6548_p2[15 : 4];
        r_V_382_reg_6178 <= r_V_382_fu_275_p2;
        r_V_389_reg_6191 <= r_V_389_fu_252_p2;
        r_V_394_reg_6201 <= r_V_394_fu_237_p2;
        r_V_404_reg_6220 <= r_V_404_fu_271_p2;
        r_V_reg_6146 <= r_V_fu_277_p2;
        tmp11_reg_7585 <= tmp11_fu_6916_p2;
        tmp12_reg_7590 <= tmp12_fu_6928_p2;
        tmp14_reg_7595 <= tmp14_fu_6942_p2;
        tmp16_reg_7600 <= tmp16_fu_6972_p2;
        tmp17_reg_7605 <= tmp17_fu_6988_p2;
        tmp21_reg_7610 <= tmp21_fu_7002_p2;
        tmp2_reg_7560 <= tmp2_fu_6822_p2;
        tmp3_reg_7565 <= tmp3_fu_6846_p2;
        tmp4_reg_7570[16 : 3] <= tmp4_fu_6862_p2[16 : 3];
        tmp7_reg_7575 <= tmp7_fu_6884_p2;
        tmp9_reg_7580 <= tmp9_fu_6890_p2;
        tmp_reg_7555 <= tmp_fu_6816_p2;
        zext_ln1319_334_reg_7550[8 : 0] <= zext_ln1319_334_fu_6594_p1[8 : 0];
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln864_fu_7416_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = {{x_V_39_fu_7253_p2[21:6]}};
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln864_15_fu_7440_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = {{x_V_41_fu_7326_p2[21:6]}};
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = sext_ln864_16_fu_7464_p1;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = sext_ln864_17_fu_7478_p1;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = {{x_V_44_fu_7400_p2[21:6]}};
    end else begin
        ap_return_6 = 'bx;
    end
end

assign add_ln859_105_fu_7159_p2 = ($signed(sext_ln859_33_fu_7155_p1) + $signed(20'd13312));

assign add_ln859_109_fu_7284_p2 = ($signed(sext_ln859_35_fu_7280_p1) + $signed(19'd523264));

assign add_ln859_111_fu_7320_p2 = (tmp107_fu_7312_p3 + 22'd3072);

assign add_ln859_113_fu_7370_p2 = ($signed(zext_ln17_fu_7048_p1) + $signed(sext_ln17_fu_7064_p1));

assign add_ln859_114_fu_7380_p2 = (mult_V_33_fu_7084_p3 + 16'd16384);

assign add_ln859_115_fu_7390_p2 = ($signed(sext_ln859_38_fu_7386_p1) + $signed(sext_ln859_37_fu_7366_p1));

assign addconv_fu_6832_p2 = ($signed(sext_ln1316_14_fu_6502_p1) + $signed(sext_ln1316_fu_6425_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mult_V_31_fu_7056_p3 = {{r_V_382_reg_6178}, {1'd0}};

assign mult_V_32_fu_7072_p3 = {{r_V_386_fu_231_p2}, {1'd0}};

assign mult_V_33_fu_7084_p3 = {{r_V_404_reg_6220}, {1'd0}};

assign mult_V_fu_7036_p3 = {{r_V_371_fu_7030_p2}, {1'd0}};

assign r_V_368_fu_6419_p2 = ($signed(sext_ln1319_fu_6399_p1) - $signed(zext_ln1319_316_fu_6415_p1));

assign r_V_369_fu_6441_p2 = (zext_ln1319_317_fu_6437_p1 + zext_ln1319_315_fu_6411_p1);

assign r_V_370_fu_256_p0 = r_V_370_fu_256_p00;

assign r_V_370_fu_256_p00 = p_read1;

assign r_V_370_fu_256_p1 = 14'd23;

assign r_V_371_fu_7030_p2 = (zext_ln1319_320_fu_7015_p1 - zext_ln1319_321_fu_7026_p1);

assign r_V_372_fu_280_p0 = r_V_372_fu_280_p00;

assign r_V_372_fu_280_p00 = p_read1;

assign r_V_372_fu_280_p1 = 15'd32741;

assign r_V_373_fu_239_p0 = r_V_373_fu_239_p00;

assign r_V_373_fu_239_p00 = p_read2;

assign r_V_373_fu_239_p1 = 15'd53;

assign r_V_374_fu_6496_p2 = ($signed(sext_ln1319_28_fu_6480_p1) - $signed(zext_ln1319_324_fu_6492_p1));

assign r_V_375_fu_241_p0 = zext_ln1319_325_fu_6506_p1;

assign r_V_375_fu_241_p1 = 15'd32742;

assign r_V_376_fu_273_p0 = zext_ln1319_325_fu_6506_p1;

assign r_V_376_fu_273_p1 = 15'd51;

assign r_V_377_fu_247_p0 = zext_ln1319_325_fu_6506_p1;

assign r_V_377_fu_247_p1 = 15'd41;

assign r_V_378_fu_254_p0 = zext_ln1319_325_fu_6506_p1;

assign r_V_378_fu_254_p1 = 15'd35;

assign r_V_379_fu_272_p0 = r_V_379_fu_272_p00;

assign r_V_379_fu_272_p00 = p_read4;

assign r_V_379_fu_272_p1 = 16'd65479;

assign r_V_380_fu_259_p0 = r_V_380_fu_259_p00;

assign r_V_380_fu_259_p00 = p_read4;

assign r_V_380_fu_259_p1 = 15'd55;

assign r_V_381_cast_fu_7092_p1 = r_V_369_reg_7540;

assign r_V_381_fu_6548_p2 = (zext_ln1319_328_fu_6532_p1 - zext_ln1319_329_fu_6544_p1);

assign r_V_382_cast_fu_6896_p1 = r_V_370_fu_256_p2;

assign r_V_382_fu_275_p0 = r_V_382_fu_275_p00;

assign r_V_382_fu_275_p00 = p_read5;

assign r_V_382_fu_275_p1 = 15'd32747;

assign r_V_383_fu_6588_p2 = (zext_ln1319_333_fu_6584_p1 - zext_ln1319_332_fu_6572_p1);

assign r_V_384_cast_fu_6948_p1 = $signed(r_V_372_fu_280_p2);

assign r_V_384_fu_288_p0 = r_V_384_fu_288_p00;

assign r_V_384_fu_288_p00 = p_read6;

assign r_V_384_fu_288_p1 = 15'd41;

assign r_V_385_cast_fu_6868_p1 = r_V_373_fu_239_p2;

assign r_V_385_fu_6611_p2 = (zext_ln1319_334_fu_6594_p1 - zext_ln1319_335_fu_6607_p1);

assign r_V_386_fu_231_p0 = zext_ln1319_334_reg_7550;

assign r_V_386_fu_231_p1 = 15'd32741;

assign r_V_387_cast_fu_7215_p1 = $signed(r_V_375_reg_6159);

assign r_V_387_fu_257_p0 = zext_ln1319_334_fu_6594_p1;

assign r_V_387_fu_257_p1 = 15'd50;

assign r_V_388_cast_fu_6934_p1 = r_V_376_fu_273_p2;

assign r_V_388_fu_233_p0 = r_V_388_fu_233_p00;

assign r_V_388_fu_233_p00 = p_read8;

assign r_V_388_fu_233_p1 = 14'd21;

assign r_V_389_cast_fu_6952_p1 = r_V_377_fu_247_p2;

assign r_V_389_fu_252_p0 = r_V_389_fu_252_p00;

assign r_V_389_fu_252_p00 = p_read8;

assign r_V_389_fu_252_p1 = 16'd65501;

assign r_V_390_cast_fu_6828_p1 = r_V_378_fu_254_p2;

assign r_V_390_fu_243_p0 = zext_ln1319_338_fu_6627_p1;

assign r_V_390_fu_243_p1 = 15'd41;

assign r_V_391_fu_6657_p2 = (zext_ln1319_339_fu_6641_p1 + zext_ln1319_340_fu_6653_p1);

assign r_V_392_cast_fu_6800_p1 = r_V_380_fu_259_p2;

assign r_V_392_fu_6675_p2 = (zext_ln1319_339_fu_6641_p1 + zext_ln1319_341_fu_6671_p1);

assign r_V_393_cast_cast_cast_cast_cast_fu_7335_p1 = $unsigned(r_V_393_cast_cast_cast_cast_fu_7332_p1);

assign r_V_393_cast_cast_cast_cast_fu_7332_p1 = $signed(r_V_381_reg_7545);

assign r_V_393_fu_286_p0 = zext_ln1319_338_fu_6627_p1;

assign r_V_393_fu_286_p1 = 15'd32749;

assign r_V_394_fu_237_p0 = zext_ln1319_342_fu_6681_p1;

assign r_V_394_fu_237_p1 = 15'd32749;

assign r_V_395_cast_fu_6838_p1 = $signed(r_V_383_fu_6588_p2);

assign r_V_395_fu_6711_p2 = (zext_ln1319_343_fu_6695_p1 - zext_ln1319_344_fu_6707_p1);

assign r_V_396_cast_fu_6804_p1 = r_V_384_fu_288_p2;

assign r_V_396_fu_240_p0 = zext_ln1319_342_fu_6681_p1;

assign r_V_396_fu_240_p1 = 15'd32747;

assign r_V_397_cast_fu_6872_p1 = $signed(r_V_385_fu_6611_p2);

assign r_V_397_fu_260_p0 = r_V_397_fu_260_p00;

assign r_V_397_fu_260_p00 = p_read12;

assign r_V_397_fu_260_p1 = 16'd65493;

assign r_V_398_fu_6746_p2 = (zext_ln1319_347_fu_6742_p1 - zext_ln1319_346_fu_6730_p1);

assign r_V_399_cast_fu_6808_p1 = r_V_387_fu_257_p2;

assign r_V_399_fu_234_p0 = zext_ln1319_348_fu_6752_p1;

assign r_V_399_fu_234_p1 = 15'd46;

assign r_V_400_cast_fu_6900_p1 = r_V_388_fu_233_p2;

assign r_V_400_fu_6771_p2 = (zext_ln1319_349_fu_6767_p1 - zext_ln1319_348_fu_6752_p1);

assign r_V_401_cast_fu_7339_p1 = $signed(r_V_389_reg_6191);

assign r_V_401_fu_289_p0 = zext_ln1319_348_fu_6752_p1;

assign r_V_401_fu_289_p1 = 15'd52;

assign r_V_402_cast_fu_6876_p1 = r_V_390_fu_243_p2;

assign r_V_402_fu_6789_p2 = (zext_ln1319_349_fu_6767_p1 - zext_ln1319_350_fu_6785_p1);

assign r_V_403_cast_fu_6904_p1 = r_V_391_fu_6657_p2;

assign r_V_403_fu_253_p0 = zext_ln1319_348_fu_6752_p1;

assign r_V_403_fu_253_p1 = 15'd32743;

assign r_V_404_cast_fu_6842_p1 = r_V_392_fu_6675_p2;

assign r_V_404_fu_271_p0 = r_V_404_fu_271_p00;

assign r_V_404_fu_271_p00 = p_read14;

assign r_V_404_fu_271_p1 = 15'd32743;

assign r_V_405_cast_fu_6812_p1 = $signed(r_V_393_fu_286_p2);

assign r_V_406_cast_fu_7259_p1 = $signed(r_V_394_reg_6201);

assign r_V_407_cast_cast_cast_cast_cast_fu_6960_p1 = $unsigned(r_V_407_cast_cast_cast_cast_fu_6956_p1);

assign r_V_407_cast_cast_cast_cast_fu_6956_p1 = $signed(r_V_395_fu_6711_p2);

assign r_V_408_cast_fu_6994_p1 = $signed(r_V_396_fu_240_p2);

assign r_V_411_cast_fu_6880_p1 = r_V_399_fu_234_p2;

assign r_V_412_cast_cast_cast_cast_cast_fu_6912_p1 = $unsigned(r_V_412_cast_cast_cast_cast_fu_6908_p1);

assign r_V_412_cast_cast_cast_cast_fu_6908_p1 = $signed(r_V_400_fu_6771_p2);

assign r_V_413_cast_fu_6938_p1 = r_V_401_fu_289_p2;

assign r_V_414_cast_cast_cast_cast_cast_fu_6968_p1 = $unsigned(r_V_414_cast_cast_cast_cast_fu_6964_p1);

assign r_V_414_cast_cast_cast_cast_fu_6964_p1 = $signed(r_V_402_fu_6789_p2);

assign r_V_415_cast_fu_6998_p1 = $signed(r_V_403_fu_253_p2);

assign r_V_cast_fu_7171_p1 = $signed(r_V_reg_6146);

assign r_V_fu_277_p0 = r_V_fu_277_p00;

assign r_V_fu_277_p00 = p_read;

assign r_V_fu_277_p1 = 16'd65482;

assign sext_ln1316_14_fu_6502_p1 = $signed(r_V_374_fu_6496_p2);

assign sext_ln1316_fu_6425_p1 = $signed(r_V_368_fu_6419_p2);

assign sext_ln1319_28_fu_6480_p1 = $signed(sub_ln1319_152_fu_6474_p2);

assign sext_ln1319_fu_6399_p1 = $signed(sub_ln1319_fu_6393_p2);

assign sext_ln17_26_fu_7068_p1 = mult_V_31_fu_7056_p3;

assign sext_ln17_29_fu_7044_p1 = $signed(mult_V_fu_7036_p3);

assign sext_ln17_30_fu_7080_p1 = $signed(mult_V_32_fu_7072_p3);

assign sext_ln17_fu_7064_p1 = mult_V_31_fu_7056_p3;

assign sext_ln859_32_fu_7125_p1 = $signed(tmp_96_fu_7117_p3);

assign sext_ln859_33_fu_7155_p1 = $signed(tmp_97_fu_7147_p3);

assign sext_ln859_34_fu_7205_p1 = $signed(tmp_98_fu_7197_p3);

assign sext_ln859_35_fu_7280_p1 = $signed(tmp_100_fu_7272_p3);

assign sext_ln859_36_fu_7290_p1 = $signed(add_ln859_109_fu_7284_p2);

assign sext_ln859_37_fu_7366_p1 = $signed(tmp_101_fu_7358_p3);

assign sext_ln859_38_fu_7386_p1 = $signed(add_ln859_114_fu_7380_p2);

assign sext_ln859_39_fu_7396_p1 = $signed(add_ln859_115_fu_7390_p2);

assign sext_ln859_fu_7376_p1 = $signed(add_ln859_113_fu_7370_p2);

assign sext_ln864_15_fu_7440_p1 = $signed(tmp_269_fu_7430_p4);

assign sext_ln864_16_fu_7464_p1 = $signed(tmp_270_fu_7454_p4);

assign sext_ln864_17_fu_7478_p1 = $signed(tmp_271_fu_7468_p4);

assign sext_ln864_fu_7416_p1 = $signed(tmp_268_fu_7406_p4);

assign shl_ln1319_147_fu_6429_p3 = {{p_read}, {6'd0}};

assign shl_ln1319_148_fu_7008_p3 = {{p_read181_reg_7534}, {5'd0}};

assign shl_ln1319_149_fu_7019_p3 = {{p_read181_reg_7534}, {3'd0}};

assign shl_ln1319_150_fu_6462_p3 = {{p_read2}, {4'd0}};

assign shl_ln1319_151_fu_6484_p3 = {{p_read2}, {2'd0}};

assign shl_ln1319_152_fu_6524_p3 = {{p_read4}, {6'd0}};

assign shl_ln1319_153_fu_6536_p3 = {{p_read4}, {4'd0}};

assign shl_ln1319_154_fu_6564_p3 = {{p_read6}, {6'd0}};

assign shl_ln1319_155_fu_6576_p3 = {{p_read6}, {4'd0}};

assign shl_ln1319_156_fu_6633_p3 = {{p_read9}, {5'd0}};

assign shl_ln1319_157_fu_6645_p3 = {{p_read9}, {1'd0}};

assign shl_ln1319_158_fu_6663_p3 = {{p_read9}, {3'd0}};

assign shl_ln1319_159_fu_6687_p3 = {{p_read11}, {5'd0}};

assign shl_ln1319_160_fu_6699_p3 = {{p_read11}, {3'd0}};

assign shl_ln1319_161_fu_6722_p3 = {{p_read12}, {6'd0}};

assign shl_ln1319_162_fu_6734_p3 = {{p_read12}, {3'd0}};

assign shl_ln1319_163_fu_6759_p3 = {{p_read13}, {5'd0}};

assign shl_ln1319_164_fu_6777_p3 = {{p_read13}, {3'd0}};

assign shl_ln1319_s_fu_6403_p3 = {{p_read}, {1'd0}};

assign shl_ln_fu_6381_p3 = {{p_read}, {4'd0}};

assign sub_ln1319_152_fu_6474_p2 = (14'd0 - zext_ln1319_323_fu_6470_p1);

assign sub_ln1319_fu_6393_p2 = (14'd0 - zext_ln1319_314_fu_6389_p1);

assign tmp107_fu_7312_p3 = {{tmp15330_fu_7306_p2}, {1'd0}};

assign tmp10_cast_fu_7228_p1 = $signed(tmp10_fu_7222_p2);

assign tmp10_fu_7222_p2 = ($signed(tmp11_cast_fu_7219_p1) + $signed(r_V_387_cast_fu_7215_p1));

assign tmp11843_fu_7111_p2 = ($signed(tmp1_cast_fu_7107_p1) + $signed(tmp_cast_fu_7095_p1));

assign tmp11_cast_fu_7219_p1 = $signed(tmp11_reg_7585);

assign tmp11_fu_6916_p2 = (r_V_382_cast_fu_6896_p1 + r_V_397_fu_260_p2);

assign tmp12_cast_fu_7232_p1 = tmp12_reg_7590;

assign tmp12_fu_6928_p2 = (tmp13_fu_6922_p2 + r_V_400_cast_fu_6900_p1);

assign tmp13437_fu_7141_p2 = ($signed(tmp4_cast_fu_7138_p1) + $signed(tmp3_cast_fu_7135_p1));

assign tmp13935_fu_7191_p2 = ($signed(tmp8_cast_fu_7187_p1) + $signed(tmp7_cast_fu_7175_p1));

assign tmp13_fu_6922_p2 = (r_V_403_cast_fu_6904_p1 + r_V_412_cast_cast_cast_cast_cast_fu_6912_p1);

assign tmp14533_fu_7235_p2 = ($signed(tmp12_cast_fu_7232_p1) + $signed(tmp10_cast_fu_7228_p1));

assign tmp146_fu_7249_p1 = $signed(tmp_99_fu_7241_p3);

assign tmp14831_fu_7266_p2 = ($signed(tmp14_cast_fu_7263_p1) + $signed(r_V_406_cast_fu_7259_p1));

assign tmp14_cast_fu_7263_p1 = tmp14_reg_7595;

assign tmp14_fu_6942_p2 = (r_V_388_cast_fu_6934_p1 + r_V_413_cast_fu_6938_p1);

assign tmp15330_fu_7306_p2 = ($signed(tmp17_cast_fu_7303_p1) + $signed(tmp16_cast_fu_7300_p1));

assign tmp16325_fu_7352_p2 = ($signed(tmp21_cast_fu_7349_p1) + $signed(tmp20_fu_7343_p2));

assign tmp16_cast_fu_7300_p1 = $signed(tmp16_reg_7600);

assign tmp16_fu_6972_p2 = (r_V_379_fu_272_p2 + r_V_389_cast_fu_6952_p1);

assign tmp17_cast_fu_7303_p1 = $signed(tmp17_reg_7605);

assign tmp17_fu_6988_p2 = ($signed(tmp18_cast_fu_6984_p1) + $signed(r_V_384_cast_fu_6948_p1));

assign tmp18_cast_fu_6984_p1 = tmp18_fu_6978_p2;

assign tmp18_fu_6978_p2 = (r_V_407_cast_cast_cast_cast_cast_fu_6960_p1 + r_V_414_cast_cast_cast_cast_cast_fu_6968_p1);

assign tmp1_cast_fu_7107_p1 = tmp1_fu_7101_p2;

assign tmp1_fu_7101_p2 = (tmp2_cast_fu_7098_p1 + r_V_381_cast_fu_7092_p1);

assign tmp20_fu_7343_p2 = ($signed(r_V_401_cast_fu_7339_p1) + $signed(r_V_393_cast_cast_cast_cast_cast_fu_7335_p1));

assign tmp21_cast_fu_7349_p1 = $signed(tmp21_reg_7610);

assign tmp21_fu_7002_p2 = ($signed(r_V_408_cast_fu_6994_p1) + $signed(r_V_415_cast_fu_6998_p1));

assign tmp2_cast_fu_7098_p1 = tmp2_reg_7560;

assign tmp2_fu_6822_p2 = (r_V_396_cast_fu_6804_p1 + r_V_399_cast_fu_6808_p1);

assign tmp3_cast_fu_7135_p1 = $signed(tmp3_reg_7565);

assign tmp3_fu_6846_p2 = (addconv_fu_6832_p2 + r_V_390_cast_fu_6828_p1);

assign tmp4_cast_fu_7138_p1 = $signed(tmp4_reg_7570);

assign tmp4_fu_6862_p2 = ($signed(tmp5_cast_fu_6858_p1) + $signed(r_V_395_cast_fu_6838_p1));

assign tmp5_cast_fu_6858_p1 = $signed(tmp5_fu_6852_p2);

assign tmp5_fu_6852_p2 = (r_V_398_fu_6746_p2 + r_V_404_cast_fu_6842_p1);

assign tmp7_cast_fu_7175_p1 = $signed(tmp7_reg_7575);

assign tmp7_fu_6884_p2 = ($signed(r_V_397_cast_fu_6872_p1) + $signed(r_V_385_cast_fu_6868_p1));

assign tmp8_cast_fu_7187_p1 = $signed(tmp8_fu_7181_p2);

assign tmp8_fu_7181_p2 = ($signed(tmp9_cast_fu_7178_p1) + $signed(r_V_cast_fu_7171_p1));

assign tmp9_cast_fu_7178_p1 = tmp9_reg_7580;

assign tmp9_fu_6890_p2 = (r_V_402_cast_fu_6876_p1 + r_V_411_cast_fu_6880_p1);

assign tmp_100_fu_7272_p3 = {{tmp14831_fu_7266_p2}, {1'd0}};

assign tmp_101_fu_7358_p3 = {{tmp16325_fu_7352_p2}, {1'd0}};

assign tmp_268_fu_7406_p4 = {{x_V_fu_7209_p2[19:6]}};

assign tmp_269_fu_7430_p4 = {{x_V_40_fu_7294_p2[20:6]}};

assign tmp_270_fu_7454_p4 = {{x_V_42_fu_7165_p2[19:6]}};

assign tmp_271_fu_7468_p4 = {{x_V_43_fu_7129_p2[19:6]}};

assign tmp_96_fu_7117_p3 = {{tmp11843_fu_7111_p2}, {1'd0}};

assign tmp_97_fu_7147_p3 = {{tmp13437_fu_7141_p2}, {1'd0}};

assign tmp_98_fu_7197_p3 = {{tmp13935_fu_7191_p2}, {1'd0}};

assign tmp_99_fu_7241_p3 = {{tmp14533_fu_7235_p2}, {1'd0}};

assign tmp_cast_fu_7095_p1 = $signed(tmp_reg_7555);

assign tmp_fu_6816_p2 = ($signed(r_V_405_cast_fu_6812_p1) + $signed(r_V_392_cast_fu_6800_p1));

assign tmp_s_fu_6599_p3 = {{p_read7}, {5'd0}};

assign x_V_39_fu_7253_p2 = ($signed(tmp146_fu_7249_p1) + $signed(22'd3072));

assign x_V_40_fu_7294_p2 = ($signed(sext_ln859_36_fu_7290_p1) + $signed(zext_ln17_23_fu_7052_p1));

assign x_V_41_fu_7326_p2 = ($signed(add_ln859_111_fu_7320_p2) + $signed(sext_ln17_26_fu_7068_p1));

assign x_V_42_fu_7165_p2 = ($signed(add_ln859_105_fu_7159_p2) + $signed(sext_ln17_30_fu_7080_p1));

assign x_V_43_fu_7129_p2 = ($signed(sext_ln859_32_fu_7125_p1) + $signed(20'd1024));

assign x_V_44_fu_7400_p2 = ($signed(sext_ln859_39_fu_7396_p1) + $signed(sext_ln859_fu_7376_p1));

assign x_V_fu_7209_p2 = ($signed(sext_ln859_34_fu_7205_p1) + $signed(20'd1024));

assign zext_ln1319_314_fu_6389_p1 = shl_ln_fu_6381_p3;

assign zext_ln1319_315_fu_6411_p1 = shl_ln1319_s_fu_6403_p3;

assign zext_ln1319_316_fu_6415_p1 = shl_ln1319_s_fu_6403_p3;

assign zext_ln1319_317_fu_6437_p1 = shl_ln1319_147_fu_6429_p3;

assign zext_ln1319_320_fu_7015_p1 = shl_ln1319_148_fu_7008_p3;

assign zext_ln1319_321_fu_7026_p1 = shl_ln1319_149_fu_7019_p3;

assign zext_ln1319_323_fu_6470_p1 = shl_ln1319_150_fu_6462_p3;

assign zext_ln1319_324_fu_6492_p1 = shl_ln1319_151_fu_6484_p3;

assign zext_ln1319_325_fu_6506_p1 = p_read3;

assign zext_ln1319_328_fu_6532_p1 = shl_ln1319_152_fu_6524_p3;

assign zext_ln1319_329_fu_6544_p1 = shl_ln1319_153_fu_6536_p3;

assign zext_ln1319_332_fu_6572_p1 = shl_ln1319_154_fu_6564_p3;

assign zext_ln1319_333_fu_6584_p1 = shl_ln1319_155_fu_6576_p3;

assign zext_ln1319_334_fu_6594_p1 = p_read7;

assign zext_ln1319_335_fu_6607_p1 = tmp_s_fu_6599_p3;

assign zext_ln1319_338_fu_6627_p1 = p_read9;

assign zext_ln1319_339_fu_6641_p1 = shl_ln1319_156_fu_6633_p3;

assign zext_ln1319_340_fu_6653_p1 = shl_ln1319_157_fu_6645_p3;

assign zext_ln1319_341_fu_6671_p1 = shl_ln1319_158_fu_6663_p3;

assign zext_ln1319_342_fu_6681_p1 = p_read11;

assign zext_ln1319_343_fu_6695_p1 = shl_ln1319_159_fu_6687_p3;

assign zext_ln1319_344_fu_6707_p1 = shl_ln1319_160_fu_6699_p3;

assign zext_ln1319_346_fu_6730_p1 = shl_ln1319_161_fu_6722_p3;

assign zext_ln1319_347_fu_6742_p1 = shl_ln1319_162_fu_6734_p3;

assign zext_ln1319_348_fu_6752_p1 = p_read13;

assign zext_ln1319_349_fu_6767_p1 = shl_ln1319_163_fu_6759_p3;

assign zext_ln1319_350_fu_6785_p1 = shl_ln1319_164_fu_6777_p3;

assign zext_ln17_23_fu_7052_p1 = $unsigned(sext_ln17_29_fu_7044_p1);

assign zext_ln17_fu_7048_p1 = $unsigned(sext_ln17_29_fu_7044_p1);

always @ (posedge ap_clk) begin
    r_V_369_reg_7540[0] <= 1'b0;
    r_V_381_reg_7545[3:0] <= 4'b0000;
    zext_ln1319_334_reg_7550[14:9] <= 6'b000000;
    tmp4_reg_7570[2:0] <= 3'b000;
end

endmodule //tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config14_s
