// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config14_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] p_read;
input  [8:0] p_read1;
input  [8:0] p_read2;
input  [8:0] p_read3;
input  [8:0] p_read4;
input  [8:0] p_read5;
input  [8:0] p_read6;
input  [8:0] p_read7;
input  [8:0] p_read8;
input  [8:0] p_read9;
input  [8:0] p_read11;
input  [8:0] p_read12;
input  [8:0] p_read13;
input  [8:0] p_read14;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] trunc_ln4_reg_4828;
reg   [8:0] trunc_ln17_s_reg_4833;
reg   [9:0] trunc_ln17_107_reg_4838;
reg   [9:0] trunc_ln864_220_reg_4843;
reg  signed [9:0] trunc_ln864_222_reg_4848;
reg   [9:0] trunc_ln17_114_reg_4854;
reg   [10:0] trunc_ln864_226_reg_4859;
reg   [9:0] trunc_ln864_227_reg_4864;
reg   [9:0] trunc_ln864_228_reg_4869;
reg   [10:0] trunc_ln864_231_reg_4874;
reg   [10:0] trunc_ln864_232_reg_4879;
reg   [9:0] trunc_ln864_233_reg_4884;
reg   [9:0] trunc_ln17_120_reg_4889;
reg   [9:0] trunc_ln864_236_reg_4894;
wire   [10:0] add_ln859_fu_4357_p2;
reg   [10:0] add_ln859_reg_4899;
wire   [10:0] add_ln859_408_fu_4363_p2;
reg   [10:0] add_ln859_408_reg_4904;
wire   [10:0] add_ln859_409_fu_4369_p2;
reg   [10:0] add_ln859_409_reg_4909;
wire   [11:0] add_ln859_411_fu_4375_p2;
reg   [11:0] add_ln859_411_reg_4914;
wire   [10:0] add_ln859_415_fu_4381_p2;
reg   [10:0] add_ln859_415_reg_4919;
wire   [11:0] add_ln859_418_fu_4397_p2;
reg   [11:0] add_ln859_418_reg_4924;
wire   [9:0] add_ln859_420_fu_4403_p2;
reg   [9:0] add_ln859_420_reg_4929;
wire   [11:0] add_ln859_426_fu_4409_p2;
reg   [11:0] add_ln859_426_reg_4934;
wire   [12:0] add_ln859_431_fu_4425_p2;
reg   [12:0] add_ln859_431_reg_4939;
wire   [11:0] add_ln859_432_fu_4431_p2;
reg   [11:0] add_ln859_432_reg_4944;
wire   [11:0] add_ln859_436_fu_4437_p2;
reg   [11:0] add_ln859_436_reg_4949;
wire   [10:0] add_ln859_439_fu_4443_p2;
reg   [10:0] add_ln859_439_reg_4954;
wire   [8:0] r_V_190_fu_220_p0;
wire   [14:0] zext_ln1319_185_fu_3902_p1;
wire  signed [5:0] r_V_190_fu_220_p1;
wire   [8:0] r_V_192_fu_221_p0;
wire   [14:0] zext_ln864_171_fu_3998_p1;
wire  signed [5:0] r_V_192_fu_221_p1;
wire   [8:0] mul_ln864_86_fu_222_p0;
wire   [14:0] zext_ln70_8_fu_4233_p1;
wire   [6:0] mul_ln864_86_fu_222_p1;
wire   [8:0] r_V_198_fu_223_p0;
wire  signed [5:0] r_V_198_fu_223_p1;
wire   [8:0] r_V_197_fu_224_p0;
wire  signed [5:0] r_V_197_fu_224_p1;
wire   [8:0] mul_ln864_79_fu_225_p0;
wire   [14:0] zext_ln1319_179_fu_3682_p1;
wire   [6:0] mul_ln864_79_fu_225_p1;
wire   [8:0] r_V_183_fu_226_p0;
wire  signed [5:0] r_V_183_fu_226_p1;
wire   [8:0] mul_ln864_77_fu_227_p0;
wire   [6:0] mul_ln864_77_fu_227_p1;
wire   [8:0] mul_ln864_80_fu_228_p0;
wire   [6:0] mul_ln864_80_fu_228_p1;
wire   [8:0] r_V_194_fu_230_p0;
wire   [14:0] zext_ln1319_187_fu_4100_p1;
wire  signed [5:0] r_V_194_fu_230_p1;
wire   [8:0] mul_ln864_84_fu_231_p0;
wire   [5:0] mul_ln864_84_fu_231_p1;
wire   [8:0] r_V_193_fu_232_p0;
wire  signed [5:0] r_V_193_fu_232_p1;
wire   [8:0] mul_ln864_85_fu_233_p0;
wire   [6:0] mul_ln864_85_fu_233_p1;
wire   [8:0] r_V_191_fu_235_p0;
wire  signed [6:0] r_V_191_fu_235_p1;
wire   [8:0] mul_ln864_87_fu_236_p0;
wire   [6:0] mul_ln864_87_fu_236_p1;
wire   [8:0] r_V_185_fu_237_p0;
wire  signed [5:0] r_V_185_fu_237_p1;
wire   [8:0] mul_ln864_82_fu_238_p0;
wire   [6:0] mul_ln864_82_fu_238_p1;
wire   [8:0] mul_ln864_83_fu_239_p0;
wire   [6:0] mul_ln864_83_fu_239_p1;
wire   [8:0] mul_ln864_fu_242_p0;
wire   [5:0] mul_ln864_fu_242_p1;
wire   [8:0] r_V_186_fu_244_p0;
wire  signed [6:0] r_V_186_fu_244_p1;
wire   [8:0] r_V_187_fu_245_p0;
wire  signed [5:0] r_V_187_fu_245_p1;
wire   [8:0] mul_ln864_81_fu_246_p0;
wire   [6:0] mul_ln864_81_fu_246_p1;
wire   [8:0] r_V_fu_247_p0;
wire  signed [6:0] r_V_fu_247_p1;
wire   [8:0] r_V_195_fu_248_p0;
wire  signed [6:0] r_V_195_fu_248_p1;
wire   [8:0] mul_ln864_78_fu_249_p0;
wire   [6:0] mul_ln864_78_fu_249_p1;
wire   [15:0] r_V_fu_247_p2;
wire   [10:0] trunc_ln_fu_3431_p4;
wire   [12:0] shl_ln_fu_3445_p3;
wire   [13:0] zext_ln1319_175_fu_3453_p1;
wire   [13:0] sub_ln1319_fu_3457_p2;
wire   [9:0] shl_ln1319_s_fu_3467_p3;
wire  signed [14:0] sext_ln1319_fu_3463_p1;
wire   [14:0] zext_ln1319_176_fu_3475_p1;
wire   [14:0] r_V_182_fu_3479_p2;
wire   [9:0] trunc_ln864_s_fu_3485_p4;
wire   [14:0] shl_ln2_fu_3499_p3;
wire   [15:0] zext_ln864_fu_3507_p1;
wire   [15:0] zext_ln864_162_fu_3511_p1;
wire   [15:0] add_ln864_fu_3515_p2;
wire   [13:0] mul_ln864_fu_242_p2;
wire   [13:0] shl_ln864_s_fu_3551_p3;
wire   [11:0] shl_ln864_83_fu_3563_p3;
wire   [14:0] zext_ln864_164_fu_3559_p1;
wire   [14:0] zext_ln864_165_fu_3571_p1;
wire   [14:0] sub_ln864_fu_3575_p2;
wire   [9:0] trunc_ln864_217_fu_3581_p4;
wire  signed [10:0] sext_ln17_fu_3591_p1;
wire   [14:0] r_V_183_fu_226_p2;
wire   [9:0] trunc_ln864_218_fu_3599_p4;
wire   [14:0] mul_ln864_77_fu_227_p2;
wire   [12:0] shl_ln1319_79_fu_3628_p3;
wire   [13:0] zext_ln1319_177_fu_3636_p1;
wire   [13:0] sub_ln1319_108_fu_3640_p2;
wire   [10:0] shl_ln1319_80_fu_3650_p3;
wire  signed [14:0] sext_ln1319_27_fu_3646_p1;
wire   [14:0] zext_ln1319_178_fu_3658_p1;
wire   [14:0] r_V_184_fu_3662_p2;
wire   [9:0] trunc_ln864_219_fu_3668_p4;
wire   [14:0] r_V_185_fu_237_p2;
wire   [14:0] mul_ln864_78_fu_249_p2;
wire   [9:0] trunc_ln17_108_fu_3700_p4;
wire   [14:0] mul_ln864_79_fu_225_p2;
wire   [9:0] trunc_ln17_109_fu_3714_p4;
wire   [14:0] mul_ln864_80_fu_228_p2;
wire   [9:0] trunc_ln17_110_fu_3728_p4;
wire   [15:0] r_V_186_fu_244_p2;
wire   [10:0] trunc_ln864_221_fu_3747_p4;
wire   [14:0] mul_ln864_81_fu_246_p2;
wire   [9:0] trunc_ln17_111_fu_3766_p4;
wire   [14:0] shl_ln864_84_fu_3780_p3;
wire   [12:0] shl_ln864_85_fu_3792_p3;
wire   [15:0] zext_ln864_168_fu_3788_p1;
wire   [15:0] zext_ln864_169_fu_3800_p1;
wire   [15:0] sub_ln864_43_fu_3804_p2;
wire   [10:0] trunc_ln17_112_fu_3810_p4;
wire   [14:0] r_V_187_fu_245_p2;
wire   [14:0] shl_ln1319_81_fu_3844_p3;
wire   [12:0] shl_ln1319_82_fu_3856_p3;
wire   [15:0] zext_ln1319_184_fu_3864_p1;
wire   [15:0] zext_ln1319_183_fu_3852_p1;
wire   [15:0] r_V_188_fu_3868_p2;
wire   [10:0] trunc_ln864_223_fu_3874_p4;
wire   [14:0] mul_ln864_82_fu_238_p2;
wire   [9:0] trunc_ln17_113_fu_3888_p4;
wire   [13:0] tmp_fu_3908_p3;
wire   [14:0] zext_ln1319_186_fu_3916_p1;
wire   [14:0] r_V_189_fu_3920_p2;
wire   [9:0] trunc_ln864_224_fu_3926_p4;
wire   [14:0] r_V_190_fu_220_p2;
wire   [9:0] trunc_ln864_225_fu_3940_p4;
wire   [14:0] mul_ln864_83_fu_239_p2;
wire   [13:0] mul_ln864_84_fu_231_p2;
wire   [8:0] trunc_ln17_115_fu_3974_p4;
wire   [15:0] r_V_191_fu_235_p2;
wire   [13:0] shl_ln864_86_fu_4004_p3;
wire   [14:0] mul_ln864_85_fu_233_p2;
wire   [9:0] trunc_ln17_116_fu_4016_p4;
wire   [9:0] shl_ln864_87_fu_4030_p3;
wire   [14:0] zext_ln864_172_fu_4012_p1;
wire   [14:0] zext_ln864_173_fu_4038_p1;
wire   [14:0] add_ln864_46_fu_4042_p2;
wire   [11:0] shl_ln864_88_fu_4058_p3;
wire   [14:0] zext_ln864_174_fu_4066_p1;
wire   [14:0] add_ln864_47_fu_4070_p2;
wire   [9:0] trunc_ln17_118_fu_4076_p4;
wire   [14:0] r_V_192_fu_221_p2;
wire   [14:0] r_V_193_fu_232_p2;
wire   [13:0] shl_ln864_89_fu_4116_p3;
wire   [11:0] shl_ln864_90_fu_4128_p3;
wire   [14:0] zext_ln864_175_fu_4124_p1;
wire   [14:0] zext_ln864_176_fu_4136_p1;
wire   [14:0] sub_ln864_44_fu_4140_p2;
wire   [9:0] trunc_ln864_229_fu_4146_p4;
wire  signed [10:0] sext_ln17_43_fu_4156_p1;
wire   [14:0] r_V_194_fu_230_p2;
wire   [9:0] trunc_ln864_230_fu_4164_p4;
wire   [15:0] r_V_195_fu_248_p2;
wire   [14:0] shl_ln1319_83_fu_4193_p3;
wire   [11:0] shl_ln1319_84_fu_4205_p3;
wire   [15:0] zext_ln1319_190_fu_4213_p1;
wire   [15:0] zext_ln1319_189_fu_4201_p1;
wire   [15:0] r_V_196_fu_4217_p2;
wire   [13:0] shl_ln864_91_fu_4240_p3;
wire   [14:0] mul_ln864_86_fu_222_p2;
wire   [9:0] trunc_ln17_119_fu_4252_p4;
wire   [14:0] zext_ln864_177_fu_4248_p1;
wire   [14:0] sub_ln864_45_fu_4266_p2;
wire   [14:0] mul_ln864_87_fu_236_p2;
wire   [11:0] shl_ln864_92_fu_4292_p3;
wire   [14:0] zext_ln864_179_fu_4300_p1;
wire   [14:0] sub_ln864_46_fu_4304_p2;
wire   [9:0] trunc_ln864_234_fu_4310_p4;
wire  signed [10:0] sext_ln17_44_fu_4320_p1;
wire   [14:0] r_V_197_fu_224_p2;
wire   [9:0] trunc_ln864_235_fu_4328_p4;
wire   [14:0] r_V_198_fu_223_p2;
wire   [10:0] zext_ln17_168_fu_3776_p1;
wire   [10:0] zext_ln17_170_fu_3898_p1;
wire   [10:0] zext_ln17_167_fu_3738_p1;
wire   [10:0] zext_ln17_173_fu_4086_p1;
wire  signed [10:0] sext_ln864_fu_3495_p1;
wire  signed [10:0] sext_ln70_22_fu_3678_p1;
wire  signed [11:0] sext_ln864_91_fu_3884_p1;
wire  signed [11:0] sext_ln864_92_fu_3950_p1;
wire   [10:0] zext_ln17_172_fu_4026_p1;
wire   [10:0] zext_ln17_175_fu_4262_p1;
wire  signed [10:0] sext_ln1319_80_fu_3936_p1;
wire   [10:0] add_ln859_417_fu_4387_p2;
wire  signed [11:0] sext_ln859_231_fu_4393_p1;
wire  signed [11:0] sext_ln1319_79_fu_3441_p1;
wire   [9:0] zext_ln17_171_fu_3984_p1;
wire   [9:0] trunc_ln17_117_fu_4048_p4;
wire   [11:0] zext_ln17_163_fu_3595_p1;
wire   [11:0] zext_ln17_165_fu_3710_p1;
wire   [11:0] zext_ln17_174_fu_4160_p1;
wire   [11:0] zext_ln17_176_fu_4324_p1;
wire   [11:0] add_ln859_430_fu_4415_p2;
wire   [12:0] zext_ln859_107_fu_4421_p1;
wire   [12:0] zext_ln17_166_fu_3724_p1;
wire  signed [11:0] sext_ln70_fu_3609_p1;
wire  signed [11:0] sext_ln864_90_fu_3757_p1;
wire   [11:0] zext_ln17_169_fu_3820_p1;
wire  signed [10:0] sext_ln70_27_fu_4174_p1;
wire  signed [10:0] sext_ln70_29_fu_4338_p1;
wire    ap_CS_fsm_state2;
wire  signed [10:0] sext_ln864_94_fu_4485_p1;
wire   [11:0] zext_ln859_fu_4498_p1;
wire   [11:0] zext_ln17_fu_4449_p1;
wire   [11:0] add_ln859_404_fu_4501_p2;
wire  signed [10:0] sext_ln70_26_fu_4473_p1;
wire   [10:0] add_ln859_405_fu_4511_p2;
wire  signed [11:0] sext_ln859_223_fu_4517_p1;
wire   [11:0] zext_ln70_10_fu_4467_p1;
wire   [11:0] add_ln859_406_fu_4521_p2;
wire  signed [13:0] sext_ln859_224_fu_4527_p1;
wire   [13:0] zext_ln859_100_fu_4507_p1;
wire   [13:0] add_ln859_407_fu_4531_p2;
wire  signed [12:0] sext_ln859_225_fu_4544_p1;
wire   [12:0] zext_ln859_103_fu_4541_p1;
wire   [12:0] add_ln859_410_fu_4547_p2;
wire  signed [11:0] sext_ln70_28_fu_4482_p1;
wire   [11:0] add_ln859_412_fu_4560_p2;
wire  signed [12:0] sext_ln859_228_fu_4566_p1;
wire  signed [12:0] sext_ln859_227_fu_4557_p1;
wire   [12:0] add_ln859_413_fu_4570_p2;
wire  signed [13:0] sext_ln859_229_fu_4576_p1;
wire  signed [13:0] sext_ln859_226_fu_4553_p1;
wire   [13:0] add_ln859_414_fu_4580_p2;
wire   [11:0] zext_ln859_102_fu_4590_p1;
wire   [11:0] zext_ln17_164_fu_4455_p1;
wire   [11:0] add_ln859_416_fu_4593_p2;
wire  signed [13:0] sext_ln859_232_fu_4603_p1;
wire   [13:0] zext_ln859_105_fu_4599_p1;
wire   [13:0] add_ln859_419_fu_4606_p2;
wire   [10:0] zext_ln859_104_fu_4616_p1;
wire   [10:0] zext_ln17_162_fu_4452_p1;
wire   [10:0] add_ln859_421_fu_4619_p2;
wire   [12:0] zext_ln864_178_fu_4488_p1;
wire  signed [12:0] sext_ln864_89_fu_4458_p1;
wire  signed [11:0] sext_ln1319_81_fu_4479_p1;
wire   [11:0] add_ln859_423_fu_4635_p2;
wire  signed [12:0] sext_ln859_233_fu_4641_p1;
wire   [12:0] add_ln859_422_fu_4629_p2;
wire   [12:0] add_ln859_424_fu_4645_p2;
wire  signed [13:0] sext_ln859_234_fu_4651_p1;
wire   [13:0] zext_ln859_108_fu_4625_p1;
wire   [13:0] add_ln859_425_fu_4655_p2;
wire  signed [10:0] sext_ln864_93_fu_4476_p1;
wire   [10:0] add_ln859_427_fu_4668_p2;
wire  signed [11:0] sext_ln859_235_fu_4674_p1;
wire   [11:0] zext_ln864_180_fu_4492_p1;
wire   [11:0] add_ln859_428_fu_4678_p2;
wire  signed [13:0] sext_ln859_236_fu_4684_p1;
wire   [13:0] zext_ln859_106_fu_4665_p1;
wire   [13:0] add_ln859_429_fu_4688_p2;
wire  signed [10:0] sext_ln70_24_fu_4464_p1;
wire   [10:0] add_ln859_433_fu_4704_p2;
wire  signed [12:0] sext_ln859_238_fu_4710_p1;
wire  signed [12:0] sext_ln859_237_fu_4701_p1;
wire   [12:0] add_ln859_434_fu_4714_p2;
wire  signed [13:0] sext_ln859_239_fu_4720_p1;
wire   [13:0] zext_ln859_109_fu_4698_p1;
wire   [13:0] add_ln859_435_fu_4724_p2;
wire  signed [11:0] sext_ln70_23_fu_4461_p1;
wire  signed [11:0] sext_ln70_25_fu_4470_p1;
wire   [11:0] add_ln859_437_fu_4737_p2;
wire  signed [13:0] sext_ln859_241_fu_4743_p1;
wire   [13:0] zext_ln859_110_fu_4734_p1;
wire  signed [10:0] sext_ln859_222_fu_4495_p1;
wire   [10:0] add_ln859_440_fu_4756_p2;
wire  signed [11:0] sext_ln859_243_fu_4762_p1;
wire  signed [11:0] sext_ln859_242_fu_4753_p1;
wire   [11:0] add_ln859_441_fu_4766_p2;
wire  signed [13:0] sext_ln859_244_fu_4772_p1;
wire   [13:0] add_ln859_438_fu_4747_p2;
wire   [13:0] add_ln859_442_fu_4776_p2;
wire  signed [15:0] sext_ln859_126_fu_4612_p1;
wire  signed [15:0] sext_ln859_128_fu_4661_p1;
wire  signed [15:0] sext_ln859_129_fu_4694_p1;
wire  signed [15:0] sext_ln859_240_fu_4730_p1;
wire  signed [15:0] sext_ln859_230_fu_4586_p1;
wire  signed [15:0] sext_ln859_fu_4537_p1;
wire  signed [15:0] add_ln859_442_cast_fu_4782_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire   [14:0] mul_ln864_77_fu_227_p00;
wire   [14:0] mul_ln864_81_fu_246_p00;
wire   [14:0] mul_ln864_82_fu_238_p00;
wire   [13:0] mul_ln864_84_fu_231_p00;
wire   [13:0] mul_ln864_fu_242_p00;
wire   [14:0] r_V_183_fu_226_p00;
wire   [15:0] r_V_186_fu_244_p00;
wire   [14:0] r_V_187_fu_245_p00;
wire   [15:0] r_V_191_fu_235_p00;
wire   [15:0] r_V_195_fu_248_p00;
wire   [14:0] r_V_198_fu_223_p00;
wire   [15:0] r_V_fu_247_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U554(
    .din0(r_V_190_fu_220_p0),
    .din1(r_V_190_fu_220_p1),
    .dout(r_V_190_fu_220_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U555(
    .din0(r_V_192_fu_221_p0),
    .din1(r_V_192_fu_221_p1),
    .dout(r_V_192_fu_221_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U556(
    .din0(mul_ln864_86_fu_222_p0),
    .din1(mul_ln864_86_fu_222_p1),
    .dout(mul_ln864_86_fu_222_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U557(
    .din0(r_V_198_fu_223_p0),
    .din1(r_V_198_fu_223_p1),
    .dout(r_V_198_fu_223_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U558(
    .din0(r_V_197_fu_224_p0),
    .din1(r_V_197_fu_224_p1),
    .dout(r_V_197_fu_224_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U559(
    .din0(mul_ln864_79_fu_225_p0),
    .din1(mul_ln864_79_fu_225_p1),
    .dout(mul_ln864_79_fu_225_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U560(
    .din0(r_V_183_fu_226_p0),
    .din1(r_V_183_fu_226_p1),
    .dout(r_V_183_fu_226_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U561(
    .din0(mul_ln864_77_fu_227_p0),
    .din1(mul_ln864_77_fu_227_p1),
    .dout(mul_ln864_77_fu_227_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U562(
    .din0(mul_ln864_80_fu_228_p0),
    .din1(mul_ln864_80_fu_228_p1),
    .dout(mul_ln864_80_fu_228_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U563(
    .din0(r_V_194_fu_230_p0),
    .din1(r_V_194_fu_230_p1),
    .dout(r_V_194_fu_230_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U564(
    .din0(mul_ln864_84_fu_231_p0),
    .din1(mul_ln864_84_fu_231_p1),
    .dout(mul_ln864_84_fu_231_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U565(
    .din0(r_V_193_fu_232_p0),
    .din1(r_V_193_fu_232_p1),
    .dout(r_V_193_fu_232_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U566(
    .din0(mul_ln864_85_fu_233_p0),
    .din1(mul_ln864_85_fu_233_p1),
    .dout(mul_ln864_85_fu_233_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U567(
    .din0(r_V_191_fu_235_p0),
    .din1(r_V_191_fu_235_p1),
    .dout(r_V_191_fu_235_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U568(
    .din0(mul_ln864_87_fu_236_p0),
    .din1(mul_ln864_87_fu_236_p1),
    .dout(mul_ln864_87_fu_236_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U569(
    .din0(r_V_185_fu_237_p0),
    .din1(r_V_185_fu_237_p1),
    .dout(r_V_185_fu_237_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U570(
    .din0(mul_ln864_82_fu_238_p0),
    .din1(mul_ln864_82_fu_238_p1),
    .dout(mul_ln864_82_fu_238_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U571(
    .din0(mul_ln864_83_fu_239_p0),
    .din1(mul_ln864_83_fu_239_p1),
    .dout(mul_ln864_83_fu_239_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U572(
    .din0(mul_ln864_fu_242_p0),
    .din1(mul_ln864_fu_242_p1),
    .dout(mul_ln864_fu_242_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U573(
    .din0(r_V_186_fu_244_p0),
    .din1(r_V_186_fu_244_p1),
    .dout(r_V_186_fu_244_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U574(
    .din0(r_V_187_fu_245_p0),
    .din1(r_V_187_fu_245_p1),
    .dout(r_V_187_fu_245_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U575(
    .din0(mul_ln864_81_fu_246_p0),
    .din1(mul_ln864_81_fu_246_p1),
    .dout(mul_ln864_81_fu_246_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U576(
    .din0(r_V_fu_247_p0),
    .din1(r_V_fu_247_p1),
    .dout(r_V_fu_247_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U577(
    .din0(r_V_195_fu_248_p0),
    .din1(r_V_195_fu_248_p1),
    .dout(r_V_195_fu_248_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U578(
    .din0(mul_ln864_78_fu_249_p0),
    .din1(mul_ln864_78_fu_249_p1),
    .dout(mul_ln864_78_fu_249_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln859_408_reg_4904 <= add_ln859_408_fu_4363_p2;
        add_ln859_409_reg_4909 <= add_ln859_409_fu_4369_p2;
        add_ln859_411_reg_4914 <= add_ln859_411_fu_4375_p2;
        add_ln859_415_reg_4919 <= add_ln859_415_fu_4381_p2;
        add_ln859_418_reg_4924 <= add_ln859_418_fu_4397_p2;
        add_ln859_420_reg_4929 <= add_ln859_420_fu_4403_p2;
        add_ln859_426_reg_4934 <= add_ln859_426_fu_4409_p2;
        add_ln859_431_reg_4939 <= add_ln859_431_fu_4425_p2;
        add_ln859_432_reg_4944 <= add_ln859_432_fu_4431_p2;
        add_ln859_436_reg_4949 <= add_ln859_436_fu_4437_p2;
        add_ln859_439_reg_4954 <= add_ln859_439_fu_4443_p2;
        add_ln859_reg_4899 <= add_ln859_fu_4357_p2;
        trunc_ln17_107_reg_4838 <= {{mul_ln864_77_fu_227_p2[14:5]}};
        trunc_ln17_114_reg_4854 <= {{mul_ln864_83_fu_239_p2[14:5]}};
        trunc_ln17_120_reg_4889 <= {{mul_ln864_87_fu_236_p2[14:5]}};
        trunc_ln17_s_reg_4833 <= {{mul_ln864_fu_242_p2[13:5]}};
        trunc_ln4_reg_4828 <= {{add_ln864_fu_3515_p2[15:5]}};
        trunc_ln864_220_reg_4843 <= {{r_V_185_fu_237_p2[14:5]}};
        trunc_ln864_222_reg_4848 <= {{r_V_187_fu_245_p2[14:5]}};
        trunc_ln864_226_reg_4859 <= {{r_V_191_fu_235_p2[15:5]}};
        trunc_ln864_227_reg_4864 <= {{r_V_192_fu_221_p2[14:5]}};
        trunc_ln864_228_reg_4869 <= {{r_V_193_fu_232_p2[14:5]}};
        trunc_ln864_231_reg_4874 <= {{r_V_195_fu_248_p2[15:5]}};
        trunc_ln864_232_reg_4879 <= {{r_V_196_fu_4217_p2[15:5]}};
        trunc_ln864_233_reg_4884 <= {{sub_ln864_45_fu_4266_p2[14:5]}};
        trunc_ln864_236_reg_4894 <= {{r_V_198_fu_223_p2[14:5]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln859_404_fu_4501_p2 = (zext_ln859_fu_4498_p1 + zext_ln17_fu_4449_p1);

assign add_ln859_405_fu_4511_p2 = ($signed(sext_ln70_26_fu_4473_p1) + $signed(11'd16));

assign add_ln859_406_fu_4521_p2 = ($signed(sext_ln859_223_fu_4517_p1) + $signed(zext_ln70_10_fu_4467_p1));

assign add_ln859_407_fu_4531_p2 = ($signed(sext_ln859_224_fu_4527_p1) + $signed(zext_ln859_100_fu_4507_p1));

assign add_ln859_408_fu_4363_p2 = (zext_ln17_167_fu_3738_p1 + zext_ln17_173_fu_4086_p1);

assign add_ln859_409_fu_4369_p2 = ($signed(sext_ln864_fu_3495_p1) + $signed(sext_ln70_22_fu_3678_p1));

assign add_ln859_410_fu_4547_p2 = ($signed(sext_ln859_225_fu_4544_p1) + $signed(zext_ln859_103_fu_4541_p1));

assign add_ln859_411_fu_4375_p2 = ($signed(sext_ln864_91_fu_3884_p1) + $signed(sext_ln864_92_fu_3950_p1));

assign add_ln859_412_fu_4560_p2 = ($signed(sext_ln70_28_fu_4482_p1) + $signed(12'd208));

assign add_ln859_413_fu_4570_p2 = ($signed(sext_ln859_228_fu_4566_p1) + $signed(sext_ln859_227_fu_4557_p1));

assign add_ln859_414_fu_4580_p2 = ($signed(sext_ln859_229_fu_4576_p1) + $signed(sext_ln859_226_fu_4553_p1));

assign add_ln859_415_fu_4381_p2 = (zext_ln17_172_fu_4026_p1 + zext_ln17_175_fu_4262_p1);

assign add_ln859_416_fu_4593_p2 = (zext_ln859_102_fu_4590_p1 + zext_ln17_164_fu_4455_p1);

assign add_ln859_417_fu_4387_p2 = ($signed(sext_ln1319_80_fu_3936_p1) + $signed(11'd16));

assign add_ln859_418_fu_4397_p2 = ($signed(sext_ln859_231_fu_4393_p1) + $signed(sext_ln1319_79_fu_3441_p1));

assign add_ln859_419_fu_4606_p2 = ($signed(sext_ln859_232_fu_4603_p1) + $signed(zext_ln859_105_fu_4599_p1));

assign add_ln859_420_fu_4403_p2 = (zext_ln17_171_fu_3984_p1 + trunc_ln17_117_fu_4048_p4);

assign add_ln859_421_fu_4619_p2 = (zext_ln859_104_fu_4616_p1 + zext_ln17_162_fu_4452_p1);

assign add_ln859_422_fu_4629_p2 = ($signed(zext_ln864_178_fu_4488_p1) + $signed(sext_ln864_89_fu_4458_p1));

assign add_ln859_423_fu_4635_p2 = ($signed(sext_ln1319_81_fu_4479_p1) + $signed(12'd48));

assign add_ln859_424_fu_4645_p2 = ($signed(sext_ln859_233_fu_4641_p1) + $signed(add_ln859_422_fu_4629_p2));

assign add_ln859_425_fu_4655_p2 = ($signed(sext_ln859_234_fu_4651_p1) + $signed(zext_ln859_108_fu_4625_p1));

assign add_ln859_426_fu_4409_p2 = (zext_ln17_163_fu_3595_p1 + zext_ln17_165_fu_3710_p1);

assign add_ln859_427_fu_4668_p2 = ($signed(sext_ln864_93_fu_4476_p1) + $signed(11'd2032));

assign add_ln859_428_fu_4678_p2 = ($signed(sext_ln859_235_fu_4674_p1) + $signed(zext_ln864_180_fu_4492_p1));

assign add_ln859_429_fu_4688_p2 = ($signed(sext_ln859_236_fu_4684_p1) + $signed(zext_ln859_106_fu_4665_p1));

assign add_ln859_430_fu_4415_p2 = (zext_ln17_174_fu_4160_p1 + zext_ln17_176_fu_4324_p1);

assign add_ln859_431_fu_4425_p2 = (zext_ln859_107_fu_4421_p1 + zext_ln17_166_fu_3724_p1);

assign add_ln859_432_fu_4431_p2 = ($signed(sext_ln70_fu_3609_p1) + $signed(sext_ln864_90_fu_3757_p1));

assign add_ln859_433_fu_4704_p2 = ($signed(sext_ln70_24_fu_4464_p1) + $signed(11'd48));

assign add_ln859_434_fu_4714_p2 = ($signed(sext_ln859_238_fu_4710_p1) + $signed(sext_ln859_237_fu_4701_p1));

assign add_ln859_435_fu_4724_p2 = ($signed(sext_ln859_239_fu_4720_p1) + $signed(zext_ln859_109_fu_4698_p1));

assign add_ln859_436_fu_4437_p2 = (zext_ln17_163_fu_3595_p1 + zext_ln17_169_fu_3820_p1);

assign add_ln859_437_fu_4737_p2 = ($signed(sext_ln70_23_fu_4461_p1) + $signed(sext_ln70_25_fu_4470_p1));

assign add_ln859_438_fu_4747_p2 = ($signed(sext_ln859_241_fu_4743_p1) + $signed(zext_ln859_110_fu_4734_p1));

assign add_ln859_439_fu_4443_p2 = ($signed(sext_ln70_27_fu_4174_p1) + $signed(sext_ln70_29_fu_4338_p1));

assign add_ln859_440_fu_4756_p2 = ($signed(sext_ln859_222_fu_4495_p1) + $signed(11'd256));

assign add_ln859_441_fu_4766_p2 = ($signed(sext_ln859_243_fu_4762_p1) + $signed(sext_ln859_242_fu_4753_p1));

assign add_ln859_442_cast_fu_4782_p1 = $signed(add_ln859_442_fu_4776_p2);

assign add_ln859_442_fu_4776_p2 = ($signed(sext_ln859_244_fu_4772_p1) + $signed(add_ln859_438_fu_4747_p2));

assign add_ln859_fu_4357_p2 = (zext_ln17_168_fu_3776_p1 + zext_ln17_170_fu_3898_p1);

assign add_ln864_46_fu_4042_p2 = (zext_ln864_172_fu_4012_p1 + zext_ln864_173_fu_4038_p1);

assign add_ln864_47_fu_4070_p2 = (zext_ln864_172_fu_4012_p1 + zext_ln864_174_fu_4066_p1);

assign add_ln864_fu_3515_p2 = (zext_ln864_fu_3507_p1 + zext_ln864_162_fu_3511_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return_0 = sext_ln859_126_fu_4612_p1;

assign ap_return_1 = sext_ln859_128_fu_4661_p1;

assign ap_return_2 = sext_ln859_129_fu_4694_p1;

assign ap_return_3 = sext_ln859_240_fu_4730_p1;

assign ap_return_4 = sext_ln859_230_fu_4586_p1;

assign ap_return_5 = sext_ln859_fu_4537_p1;

assign ap_return_6 = add_ln859_442_cast_fu_4782_p1;

assign mul_ln864_77_fu_227_p0 = mul_ln864_77_fu_227_p00;

assign mul_ln864_77_fu_227_p00 = p_read2;

assign mul_ln864_77_fu_227_p1 = 15'd53;

assign mul_ln864_78_fu_249_p0 = zext_ln1319_179_fu_3682_p1;

assign mul_ln864_78_fu_249_p1 = 15'd51;

assign mul_ln864_79_fu_225_p0 = zext_ln1319_179_fu_3682_p1;

assign mul_ln864_79_fu_225_p1 = 15'd41;

assign mul_ln864_80_fu_228_p0 = zext_ln1319_179_fu_3682_p1;

assign mul_ln864_80_fu_228_p1 = 15'd35;

assign mul_ln864_81_fu_246_p0 = mul_ln864_81_fu_246_p00;

assign mul_ln864_81_fu_246_p00 = p_read4;

assign mul_ln864_81_fu_246_p1 = 15'd55;

assign mul_ln864_82_fu_238_p0 = mul_ln864_82_fu_238_p00;

assign mul_ln864_82_fu_238_p00 = p_read6;

assign mul_ln864_82_fu_238_p1 = 15'd41;

assign mul_ln864_83_fu_239_p0 = zext_ln1319_185_fu_3902_p1;

assign mul_ln864_83_fu_239_p1 = 15'd50;

assign mul_ln864_84_fu_231_p0 = mul_ln864_84_fu_231_p00;

assign mul_ln864_84_fu_231_p00 = p_read8;

assign mul_ln864_84_fu_231_p1 = 14'd21;

assign mul_ln864_85_fu_233_p0 = zext_ln864_171_fu_3998_p1;

assign mul_ln864_85_fu_233_p1 = 15'd41;

assign mul_ln864_86_fu_222_p0 = zext_ln70_8_fu_4233_p1;

assign mul_ln864_86_fu_222_p1 = 15'd46;

assign mul_ln864_87_fu_236_p0 = zext_ln70_8_fu_4233_p1;

assign mul_ln864_87_fu_236_p1 = 15'd52;

assign mul_ln864_fu_242_p0 = mul_ln864_fu_242_p00;

assign mul_ln864_fu_242_p00 = p_read1;

assign mul_ln864_fu_242_p1 = 14'd23;

assign r_V_182_fu_3479_p2 = ($signed(sext_ln1319_fu_3463_p1) - $signed(zext_ln1319_176_fu_3475_p1));

assign r_V_183_fu_226_p0 = r_V_183_fu_226_p00;

assign r_V_183_fu_226_p00 = p_read1;

assign r_V_183_fu_226_p1 = 15'd32741;

assign r_V_184_fu_3662_p2 = ($signed(sext_ln1319_27_fu_3646_p1) - $signed(zext_ln1319_178_fu_3658_p1));

assign r_V_185_fu_237_p0 = zext_ln1319_179_fu_3682_p1;

assign r_V_185_fu_237_p1 = 15'd32742;

assign r_V_186_fu_244_p0 = r_V_186_fu_244_p00;

assign r_V_186_fu_244_p00 = p_read4;

assign r_V_186_fu_244_p1 = 16'd65479;

assign r_V_187_fu_245_p0 = r_V_187_fu_245_p00;

assign r_V_187_fu_245_p00 = p_read5;

assign r_V_187_fu_245_p1 = 15'd32747;

assign r_V_188_fu_3868_p2 = (zext_ln1319_184_fu_3864_p1 - zext_ln1319_183_fu_3852_p1);

assign r_V_189_fu_3920_p2 = (zext_ln1319_185_fu_3902_p1 - zext_ln1319_186_fu_3916_p1);

assign r_V_190_fu_220_p0 = zext_ln1319_185_fu_3902_p1;

assign r_V_190_fu_220_p1 = 15'd32741;

assign r_V_191_fu_235_p0 = r_V_191_fu_235_p00;

assign r_V_191_fu_235_p00 = p_read8;

assign r_V_191_fu_235_p1 = 16'd65501;

assign r_V_192_fu_221_p0 = zext_ln864_171_fu_3998_p1;

assign r_V_192_fu_221_p1 = 15'd32749;

assign r_V_193_fu_232_p0 = zext_ln1319_187_fu_4100_p1;

assign r_V_193_fu_232_p1 = 15'd32749;

assign r_V_194_fu_230_p0 = zext_ln1319_187_fu_4100_p1;

assign r_V_194_fu_230_p1 = 15'd32747;

assign r_V_195_fu_248_p0 = r_V_195_fu_248_p00;

assign r_V_195_fu_248_p00 = p_read12;

assign r_V_195_fu_248_p1 = 16'd65493;

assign r_V_196_fu_4217_p2 = (zext_ln1319_190_fu_4213_p1 - zext_ln1319_189_fu_4201_p1);

assign r_V_197_fu_224_p0 = zext_ln70_8_fu_4233_p1;

assign r_V_197_fu_224_p1 = 15'd32743;

assign r_V_198_fu_223_p0 = r_V_198_fu_223_p00;

assign r_V_198_fu_223_p00 = p_read14;

assign r_V_198_fu_223_p1 = 15'd32743;

assign r_V_fu_247_p0 = r_V_fu_247_p00;

assign r_V_fu_247_p00 = p_read;

assign r_V_fu_247_p1 = 16'd65482;

assign sext_ln1319_27_fu_3646_p1 = $signed(sub_ln1319_108_fu_3640_p2);

assign sext_ln1319_79_fu_3441_p1 = $signed(trunc_ln_fu_3431_p4);

assign sext_ln1319_80_fu_3936_p1 = $signed(trunc_ln864_224_fu_3926_p4);

assign sext_ln1319_81_fu_4479_p1 = $signed(trunc_ln864_231_reg_4874);

assign sext_ln1319_fu_3463_p1 = $signed(sub_ln1319_fu_3457_p2);

assign sext_ln17_43_fu_4156_p1 = $signed(trunc_ln864_229_fu_4146_p4);

assign sext_ln17_44_fu_4320_p1 = $signed(trunc_ln864_234_fu_4310_p4);

assign sext_ln17_fu_3591_p1 = $signed(trunc_ln864_217_fu_3581_p4);

assign sext_ln70_22_fu_3678_p1 = $signed(trunc_ln864_219_fu_3668_p4);

assign sext_ln70_23_fu_4461_p1 = trunc_ln864_222_reg_4848;

assign sext_ln70_24_fu_4464_p1 = trunc_ln864_222_reg_4848;

assign sext_ln70_25_fu_4470_p1 = $signed(trunc_ln864_226_reg_4859);

assign sext_ln70_26_fu_4473_p1 = $signed(trunc_ln864_227_reg_4864);

assign sext_ln70_27_fu_4174_p1 = $signed(trunc_ln864_230_fu_4164_p4);

assign sext_ln70_28_fu_4482_p1 = $signed(trunc_ln864_232_reg_4879);

assign sext_ln70_29_fu_4338_p1 = $signed(trunc_ln864_235_fu_4328_p4);

assign sext_ln70_fu_3609_p1 = $signed(trunc_ln864_218_fu_3599_p4);

assign sext_ln859_126_fu_4612_p1 = $signed(add_ln859_419_fu_4606_p2);

assign sext_ln859_128_fu_4661_p1 = $signed(add_ln859_425_fu_4655_p2);

assign sext_ln859_129_fu_4694_p1 = $signed(add_ln859_429_fu_4688_p2);

assign sext_ln859_222_fu_4495_p1 = $signed(trunc_ln864_236_reg_4894);

assign sext_ln859_223_fu_4517_p1 = $signed(add_ln859_405_fu_4511_p2);

assign sext_ln859_224_fu_4527_p1 = $signed(add_ln859_406_fu_4521_p2);

assign sext_ln859_225_fu_4544_p1 = $signed(add_ln859_409_reg_4909);

assign sext_ln859_226_fu_4553_p1 = $signed(add_ln859_410_fu_4547_p2);

assign sext_ln859_227_fu_4557_p1 = $signed(add_ln859_411_reg_4914);

assign sext_ln859_228_fu_4566_p1 = $signed(add_ln859_412_fu_4560_p2);

assign sext_ln859_229_fu_4576_p1 = $signed(add_ln859_413_fu_4570_p2);

assign sext_ln859_230_fu_4586_p1 = $signed(add_ln859_414_fu_4580_p2);

assign sext_ln859_231_fu_4393_p1 = $signed(add_ln859_417_fu_4387_p2);

assign sext_ln859_232_fu_4603_p1 = $signed(add_ln859_418_reg_4924);

assign sext_ln859_233_fu_4641_p1 = $signed(add_ln859_423_fu_4635_p2);

assign sext_ln859_234_fu_4651_p1 = $signed(add_ln859_424_fu_4645_p2);

assign sext_ln859_235_fu_4674_p1 = $signed(add_ln859_427_fu_4668_p2);

assign sext_ln859_236_fu_4684_p1 = $signed(add_ln859_428_fu_4678_p2);

assign sext_ln859_237_fu_4701_p1 = $signed(add_ln859_432_reg_4944);

assign sext_ln859_238_fu_4710_p1 = $signed(add_ln859_433_fu_4704_p2);

assign sext_ln859_239_fu_4720_p1 = $signed(add_ln859_434_fu_4714_p2);

assign sext_ln859_240_fu_4730_p1 = $signed(add_ln859_435_fu_4724_p2);

assign sext_ln859_241_fu_4743_p1 = $signed(add_ln859_437_fu_4737_p2);

assign sext_ln859_242_fu_4753_p1 = $signed(add_ln859_439_reg_4954);

assign sext_ln859_243_fu_4762_p1 = $signed(add_ln859_440_fu_4756_p2);

assign sext_ln859_244_fu_4772_p1 = $signed(add_ln859_441_fu_4766_p2);

assign sext_ln859_fu_4537_p1 = $signed(add_ln859_407_fu_4531_p2);

assign sext_ln864_89_fu_4458_p1 = $signed(trunc_ln864_220_reg_4843);

assign sext_ln864_90_fu_3757_p1 = $signed(trunc_ln864_221_fu_3747_p4);

assign sext_ln864_91_fu_3884_p1 = $signed(trunc_ln864_223_fu_3874_p4);

assign sext_ln864_92_fu_3950_p1 = $signed(trunc_ln864_225_fu_3940_p4);

assign sext_ln864_93_fu_4476_p1 = $signed(trunc_ln864_228_reg_4869);

assign sext_ln864_94_fu_4485_p1 = $signed(trunc_ln864_233_reg_4884);

assign sext_ln864_fu_3495_p1 = $signed(trunc_ln864_s_fu_3485_p4);

assign shl_ln1319_79_fu_3628_p3 = {{p_read2}, {4'd0}};

assign shl_ln1319_80_fu_3650_p3 = {{p_read2}, {2'd0}};

assign shl_ln1319_81_fu_3844_p3 = {{p_read6}, {6'd0}};

assign shl_ln1319_82_fu_3856_p3 = {{p_read6}, {4'd0}};

assign shl_ln1319_83_fu_4193_p3 = {{p_read12}, {6'd0}};

assign shl_ln1319_84_fu_4205_p3 = {{p_read12}, {3'd0}};

assign shl_ln1319_s_fu_3467_p3 = {{p_read}, {1'd0}};

assign shl_ln2_fu_3499_p3 = {{p_read}, {6'd0}};

assign shl_ln864_83_fu_3563_p3 = {{p_read1}, {3'd0}};

assign shl_ln864_84_fu_3780_p3 = {{p_read4}, {6'd0}};

assign shl_ln864_85_fu_3792_p3 = {{p_read4}, {4'd0}};

assign shl_ln864_86_fu_4004_p3 = {{p_read9}, {5'd0}};

assign shl_ln864_87_fu_4030_p3 = {{p_read9}, {1'd0}};

assign shl_ln864_88_fu_4058_p3 = {{p_read9}, {3'd0}};

assign shl_ln864_89_fu_4116_p3 = {{p_read11}, {5'd0}};

assign shl_ln864_90_fu_4128_p3 = {{p_read11}, {3'd0}};

assign shl_ln864_91_fu_4240_p3 = {{p_read13}, {5'd0}};

assign shl_ln864_92_fu_4292_p3 = {{p_read13}, {3'd0}};

assign shl_ln864_s_fu_3551_p3 = {{p_read1}, {5'd0}};

assign shl_ln_fu_3445_p3 = {{p_read}, {4'd0}};

assign sub_ln1319_108_fu_3640_p2 = (14'd0 - zext_ln1319_177_fu_3636_p1);

assign sub_ln1319_fu_3457_p2 = (14'd0 - zext_ln1319_175_fu_3453_p1);

assign sub_ln864_43_fu_3804_p2 = (zext_ln864_168_fu_3788_p1 - zext_ln864_169_fu_3800_p1);

assign sub_ln864_44_fu_4140_p2 = (zext_ln864_175_fu_4124_p1 - zext_ln864_176_fu_4136_p1);

assign sub_ln864_45_fu_4266_p2 = (zext_ln864_177_fu_4248_p1 - zext_ln70_8_fu_4233_p1);

assign sub_ln864_46_fu_4304_p2 = (zext_ln864_177_fu_4248_p1 - zext_ln864_179_fu_4300_p1);

assign sub_ln864_fu_3575_p2 = (zext_ln864_164_fu_3559_p1 - zext_ln864_165_fu_3571_p1);

assign tmp_fu_3908_p3 = {{p_read7}, {5'd0}};

assign trunc_ln17_108_fu_3700_p4 = {{mul_ln864_78_fu_249_p2[14:5]}};

assign trunc_ln17_109_fu_3714_p4 = {{mul_ln864_79_fu_225_p2[14:5]}};

assign trunc_ln17_110_fu_3728_p4 = {{mul_ln864_80_fu_228_p2[14:5]}};

assign trunc_ln17_111_fu_3766_p4 = {{mul_ln864_81_fu_246_p2[14:5]}};

assign trunc_ln17_112_fu_3810_p4 = {{sub_ln864_43_fu_3804_p2[15:5]}};

assign trunc_ln17_113_fu_3888_p4 = {{mul_ln864_82_fu_238_p2[14:5]}};

assign trunc_ln17_115_fu_3974_p4 = {{mul_ln864_84_fu_231_p2[13:5]}};

assign trunc_ln17_116_fu_4016_p4 = {{mul_ln864_85_fu_233_p2[14:5]}};

assign trunc_ln17_117_fu_4048_p4 = {{add_ln864_46_fu_4042_p2[14:5]}};

assign trunc_ln17_118_fu_4076_p4 = {{add_ln864_47_fu_4070_p2[14:5]}};

assign trunc_ln17_119_fu_4252_p4 = {{mul_ln864_86_fu_222_p2[14:5]}};

assign trunc_ln864_217_fu_3581_p4 = {{sub_ln864_fu_3575_p2[14:5]}};

assign trunc_ln864_218_fu_3599_p4 = {{r_V_183_fu_226_p2[14:5]}};

assign trunc_ln864_219_fu_3668_p4 = {{r_V_184_fu_3662_p2[14:5]}};

assign trunc_ln864_221_fu_3747_p4 = {{r_V_186_fu_244_p2[15:5]}};

assign trunc_ln864_223_fu_3874_p4 = {{r_V_188_fu_3868_p2[15:5]}};

assign trunc_ln864_224_fu_3926_p4 = {{r_V_189_fu_3920_p2[14:5]}};

assign trunc_ln864_225_fu_3940_p4 = {{r_V_190_fu_220_p2[14:5]}};

assign trunc_ln864_229_fu_4146_p4 = {{sub_ln864_44_fu_4140_p2[14:5]}};

assign trunc_ln864_230_fu_4164_p4 = {{r_V_194_fu_230_p2[14:5]}};

assign trunc_ln864_234_fu_4310_p4 = {{sub_ln864_46_fu_4304_p2[14:5]}};

assign trunc_ln864_235_fu_4328_p4 = {{r_V_197_fu_224_p2[14:5]}};

assign trunc_ln864_s_fu_3485_p4 = {{r_V_182_fu_3479_p2[14:5]}};

assign trunc_ln_fu_3431_p4 = {{r_V_fu_247_p2[15:5]}};

assign zext_ln1319_175_fu_3453_p1 = shl_ln_fu_3445_p3;

assign zext_ln1319_176_fu_3475_p1 = shl_ln1319_s_fu_3467_p3;

assign zext_ln1319_177_fu_3636_p1 = shl_ln1319_79_fu_3628_p3;

assign zext_ln1319_178_fu_3658_p1 = shl_ln1319_80_fu_3650_p3;

assign zext_ln1319_179_fu_3682_p1 = p_read3;

assign zext_ln1319_183_fu_3852_p1 = shl_ln1319_81_fu_3844_p3;

assign zext_ln1319_184_fu_3864_p1 = shl_ln1319_82_fu_3856_p3;

assign zext_ln1319_185_fu_3902_p1 = p_read7;

assign zext_ln1319_186_fu_3916_p1 = tmp_fu_3908_p3;

assign zext_ln1319_187_fu_4100_p1 = p_read11;

assign zext_ln1319_189_fu_4201_p1 = shl_ln1319_83_fu_4193_p3;

assign zext_ln1319_190_fu_4213_p1 = shl_ln1319_84_fu_4205_p3;

assign zext_ln17_162_fu_4452_p1 = trunc_ln17_s_reg_4833;

assign zext_ln17_163_fu_3595_p1 = $unsigned(sext_ln17_fu_3591_p1);

assign zext_ln17_164_fu_4455_p1 = trunc_ln17_107_reg_4838;

assign zext_ln17_165_fu_3710_p1 = trunc_ln17_108_fu_3700_p4;

assign zext_ln17_166_fu_3724_p1 = trunc_ln17_109_fu_3714_p4;

assign zext_ln17_167_fu_3738_p1 = trunc_ln17_110_fu_3728_p4;

assign zext_ln17_168_fu_3776_p1 = trunc_ln17_111_fu_3766_p4;

assign zext_ln17_169_fu_3820_p1 = trunc_ln17_112_fu_3810_p4;

assign zext_ln17_170_fu_3898_p1 = trunc_ln17_113_fu_3888_p4;

assign zext_ln17_171_fu_3984_p1 = trunc_ln17_115_fu_3974_p4;

assign zext_ln17_172_fu_4026_p1 = trunc_ln17_116_fu_4016_p4;

assign zext_ln17_173_fu_4086_p1 = trunc_ln17_118_fu_4076_p4;

assign zext_ln17_174_fu_4160_p1 = $unsigned(sext_ln17_43_fu_4156_p1);

assign zext_ln17_175_fu_4262_p1 = trunc_ln17_119_fu_4252_p4;

assign zext_ln17_176_fu_4324_p1 = $unsigned(sext_ln17_44_fu_4320_p1);

assign zext_ln17_fu_4449_p1 = trunc_ln4_reg_4828;

assign zext_ln70_10_fu_4467_p1 = trunc_ln17_114_reg_4854;

assign zext_ln70_8_fu_4233_p1 = p_read13;

assign zext_ln859_100_fu_4507_p1 = add_ln859_404_fu_4501_p2;

assign zext_ln859_102_fu_4590_p1 = add_ln859_415_reg_4919;

assign zext_ln859_103_fu_4541_p1 = add_ln859_408_reg_4904;

assign zext_ln859_104_fu_4616_p1 = add_ln859_420_reg_4929;

assign zext_ln859_105_fu_4599_p1 = add_ln859_416_fu_4593_p2;

assign zext_ln859_106_fu_4665_p1 = add_ln859_426_reg_4934;

assign zext_ln859_107_fu_4421_p1 = add_ln859_430_fu_4415_p2;

assign zext_ln859_108_fu_4625_p1 = add_ln859_421_fu_4619_p2;

assign zext_ln859_109_fu_4698_p1 = add_ln859_431_reg_4939;

assign zext_ln859_110_fu_4734_p1 = add_ln859_436_reg_4949;

assign zext_ln859_fu_4498_p1 = add_ln859_reg_4899;

assign zext_ln864_162_fu_3511_p1 = shl_ln1319_s_fu_3467_p3;

assign zext_ln864_164_fu_3559_p1 = shl_ln864_s_fu_3551_p3;

assign zext_ln864_165_fu_3571_p1 = shl_ln864_83_fu_3563_p3;

assign zext_ln864_168_fu_3788_p1 = shl_ln864_84_fu_3780_p3;

assign zext_ln864_169_fu_3800_p1 = shl_ln864_85_fu_3792_p3;

assign zext_ln864_171_fu_3998_p1 = p_read9;

assign zext_ln864_172_fu_4012_p1 = shl_ln864_86_fu_4004_p3;

assign zext_ln864_173_fu_4038_p1 = shl_ln864_87_fu_4030_p3;

assign zext_ln864_174_fu_4066_p1 = shl_ln864_88_fu_4058_p3;

assign zext_ln864_175_fu_4124_p1 = shl_ln864_89_fu_4116_p3;

assign zext_ln864_176_fu_4136_p1 = shl_ln864_90_fu_4128_p3;

assign zext_ln864_177_fu_4248_p1 = shl_ln864_91_fu_4240_p3;

assign zext_ln864_178_fu_4488_p1 = $unsigned(sext_ln864_94_fu_4485_p1);

assign zext_ln864_179_fu_4300_p1 = shl_ln864_92_fu_4292_p3;

assign zext_ln864_180_fu_4492_p1 = trunc_ln17_120_reg_4889;

assign zext_ln864_fu_3507_p1 = shl_ln2_fu_3499_p3;

endmodule //tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config14_s
