// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] p_read;
input  [8:0] p_read1;
input  [8:0] p_read2;
input  [8:0] p_read3;
input  [8:0] p_read4;
input  [8:0] p_read5;
input  [8:0] p_read6;
input  [8:0] p_read7;
input  [8:0] p_read8;
input  [8:0] p_read9;
input  [8:0] p_read10;
input  [8:0] p_read11;
input  [8:0] p_read12;
input  [8:0] p_read13;
input  [8:0] p_read14;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
reg   [8:0] p_read_106_reg_11885;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] p_read10106_reg_11891;
reg   [8:0] p_read399_reg_11897;
reg   [9:0] trunc_ln_reg_11904;
reg   [10:0] trunc_ln5_reg_11909;
reg   [10:0] trunc_ln864_239_reg_11914;
reg   [10:0] trunc_ln864_244_reg_11919;
reg   [10:0] trunc_ln864_251_reg_11924;
reg   [9:0] trunc_ln864_257_reg_11929;
reg   [8:0] trunc_ln17_134_reg_11934;
wire   [13:0] zext_ln864_193_fu_10150_p1;
reg   [13:0] zext_ln864_193_reg_11939;
wire   [11:0] zext_ln17_195_fu_10199_p1;
reg   [11:0] zext_ln17_195_reg_11944;
reg  signed [9:0] trunc_ln864_261_reg_11949;
reg   [8:0] trunc_ln17_140_reg_11955;
reg   [9:0] trunc_ln864_272_reg_11960;
reg   [9:0] trunc_ln864_274_reg_11965;
reg   [10:0] trunc_ln864_275_reg_11970;
wire   [14:0] zext_ln1319_222_fu_10700_p1;
reg   [14:0] zext_ln1319_222_reg_11975;
reg   [9:0] trunc_ln864_278_reg_11980;
reg   [9:0] trunc_ln17_144_reg_11985;
reg   [9:0] trunc_ln17_145_reg_11990;
wire   [10:0] add_ln859_fu_10902_p2;
reg   [10:0] add_ln859_reg_11995;
wire   [10:0] add_ln859_443_fu_10908_p2;
reg   [10:0] add_ln859_443_reg_12000;
wire   [11:0] add_ln859_446_fu_10920_p2;
reg   [11:0] add_ln859_446_reg_12005;
wire   [12:0] add_ln859_451_fu_10936_p2;
reg   [12:0] add_ln859_451_reg_12010;
wire   [11:0] add_ln859_453_fu_10948_p2;
reg   [11:0] add_ln859_453_reg_12015;
wire   [11:0] add_ln859_456_fu_10960_p2;
reg   [11:0] add_ln859_456_reg_12020;
wire   [11:0] add_ln859_458_fu_10976_p2;
reg   [11:0] add_ln859_458_reg_12025;
wire   [9:0] add_ln859_461_fu_10982_p2;
reg   [9:0] add_ln859_461_reg_12030;
wire   [11:0] add_ln859_463_fu_10988_p2;
reg   [11:0] add_ln859_463_reg_12035;
wire   [10:0] add_ln859_467_fu_10994_p2;
reg   [10:0] add_ln859_467_reg_12040;
wire   [11:0] add_ln859_468_fu_11000_p2;
reg   [11:0] add_ln859_468_reg_12045;
wire   [11:0] add_ln859_470_fu_11006_p2;
reg   [11:0] add_ln859_470_reg_12050;
wire   [9:0] add_ln859_474_fu_11012_p2;
reg   [9:0] add_ln859_474_reg_12055;
wire   [10:0] add_ln859_477_fu_11018_p2;
reg   [10:0] add_ln859_477_reg_12060;
wire   [10:0] add_ln859_481_fu_11024_p2;
reg   [10:0] add_ln859_481_reg_12065;
wire   [10:0] add_ln859_483_fu_11030_p2;
reg   [10:0] add_ln859_483_reg_12070;
wire   [10:0] add_ln859_487_fu_11036_p2;
reg   [10:0] add_ln859_487_reg_12075;
wire   [9:0] add_ln859_488_fu_11042_p2;
reg   [9:0] add_ln859_488_reg_12080;
wire   [11:0] add_ln859_490_fu_11048_p2;
reg   [11:0] add_ln859_490_reg_12085;
wire   [10:0] add_ln859_495_fu_11060_p2;
reg   [10:0] add_ln859_495_reg_12090;
wire   [10:0] add_ln859_496_fu_11066_p2;
reg   [10:0] add_ln859_496_reg_12095;
wire   [9:0] add_ln859_499_fu_11072_p2;
reg   [9:0] add_ln859_499_reg_12100;
wire   [11:0] add_ln859_502_fu_11084_p2;
reg   [11:0] add_ln859_502_reg_12105;
wire   [9:0] add_ln859_507_fu_11090_p2;
reg   [9:0] add_ln859_507_reg_12110;
wire   [10:0] add_ln859_514_fu_11096_p2;
reg   [10:0] add_ln859_514_reg_12115;
wire   [10:0] add_ln859_516_fu_11102_p2;
reg   [10:0] add_ln859_516_reg_12120;
wire   [9:0] grp_fu_9184_p4;
reg   [9:0] trunc_ln864_280_reg_12125;
wire    ap_block_pp0_stage1_11001;
wire   [11:0] add_ln859_444_fu_11308_p2;
reg   [11:0] add_ln859_444_reg_12130;
wire   [13:0] add_ln859_449_fu_11337_p2;
reg   [13:0] add_ln859_449_reg_12135;
wire   [13:0] add_ln859_454_fu_11349_p2;
reg   [13:0] add_ln859_454_reg_12140;
wire   [13:0] add_ln859_459_fu_11361_p2;
reg   [13:0] add_ln859_459_reg_12145;
wire   [13:0] add_ln859_466_fu_11408_p2;
reg   [13:0] add_ln859_466_reg_12150;
wire   [13:0] add_ln859_473_fu_11453_p2;
reg   [13:0] add_ln859_473_reg_12155;
wire   [13:0] add_ln859_480_fu_11501_p2;
reg   [13:0] add_ln859_480_reg_12160;
wire   [13:0] add_ln859_486_fu_11543_p2;
reg   [13:0] add_ln859_486_reg_12165;
wire   [13:0] add_ln859_493_fu_11588_p2;
reg   [13:0] add_ln859_493_reg_12170;
wire   [12:0] add_ln859_498_fu_11610_p2;
reg   [12:0] add_ln859_498_reg_12175;
wire   [12:0] add_ln859_503_fu_11632_p2;
reg   [12:0] add_ln859_503_reg_12180;
wire   [11:0] add_ln859_506_fu_11653_p2;
reg   [11:0] add_ln859_506_reg_12185;
wire   [13:0] add_ln859_513_fu_11708_p2;
reg   [13:0] add_ln859_513_reg_12190;
wire   [12:0] add_ln859_515_fu_11717_p2;
reg   [12:0] add_ln859_515_reg_12195;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [8:0] r_V_211_fu_258_p0;
wire  signed [5:0] r_V_211_fu_258_p1;
wire    ap_block_pp0_stage0;
wire   [8:0] r_V_215_fu_259_p0;
wire   [14:0] zext_ln1319_207_fu_10005_p1;
wire  signed [5:0] r_V_215_fu_259_p1;
wire   [8:0] r_V_203_fu_260_p0;
wire   [14:0] zext_ln1319_191_fu_9367_p1;
wire  signed [5:0] r_V_203_fu_260_p1;
wire   [8:0] r_V_220_fu_261_p0;
wire   [14:0] zext_ln1319_211_fu_10203_p1;
wire  signed [5:0] r_V_220_fu_261_p1;
wire   [8:0] r_V_208_fu_262_p0;
wire   [14:0] zext_ln1319_196_fu_9651_p1;
wire  signed [5:0] r_V_208_fu_262_p1;
wire   [8:0] r_V_223_fu_263_p0;
wire   [14:0] zext_ln1319_212_fu_10271_p1;
wire  signed [5:0] r_V_223_fu_263_p1;
wire   [8:0] mul_ln864_103_fu_264_p0;
wire   [13:0] zext_ln864_204_fu_10505_p1;
wire   [5:0] mul_ln864_103_fu_264_p1;
wire   [8:0] r_V_217_fu_265_p0;
wire  signed [5:0] r_V_217_fu_265_p1;
wire   [8:0] r_V_201_fu_266_p0;
wire  signed [5:0] r_V_201_fu_266_p1;
wire   [8:0] r_V_218_fu_267_p0;
wire  signed [5:0] r_V_218_fu_267_p1;
wire   [8:0] r_V_205_fu_268_p0;
wire   [15:0] zext_ln1319_194_fu_9563_p1;
wire  signed [6:0] r_V_205_fu_268_p1;
wire   [8:0] r_V_207_fu_269_p0;
wire  signed [5:0] r_V_207_fu_269_p1;
wire   [8:0] r_V_226_fu_270_p0;
wire   [15:0] zext_ln1319_214_fu_10471_p1;
wire  signed [6:0] r_V_226_fu_270_p1;
wire   [8:0] mul_ln864_95_fu_271_p0;
wire   [13:0] zext_ln864_191_fu_9704_p1;
wire   [5:0] mul_ln864_95_fu_271_p1;
wire   [8:0] r_V_229_fu_272_p0;
wire  signed [5:0] r_V_229_fu_272_p1;
wire   [8:0] mul_ln864_99_fu_273_p0;
wire   [13:0] zext_ln1319_205_fu_9995_p1;
wire   [5:0] mul_ln864_99_fu_273_p1;
wire   [8:0] mul_ln864_100_fu_274_p0;
wire   [5:0] mul_ln864_100_fu_274_p1;
wire   [8:0] mul_ln864_105_fu_275_p0;
wire   [13:0] zext_ln70_fu_10595_p1;
wire   [5:0] mul_ln864_105_fu_275_p1;
wire   [8:0] r_V_224_fu_276_p0;
wire  signed [5:0] r_V_224_fu_276_p1;
wire   [8:0] mul_ln864_96_fu_277_p0;
wire   [5:0] mul_ln864_96_fu_277_p1;
wire   [8:0] mul_ln864_89_fu_278_p0;
wire   [14:0] zext_ln864_180_fu_9210_p1;
wire   [6:0] mul_ln864_89_fu_278_p1;
wire   [8:0] mul_ln864_107_fu_279_p0;
wire   [13:0] zext_ln1319_221_fu_10694_p1;
wire   [5:0] mul_ln864_107_fu_279_p1;
wire   [8:0] r_V_202_fu_280_p0;
wire  signed [6:0] r_V_202_fu_280_p1;
wire   [8:0] r_V_234_fu_281_p0;
wire  signed [5:0] r_V_234_fu_281_p1;
reg   [8:0] grp_fu_282_p0;
wire   [13:0] zext_ln864_196_fu_10262_p1;
wire   [5:0] grp_fu_282_p1;
wire    ap_block_pp0_stage1;
wire   [8:0] mul_ln864_104_fu_283_p0;
wire   [5:0] mul_ln864_104_fu_283_p1;
wire   [8:0] r_V_fu_284_p0;
wire   [15:0] zext_ln864_fu_9204_p1;
wire  signed [6:0] r_V_fu_284_p1;
wire   [8:0] r_V_199_fu_285_p0;
wire  signed [5:0] r_V_199_fu_285_p1;
wire   [8:0] mul_ln864_106_fu_286_p0;
wire   [5:0] mul_ln864_106_fu_286_p1;
wire   [8:0] mul_ln864_92_fu_287_p0;
wire   [4:0] mul_ln864_92_fu_287_p1;
wire   [8:0] mul_ln864_90_fu_288_p0;
wire   [6:0] mul_ln864_90_fu_288_p1;
wire   [8:0] r_V_233_fu_289_p0;
wire  signed [5:0] r_V_233_fu_289_p1;
wire   [8:0] r_V_227_fu_290_p0;
wire  signed [6:0] r_V_227_fu_290_p1;
wire   [8:0] mul_ln864_88_fu_291_p0;
wire   [7:0] mul_ln864_88_fu_291_p1;
wire   [8:0] r_V_221_fu_292_p0;
wire  signed [5:0] r_V_221_fu_292_p1;
wire   [8:0] mul_ln864_98_fu_293_p0;
wire   [5:0] mul_ln864_98_fu_293_p1;
wire   [8:0] mul_ln864_108_fu_294_p0;
wire   [5:0] mul_ln864_108_fu_294_p1;
wire   [8:0] r_V_222_fu_295_p0;
wire  signed [5:0] r_V_222_fu_295_p1;
reg   [8:0] grp_fu_296_p0;
wire  signed [5:0] grp_fu_296_p1;
wire   [8:0] mul_ln864_94_fu_297_p0;
wire   [5:0] mul_ln864_94_fu_297_p1;
wire   [8:0] mul_ln864_97_fu_298_p0;
wire   [5:0] mul_ln864_97_fu_298_p1;
wire   [8:0] mul_ln864_91_fu_299_p0;
wire   [6:0] mul_ln864_91_fu_299_p1;
wire   [8:0] r_V_231_fu_300_p0;
wire  signed [5:0] r_V_231_fu_300_p1;
wire   [8:0] mul_ln864_93_fu_301_p0;
wire   [5:0] mul_ln864_93_fu_301_p1;
wire   [8:0] mul_ln864_109_fu_302_p0;
wire   [6:0] mul_ln864_109_fu_302_p1;
wire   [8:0] mul_ln864_fu_303_p0;
wire   [6:0] mul_ln864_fu_303_p1;
wire   [14:0] grp_fu_296_p2;
wire   [13:0] grp_fu_282_p2;
wire   [14:0] mul_ln864_fu_303_p2;
wire   [14:0] shl_ln_fu_9228_p3;
wire   [15:0] zext_ln864_181_fu_9236_p1;
wire   [15:0] add_ln864_fu_9240_p2;
wire   [15:0] r_V_fu_284_p2;
wire   [15:0] mul_ln864_88_fu_291_p2;
wire   [14:0] mul_ln864_89_fu_278_p2;
wire   [9:0] trunc_ln17_122_fu_9276_p4;
wire   [12:0] shl_ln864_s_fu_9290_p3;
wire   [9:0] shl_ln864_93_fu_9302_p3;
wire   [13:0] zext_ln864_182_fu_9298_p1;
wire   [13:0] zext_ln864_183_fu_9310_p1;
wire   [13:0] add_ln864_48_fu_9314_p2;
wire   [8:0] trunc_ln17_123_fu_9320_p4;
wire   [14:0] mul_ln864_90_fu_288_p2;
wire   [9:0] trunc_ln17_124_fu_9334_p4;
wire   [14:0] r_V_199_fu_285_p2;
wire   [9:0] trunc_ln864_s_fu_9348_p4;
wire   [14:0] shl_ln3_fu_9374_p3;
wire   [10:0] shl_ln1319_s_fu_9386_p3;
wire   [15:0] zext_ln1319_193_fu_9394_p1;
wire   [15:0] zext_ln1319_192_fu_9382_p1;
wire   [15:0] r_V_200_fu_9398_p2;
wire   [10:0] trunc_ln864_237_fu_9404_p4;
wire   [13:0] shl_ln864_94_fu_9418_p3;
wire   [9:0] shl_ln864_95_fu_9430_p3;
wire   [14:0] zext_ln864_184_fu_9426_p1;
wire   [14:0] zext_ln864_185_fu_9438_p1;
wire   [14:0] add_ln864_49_fu_9442_p2;
wire   [14:0] r_V_201_fu_266_p2;
wire   [9:0] trunc_ln864_238_fu_9458_p4;
wire   [14:0] mul_ln864_91_fu_299_p2;
wire   [9:0] trunc_ln17_126_fu_9472_p4;
wire   [15:0] r_V_202_fu_280_p2;
wire   [14:0] r_V_203_fu_260_p2;
wire   [9:0] trunc_ln864_240_fu_9496_p4;
wire   [13:0] shl_ln864_96_fu_9515_p3;
wire   [11:0] shl_ln864_97_fu_9527_p3;
wire   [14:0] zext_ln864_187_fu_9523_p1;
wire   [14:0] zext_ln864_188_fu_9535_p1;
wire   [14:0] sub_ln864_fu_9539_p2;
wire   [9:0] trunc_ln864_241_fu_9545_p4;
wire  signed [10:0] sext_ln17_fu_9555_p1;
wire   [14:0] sub_ln1319_fu_9568_p2;
wire  signed [15:0] sext_ln1319_fu_9574_p1;
wire   [15:0] zext_ln1319_195_fu_9578_p1;
wire   [15:0] r_V_204_fu_9582_p2;
wire   [10:0] trunc_ln864_242_fu_9588_p4;
wire   [12:0] mul_ln864_92_fu_287_p2;
wire   [7:0] trunc_ln17_127_fu_9602_p4;
wire   [15:0] r_V_205_fu_268_p2;
wire   [10:0] trunc_ln864_243_fu_9616_p4;
wire   [15:0] r_V_206_fu_9630_p2;
wire   [14:0] r_V_207_fu_269_p2;
wire   [9:0] trunc_ln864_245_fu_9658_p4;
wire   [14:0] r_V_208_fu_262_p2;
wire   [9:0] trunc_ln864_246_fu_9672_p4;
wire   [13:0] mul_ln864_93_fu_301_p2;
wire   [8:0] trunc_ln17_128_fu_9686_p4;
wire   [13:0] mul_ln864_94_fu_297_p2;
wire   [8:0] mult_V_fu_9712_p4;
wire   [13:0] shl_ln1319_85_fu_9739_p3;
wire   [11:0] shl_ln1319_86_fu_9751_p3;
wire   [14:0] zext_ln1319_200_fu_9759_p1;
wire   [14:0] zext_ln1319_199_fu_9747_p1;
wire   [14:0] r_V_210_fu_9763_p2;
wire   [9:0] trunc_ln864_249_fu_9769_p4;
wire   [14:0] r_V_211_fu_258_p2;
wire   [9:0] trunc_ln864_250_fu_9783_p4;
wire   [13:0] mul_ln864_95_fu_271_p2;
wire   [8:0] trunc_ln17_129_fu_9797_p4;
wire   [13:0] mul_ln864_96_fu_277_p2;
wire   [8:0] trunc_ln17_130_fu_9811_p4;
wire   [14:0] sub_ln1319_115_fu_9825_p2;
wire  signed [15:0] sext_ln1319_28_fu_9831_p1;
wire   [15:0] zext_ln1319_197_fu_9730_p1;
wire   [15:0] r_V_212_fu_9835_p2;
wire   [13:0] mul_ln864_97_fu_298_p2;
wire   [8:0] trunc_ln17_131_fu_9851_p4;
wire   [12:0] shl_ln1319_87_fu_9865_p3;
wire   [13:0] zext_ln1319_201_fu_9873_p1;
wire   [13:0] sub_ln1319_117_fu_9877_p2;
wire   [9:0] shl_ln1319_88_fu_9887_p3;
wire  signed [14:0] sext_ln1319_29_fu_9883_p1;
wire   [14:0] zext_ln1319_202_fu_9895_p1;
wire   [14:0] r_V_213_fu_9899_p2;
wire   [9:0] trunc_ln864_252_fu_9905_p4;
wire   [10:0] shl_ln864_100_fu_9919_p3;
wire   [13:0] zext_ln864_192_fu_9927_p1;
wire   [13:0] add_ln864_50_fu_9931_p2;
wire   [8:0] trunc_ln17_132_fu_9937_p4;
wire   [13:0] shl_ln1319_89_fu_9951_p3;
wire   [11:0] shl_ln1319_90_fu_9963_p3;
wire   [14:0] zext_ln1319_204_fu_9971_p1;
wire   [14:0] zext_ln1319_203_fu_9959_p1;
wire   [14:0] r_V_214_fu_9975_p2;
wire   [9:0] trunc_ln864_253_fu_9981_p4;
wire   [14:0] r_V_215_fu_259_p2;
wire   [9:0] trunc_ln864_254_fu_10012_p4;
wire   [14:0] tmp_fu_10026_p3;
wire   [15:0] zext_ln1319_206_fu_10001_p1;
wire   [15:0] zext_ln1319_208_fu_10034_p1;
wire   [15:0] r_V_216_fu_10038_p2;
wire   [10:0] trunc_ln864_255_fu_10044_p4;
wire   [14:0] r_V_217_fu_265_p2;
wire   [9:0] trunc_ln864_256_fu_10058_p4;
wire   [13:0] mul_ln864_98_fu_293_p2;
wire   [8:0] trunc_ln17_133_fu_10072_p4;
wire   [14:0] r_V_218_fu_267_p2;
wire   [13:0] shl_ln1319_91_fu_10096_p3;
wire   [10:0] shl_ln1319_92_fu_10108_p3;
wire   [14:0] zext_ln1319_210_fu_10116_p1;
wire   [14:0] zext_ln1319_209_fu_10104_p1;
wire   [14:0] r_V_219_fu_10120_p2;
wire   [9:0] trunc_ln864_258_fu_10126_p4;
wire   [13:0] mul_ln864_99_fu_273_p2;
wire   [13:0] shl_ln864_101_fu_10155_p3;
wire   [11:0] shl_ln864_102_fu_10167_p3;
wire   [14:0] zext_ln864_194_fu_10163_p1;
wire   [14:0] zext_ln864_195_fu_10175_p1;
wire   [14:0] sub_ln864_48_fu_10179_p2;
wire   [9:0] trunc_ln864_259_fu_10185_p4;
wire  signed [10:0] sext_ln17_46_fu_10195_p1;
wire   [14:0] r_V_220_fu_261_p2;
wire   [9:0] trunc_ln864_260_fu_10210_p4;
wire   [14:0] r_V_221_fu_292_p2;
wire   [14:0] r_V_222_fu_295_p2;
wire   [9:0] trunc_ln864_262_fu_10234_p4;
wire   [13:0] mul_ln864_100_fu_274_p2;
wire   [8:0] trunc_ln17_135_fu_10248_p4;
wire   [8:0] grp_fu_9194_p4;
wire   [14:0] r_V_223_fu_263_p2;
wire   [9:0] trunc_ln864_263_fu_10277_p4;
wire   [14:0] r_V_224_fu_276_p2;
wire   [9:0] trunc_ln864_264_fu_10291_p4;
wire   [13:0] shl_ln864_103_fu_10305_p3;
wire   [9:0] shl_ln864_104_fu_10317_p3;
wire   [14:0] zext_ln864_197_fu_10313_p1;
wire   [14:0] zext_ln864_198_fu_10325_p1;
wire   [14:0] sub_ln864_49_fu_10329_p2;
wire   [9:0] trunc_ln864_265_fu_10335_p4;
wire  signed [10:0] sext_ln17_47_fu_10345_p1;
wire   [13:0] shl_ln864_105_fu_10353_p3;
wire   [11:0] shl_ln864_106_fu_10365_p3;
wire   [14:0] zext_ln864_199_fu_10361_p1;
wire   [14:0] zext_ln864_200_fu_10373_p1;
wire   [14:0] sub_ln864_50_fu_10377_p2;
wire   [9:0] trunc_ln864_266_fu_10383_p4;
wire  signed [10:0] sext_ln17_48_fu_10393_p1;
wire   [9:0] shl_ln864_107_fu_10401_p3;
wire   [14:0] zext_ln864_201_fu_10409_p1;
wire   [14:0] add_ln864_51_fu_10413_p2;
wire   [12:0] shl_ln1319_93_fu_10429_p3;
wire   [13:0] zext_ln1319_213_fu_10437_p1;
wire   [13:0] sub_ln1319_121_fu_10441_p2;
wire  signed [14:0] sext_ln1319_30_fu_10447_p1;
wire   [14:0] r_V_225_fu_10451_p2;
wire   [9:0] trunc_ln864_267_fu_10457_p4;
wire   [15:0] r_V_226_fu_270_p2;
wire   [10:0] trunc_ln864_268_fu_10477_p4;
wire   [15:0] r_V_227_fu_290_p2;
wire   [10:0] trunc_ln864_270_fu_10491_p4;
wire   [13:0] mul_ln864_103_fu_264_p2;
wire   [8:0] trunc_ln17_139_fu_10511_p4;
wire   [13:0] mul_ln864_104_fu_283_p2;
wire   [13:0] shl_ln1319_94_fu_10535_p3;
wire   [11:0] shl_ln1319_95_fu_10547_p3;
wire   [14:0] zext_ln1319_217_fu_10555_p1;
wire   [14:0] zext_ln1319_216_fu_10543_p1;
wire   [14:0] r_V_228_fu_10559_p2;
wire   [9:0] trunc_ln864_271_fu_10565_p4;
wire   [14:0] sub_ln864_52_fu_10579_p2;
wire   [13:0] mul_ln864_105_fu_275_p2;
wire   [8:0] trunc_ln17_141_fu_10601_p4;
wire   [13:0] mul_ln864_106_fu_286_p2;
wire   [8:0] trunc_ln17_142_fu_10615_p4;
wire   [14:0] r_V_229_fu_272_p2;
wire   [13:0] shl_ln1319_96_fu_10644_p3;
wire   [14:0] zext_ln1319_219_fu_10652_p1;
wire   [14:0] sub_ln1319_125_fu_10656_p2;
wire   [10:0] shl_ln1319_97_fu_10666_p3;
wire  signed [15:0] sext_ln1319_31_fu_10662_p1;
wire   [15:0] zext_ln1319_220_fu_10674_p1;
wire   [15:0] r_V_230_fu_10678_p2;
wire   [14:0] r_V_231_fu_300_p2;
wire   [9:0] trunc_ln864_276_fu_10708_p4;
wire   [12:0] shl_ln864_112_fu_10722_p3;
wire   [10:0] shl_ln864_113_fu_10734_p3;
wire   [13:0] zext_ln864_208_fu_10730_p1;
wire   [13:0] zext_ln864_209_fu_10742_p1;
wire   [13:0] add_ln864_52_fu_10746_p2;
wire   [8:0] mult_V_29_fu_10752_p4;
wire   [11:0] shl_ln1319_98_fu_10766_p3;
wire   [12:0] zext_ln1319_223_fu_10774_p1;
wire   [12:0] sub_ln1319_127_fu_10778_p2;
wire  signed [13:0] sext_ln1319_32_fu_10784_p1;
wire   [13:0] r_V_232_fu_10788_p2;
wire   [8:0] trunc_ln864_277_fu_10794_p4;
wire   [13:0] mul_ln864_107_fu_279_p2;
wire   [8:0] mult_V_30_fu_10808_p4;
wire   [14:0] r_V_233_fu_289_p2;
wire   [14:0] r_V_234_fu_281_p2;
wire   [9:0] trunc_ln864_279_fu_10832_p4;
wire   [13:0] mul_ln864_108_fu_294_p2;
wire   [8:0] trunc_ln17_143_fu_10846_p4;
wire   [13:0] shl_ln864_114_fu_10860_p3;
wire   [14:0] zext_ln864_210_fu_10868_p1;
wire   [14:0] zext_ln864_211_fu_10872_p1;
wire   [14:0] add_ln864_53_fu_10876_p2;
wire   [14:0] mul_ln864_109_fu_302_p2;
wire   [10:0] zext_ln17_187_fu_9722_p1;
wire  signed [10:0] sext_ln1319_84_fu_9668_p1;
wire  signed [10:0] sext_ln1319_86_fu_10022_p1;
wire  signed [10:0] sext_ln1319_89_fu_10220_p1;
wire   [11:0] zext_ln17_180_fu_9482_p1;
wire   [11:0] zext_ln17_199_fu_10349_p1;
wire   [11:0] add_ln859_445_fu_10914_p2;
wire   [11:0] zext_ln17_179_fu_9344_p1;
wire   [11:0] zext_ln17_181_fu_9559_p1;
wire   [11:0] zext_ln17_200_fu_10397_p1;
wire   [11:0] add_ln859_450_fu_10926_p2;
wire   [12:0] zext_ln859_110_fu_10932_p1;
wire   [12:0] zext_ln17_188_fu_9726_p1;
wire  signed [11:0] sext_ln1319_87_fu_10054_p1;
wire  signed [11:0] sext_ln1319_92_fu_10287_p1;
wire   [11:0] add_ln859_452_fu_10942_p2;
wire  signed [11:0] sext_ln864_101_fu_9915_p1;
wire   [11:0] zext_ln17_190_fu_9821_p1;
wire   [11:0] add_ln859_455_fu_10954_p2;
wire   [11:0] zext_ln17_178_fu_9330_p1;
wire  signed [10:0] sext_ln864_107_fu_10575_p1;
wire   [10:0] add_ln859_457_fu_10966_p2;
wire  signed [11:0] sext_ln859_252_fu_10972_p1;
wire  signed [11:0] sext_ln864_103_fu_10136_p1;
wire   [9:0] zext_ln17_198_fu_10267_p1;
wire   [9:0] zext_ln17_203_fu_10611_p1;
wire  signed [11:0] sext_ln864_106_fu_10487_p1;
wire  signed [11:0] sext_ln864_109_fu_10718_p1;
wire   [10:0] trunc_ln17_s_fu_9246_p4;
wire   [10:0] zext_ln17_201_fu_10521_p1;
wire   [11:0] zext_ln17_205_fu_10762_p1;
wire  signed [11:0] sext_ln864_95_fu_9414_p1;
wire  signed [11:0] sext_ln864_97_fu_9598_p1;
wire  signed [11:0] sext_ln1319_85_fu_9779_p1;
wire   [9:0] trunc_ln17_125_fu_9448_p4;
wire   [9:0] zext_ln17_182_fu_9612_p1;
wire  signed [10:0] sext_ln864_102_fu_10068_p1;
wire  signed [10:0] sext_ln864_110_fu_10804_p1;
wire   [10:0] zext_ln17_206_fu_10818_p1;
wire  signed [10:0] sext_ln864_98_fu_9682_p1;
wire  signed [10:0] sext_ln864_104_fu_10244_p1;
wire  signed [10:0] sext_ln864_105_fu_10301_p1;
wire   [10:0] trunc_ln17_121_fu_9266_p4;
wire   [10:0] zext_ln17_192_fu_9947_p1;
wire   [9:0] zext_ln17_193_fu_10082_p1;
wire   [9:0] trunc_ln17_138_fu_10419_p4;
wire  signed [11:0] sext_ln1319_83_fu_9626_p1;
wire  signed [11:0] sext_ln864_99_fu_9793_p1;
wire   [10:0] zext_ln17_177_fu_9286_p1;
wire   [10:0] zext_ln17_196_fu_10258_p1;
wire   [10:0] add_ln859_494_fu_11054_p2;
wire   [10:0] zext_ln17_189_fu_9807_p1;
wire  signed [10:0] sext_ln70_34_fu_10467_p1;
wire  signed [10:0] sext_ln864_111_fu_10842_p1;
wire   [9:0] zext_ln17_204_fu_10625_p1;
wire   [9:0] zext_ln17_207_fu_10856_p1;
wire  signed [11:0] sext_ln70_35_fu_10501_p1;
wire   [11:0] add_ln859_501_fu_11078_p2;
wire  signed [11:0] sext_ln864_96_fu_9468_p1;
wire   [9:0] zext_ln17_186_fu_9696_p1;
wire   [9:0] zext_ln17_191_fu_9861_p1;
wire  signed [10:0] sext_ln70_fu_9358_p1;
wire  signed [10:0] sext_ln70_30_fu_9506_p1;
wire  signed [10:0] sext_ln70_32_fu_9700_p1;
wire  signed [10:0] sext_ln70_33_fu_9991_p1;
wire   [13:0] shl_ln864_98_fu_11123_p3;
wire   [9:0] shl_ln864_99_fu_11134_p3;
wire   [14:0] zext_ln864_189_fu_11130_p1;
wire   [14:0] zext_ln864_190_fu_11141_p1;
wire   [14:0] sub_ln864_47_fu_11145_p2;
wire   [9:0] trunc_ln864_247_fu_11151_p4;
wire  signed [10:0] sext_ln17_45_fu_11161_p1;
wire   [13:0] shl_ln864_108_fu_11188_p3;
wire   [10:0] shl_ln864_109_fu_11199_p3;
wire   [14:0] zext_ln864_202_fu_11195_p1;
wire   [14:0] zext_ln864_203_fu_11206_p1;
wire   [14:0] sub_ln864_51_fu_11210_p2;
wire   [9:0] trunc_ln864_269_fu_11216_p4;
wire  signed [10:0] sext_ln1319_93_fu_11226_p1;
wire  signed [10:0] sext_ln70_36_fu_11237_p1;
wire   [13:0] shl_ln864_110_fu_11244_p3;
wire   [11:0] shl_ln864_111_fu_11255_p3;
wire   [14:0] zext_ln864_205_fu_11251_p1;
wire   [14:0] zext_ln864_206_fu_11262_p1;
wire   [14:0] sub_ln864_53_fu_11266_p2;
wire   [9:0] trunc_ln864_273_fu_11272_p4;
wire  signed [10:0] sext_ln864_108_fu_11282_p1;
wire  signed [11:0] sext_ln859_247_fu_11305_p1;
wire  signed [11:0] sext_ln859_246_fu_11302_p1;
wire  signed [11:0] sext_ln864_100_fu_11169_p1;
wire   [11:0] add_ln859_447_fu_11317_p2;
wire  signed [12:0] sext_ln859_248_fu_11323_p1;
wire  signed [12:0] sext_ln70_31_fu_11117_p1;
wire   [12:0] add_ln859_448_fu_11327_p2;
wire  signed [13:0] sext_ln859_249_fu_11333_p1;
wire   [13:0] zext_ln859_fu_11314_p1;
wire  signed [13:0] sext_ln859_250_fu_11346_p1;
wire   [13:0] zext_ln859_111_fu_11343_p1;
wire  signed [13:0] sext_ln859_253_fu_11358_p1;
wire   [13:0] zext_ln859_112_fu_11355_p1;
wire   [11:0] zext_ln17_fu_11108_p1;
wire   [11:0] zext_ln859_113_fu_11372_p1;
wire   [11:0] add_ln859_460_fu_11367_p2;
wire   [11:0] add_ln859_462_fu_11375_p2;
wire   [9:0] zext_ln17_183_fu_11120_p1;
wire   [9:0] add_ln859_464_fu_11388_p2;
wire   [12:0] zext_ln859_115_fu_11394_p1;
wire  signed [12:0] sext_ln859_254_fu_11385_p1;
wire   [12:0] add_ln859_465_fu_11398_p2;
wire  signed [13:0] sext_ln859_255_fu_11404_p1;
wire   [13:0] zext_ln859_114_fu_11381_p1;
wire  signed [12:0] sext_ln859_256_fu_11417_p1;
wire   [12:0] zext_ln859_116_fu_11414_p1;
wire   [12:0] add_ln859_469_fu_11420_p2;
wire  signed [10:0] sext_ln1319_91_fu_11181_p1;
wire   [10:0] add_ln859_471_fu_11433_p2;
wire  signed [12:0] sext_ln859_259_fu_11439_p1;
wire  signed [12:0] sext_ln859_258_fu_11430_p1;
wire   [12:0] add_ln859_472_fu_11443_p2;
wire  signed [13:0] sext_ln859_260_fu_11449_p1;
wire  signed [13:0] sext_ln859_257_fu_11426_p1;
wire   [12:0] zext_ln1319_215_fu_11230_p1;
wire  signed [12:0] sext_ln864_fu_11111_p1;
wire   [12:0] add_ln859_475_fu_11462_p2;
wire   [12:0] zext_ln859_117_fu_11459_p1;
wire   [12:0] add_ln859_476_fu_11468_p2;
wire   [9:0] add_ln859_478_fu_11481_p2;
wire   [11:0] zext_ln859_118_fu_11487_p1;
wire  signed [11:0] sext_ln859_262_fu_11478_p1;
wire   [11:0] add_ln859_479_fu_11491_p2;
wire  signed [13:0] sext_ln859_263_fu_11497_p1;
wire  signed [13:0] sext_ln859_261_fu_11474_p1;
wire  signed [12:0] sext_ln859_264_fu_11507_p1;
wire   [12:0] zext_ln864_207_fu_11286_p1;
wire   [12:0] add_ln859_482_fu_11510_p2;
wire  signed [10:0] sext_ln1319_94_fu_11290_p1;
wire   [10:0] add_ln859_484_fu_11523_p2;
wire  signed [11:0] sext_ln859_267_fu_11529_p1;
wire  signed [11:0] sext_ln859_266_fu_11520_p1;
wire   [11:0] add_ln859_485_fu_11533_p2;
wire  signed [13:0] sext_ln859_268_fu_11539_p1;
wire  signed [13:0] sext_ln859_265_fu_11516_p1;
wire   [11:0] zext_ln859_120_fu_11552_p1;
wire   [11:0] zext_ln859_119_fu_11549_p1;
wire   [11:0] add_ln859_489_fu_11555_p2;
wire  signed [10:0] sext_ln1319_95_fu_11296_p1;
wire   [10:0] add_ln859_491_fu_11568_p2;
wire  signed [12:0] sext_ln859_270_fu_11574_p1;
wire  signed [12:0] sext_ln859_269_fu_11565_p1;
wire   [12:0] add_ln859_492_fu_11578_p2;
wire  signed [13:0] sext_ln859_271_fu_11584_p1;
wire   [13:0] zext_ln859_121_fu_11561_p1;
wire  signed [11:0] sext_ln859_272_fu_11597_p1;
wire  signed [11:0] sext_ln1319_88_fu_11172_p1;
wire   [11:0] add_ln859_497_fu_11600_p2;
wire  signed [12:0] sext_ln859_273_fu_11606_p1;
wire   [12:0] zext_ln859_122_fu_11594_p1;
wire   [10:0] zext_ln859_123_fu_11616_p1;
wire   [10:0] zext_ln17_202_fu_11234_p1;
wire   [10:0] add_ln859_500_fu_11619_p2;
wire  signed [12:0] sext_ln859_274_fu_11629_p1;
wire   [12:0] zext_ln859_124_fu_11625_p1;
wire   [11:0] zext_ln17_185_fu_11165_p1;
wire   [11:0] zext_ln17_197_fu_11184_p1;
wire   [9:0] add_ln859_505_fu_11644_p2;
wire   [11:0] zext_ln859_125_fu_11649_p1;
wire   [11:0] add_ln859_504_fu_11638_p2;
wire   [10:0] zext_ln17_194_fu_11175_p1;
wire   [10:0] zext_ln17_208_fu_11299_p1;
wire   [10:0] add_ln859_508_fu_11662_p2;
wire   [10:0] zext_ln859_127_fu_11659_p1;
wire   [10:0] add_ln859_509_fu_11668_p2;
wire  signed [11:0] sext_ln1319_82_fu_11114_p1;
wire  signed [11:0] sext_ln1319_90_fu_11178_p1;
wire   [11:0] add_ln859_510_fu_11678_p2;
wire  signed [11:0] sext_ln70_37_fu_11293_p1;
wire   [11:0] add_ln859_511_fu_11688_p2;
wire  signed [12:0] sext_ln859_276_fu_11694_p1;
wire  signed [12:0] sext_ln859_275_fu_11684_p1;
wire   [12:0] add_ln859_512_fu_11698_p2;
wire  signed [13:0] sext_ln859_277_fu_11704_p1;
wire   [13:0] zext_ln859_128_fu_11674_p1;
wire  signed [12:0] sext_ln859_278_fu_11714_p1;
wire   [12:0] zext_ln70_11_fu_11240_p1;
wire  signed [10:0] sext_ln859_245_fu_11723_p1;
wire   [10:0] add_ln859_517_fu_11771_p2;
wire  signed [11:0] sext_ln859_281_fu_11777_p1;
wire  signed [11:0] sext_ln859_280_fu_11768_p1;
wire   [11:0] add_ln859_518_fu_11781_p2;
wire  signed [13:0] sext_ln859_282_fu_11787_p1;
wire  signed [13:0] sext_ln859_279_fu_11765_p1;
wire   [13:0] add_ln859_519_fu_11791_p2;
wire  signed [15:0] sext_ln859_141_fu_11738_p1;
wire  signed [15:0] sext_ln859_fu_11726_p1;
wire  signed [15:0] sext_ln859_251_fu_11732_p1;
wire  signed [15:0] sext_ln859_142_fu_11741_p1;
wire  signed [15:0] sext_ln859_145_fu_11744_p1;
wire  signed [15:0] sext_ln859_146_fu_11747_p1;
wire  signed [15:0] sext_ln859_148_fu_11750_p1;
wire  signed [15:0] sext_ln859_150_fu_11753_p1;
wire  signed [15:0] sext_ln859_152_fu_11756_p1;
wire   [15:0] zext_ln859_126_fu_11759_p1;
wire  signed [15:0] sext_ln859_139_fu_11735_p1;
wire  signed [15:0] sext_ln859_135_fu_11729_p1;
wire  signed [15:0] sext_ln859_154_fu_11762_p1;
wire  signed [15:0] add_ln859_519_cast_fu_11797_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire   [13:0] mul_ln864_100_fu_274_p00;
wire   [12:0] mul_ln864_92_fu_287_p00;
wire   [13:0] mul_ln864_93_fu_301_p00;
wire   [15:0] r_V_202_fu_280_p00;
wire   [14:0] r_V_211_fu_258_p00;
wire   [14:0] r_V_229_fu_272_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U479(
    .din0(r_V_211_fu_258_p0),
    .din1(r_V_211_fu_258_p1),
    .dout(r_V_211_fu_258_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U480(
    .din0(r_V_215_fu_259_p0),
    .din1(r_V_215_fu_259_p1),
    .dout(r_V_215_fu_259_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U481(
    .din0(r_V_203_fu_260_p0),
    .din1(r_V_203_fu_260_p1),
    .dout(r_V_203_fu_260_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U482(
    .din0(r_V_220_fu_261_p0),
    .din1(r_V_220_fu_261_p1),
    .dout(r_V_220_fu_261_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U483(
    .din0(r_V_208_fu_262_p0),
    .din1(r_V_208_fu_262_p1),
    .dout(r_V_208_fu_262_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U484(
    .din0(r_V_223_fu_263_p0),
    .din1(r_V_223_fu_263_p1),
    .dout(r_V_223_fu_263_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U485(
    .din0(mul_ln864_103_fu_264_p0),
    .din1(mul_ln864_103_fu_264_p1),
    .dout(mul_ln864_103_fu_264_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U486(
    .din0(r_V_217_fu_265_p0),
    .din1(r_V_217_fu_265_p1),
    .dout(r_V_217_fu_265_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U487(
    .din0(r_V_201_fu_266_p0),
    .din1(r_V_201_fu_266_p1),
    .dout(r_V_201_fu_266_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U488(
    .din0(r_V_218_fu_267_p0),
    .din1(r_V_218_fu_267_p1),
    .dout(r_V_218_fu_267_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U489(
    .din0(r_V_205_fu_268_p0),
    .din1(r_V_205_fu_268_p1),
    .dout(r_V_205_fu_268_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U490(
    .din0(r_V_207_fu_269_p0),
    .din1(r_V_207_fu_269_p1),
    .dout(r_V_207_fu_269_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U491(
    .din0(r_V_226_fu_270_p0),
    .din1(r_V_226_fu_270_p1),
    .dout(r_V_226_fu_270_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U492(
    .din0(mul_ln864_95_fu_271_p0),
    .din1(mul_ln864_95_fu_271_p1),
    .dout(mul_ln864_95_fu_271_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U493(
    .din0(r_V_229_fu_272_p0),
    .din1(r_V_229_fu_272_p1),
    .dout(r_V_229_fu_272_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U494(
    .din0(mul_ln864_99_fu_273_p0),
    .din1(mul_ln864_99_fu_273_p1),
    .dout(mul_ln864_99_fu_273_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U495(
    .din0(mul_ln864_100_fu_274_p0),
    .din1(mul_ln864_100_fu_274_p1),
    .dout(mul_ln864_100_fu_274_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U496(
    .din0(mul_ln864_105_fu_275_p0),
    .din1(mul_ln864_105_fu_275_p1),
    .dout(mul_ln864_105_fu_275_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U497(
    .din0(r_V_224_fu_276_p0),
    .din1(r_V_224_fu_276_p1),
    .dout(r_V_224_fu_276_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U498(
    .din0(mul_ln864_96_fu_277_p0),
    .din1(mul_ln864_96_fu_277_p1),
    .dout(mul_ln864_96_fu_277_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U499(
    .din0(mul_ln864_89_fu_278_p0),
    .din1(mul_ln864_89_fu_278_p1),
    .dout(mul_ln864_89_fu_278_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U500(
    .din0(mul_ln864_107_fu_279_p0),
    .din1(mul_ln864_107_fu_279_p1),
    .dout(mul_ln864_107_fu_279_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U501(
    .din0(r_V_202_fu_280_p0),
    .din1(r_V_202_fu_280_p1),
    .dout(r_V_202_fu_280_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U502(
    .din0(r_V_234_fu_281_p0),
    .din1(r_V_234_fu_281_p1),
    .dout(r_V_234_fu_281_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U503(
    .din0(grp_fu_282_p0),
    .din1(grp_fu_282_p1),
    .dout(grp_fu_282_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U504(
    .din0(mul_ln864_104_fu_283_p0),
    .din1(mul_ln864_104_fu_283_p1),
    .dout(mul_ln864_104_fu_283_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U505(
    .din0(r_V_fu_284_p0),
    .din1(r_V_fu_284_p1),
    .dout(r_V_fu_284_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U506(
    .din0(r_V_199_fu_285_p0),
    .din1(r_V_199_fu_285_p1),
    .dout(r_V_199_fu_285_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U507(
    .din0(mul_ln864_106_fu_286_p0),
    .din1(mul_ln864_106_fu_286_p1),
    .dout(mul_ln864_106_fu_286_p2)
);

tau_nn_mul_9ns_5ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mul_9ns_5ns_13_1_1_U508(
    .din0(mul_ln864_92_fu_287_p0),
    .din1(mul_ln864_92_fu_287_p1),
    .dout(mul_ln864_92_fu_287_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U509(
    .din0(mul_ln864_90_fu_288_p0),
    .din1(mul_ln864_90_fu_288_p1),
    .dout(mul_ln864_90_fu_288_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U510(
    .din0(r_V_233_fu_289_p0),
    .din1(r_V_233_fu_289_p1),
    .dout(r_V_233_fu_289_p2)
);

tau_nn_mul_9ns_7s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 16 ))
mul_9ns_7s_16_1_1_U511(
    .din0(r_V_227_fu_290_p0),
    .din1(r_V_227_fu_290_p1),
    .dout(r_V_227_fu_290_p2)
);

tau_nn_mul_9ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_9ns_8ns_16_1_1_U512(
    .din0(mul_ln864_88_fu_291_p0),
    .din1(mul_ln864_88_fu_291_p1),
    .dout(mul_ln864_88_fu_291_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U513(
    .din0(r_V_221_fu_292_p0),
    .din1(r_V_221_fu_292_p1),
    .dout(r_V_221_fu_292_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U514(
    .din0(mul_ln864_98_fu_293_p0),
    .din1(mul_ln864_98_fu_293_p1),
    .dout(mul_ln864_98_fu_293_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U515(
    .din0(mul_ln864_108_fu_294_p0),
    .din1(mul_ln864_108_fu_294_p1),
    .dout(mul_ln864_108_fu_294_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U516(
    .din0(r_V_222_fu_295_p0),
    .din1(r_V_222_fu_295_p1),
    .dout(r_V_222_fu_295_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U517(
    .din0(grp_fu_296_p0),
    .din1(grp_fu_296_p1),
    .dout(grp_fu_296_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U518(
    .din0(mul_ln864_94_fu_297_p0),
    .din1(mul_ln864_94_fu_297_p1),
    .dout(mul_ln864_94_fu_297_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U519(
    .din0(mul_ln864_97_fu_298_p0),
    .din1(mul_ln864_97_fu_298_p1),
    .dout(mul_ln864_97_fu_298_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U520(
    .din0(mul_ln864_91_fu_299_p0),
    .din1(mul_ln864_91_fu_299_p1),
    .dout(mul_ln864_91_fu_299_p2)
);

tau_nn_mul_9ns_6s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6s_15_1_1_U521(
    .din0(r_V_231_fu_300_p0),
    .din1(r_V_231_fu_300_p1),
    .dout(r_V_231_fu_300_p2)
);

tau_nn_mul_9ns_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_9ns_6ns_14_1_1_U522(
    .din0(mul_ln864_93_fu_301_p0),
    .din1(mul_ln864_93_fu_301_p1),
    .dout(mul_ln864_93_fu_301_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U523(
    .din0(mul_ln864_109_fu_302_p0),
    .din1(mul_ln864_109_fu_302_p1),
    .dout(mul_ln864_109_fu_302_p2)
);

tau_nn_mul_9ns_7ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
mul_9ns_7ns_15_1_1_U524(
    .din0(mul_ln864_fu_303_p0),
    .din1(mul_ln864_fu_303_p1),
    .dout(mul_ln864_fu_303_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln859_443_reg_12000 <= add_ln859_443_fu_10908_p2;
        add_ln859_446_reg_12005 <= add_ln859_446_fu_10920_p2;
        add_ln859_451_reg_12010 <= add_ln859_451_fu_10936_p2;
        add_ln859_453_reg_12015 <= add_ln859_453_fu_10948_p2;
        add_ln859_456_reg_12020 <= add_ln859_456_fu_10960_p2;
        add_ln859_458_reg_12025 <= add_ln859_458_fu_10976_p2;
        add_ln859_461_reg_12030 <= add_ln859_461_fu_10982_p2;
        add_ln859_463_reg_12035 <= add_ln859_463_fu_10988_p2;
        add_ln859_467_reg_12040 <= add_ln859_467_fu_10994_p2;
        add_ln859_468_reg_12045 <= add_ln859_468_fu_11000_p2;
        add_ln859_470_reg_12050 <= add_ln859_470_fu_11006_p2;
        add_ln859_474_reg_12055 <= add_ln859_474_fu_11012_p2;
        add_ln859_477_reg_12060 <= add_ln859_477_fu_11018_p2;
        add_ln859_481_reg_12065 <= add_ln859_481_fu_11024_p2;
        add_ln859_483_reg_12070 <= add_ln859_483_fu_11030_p2;
        add_ln859_487_reg_12075 <= add_ln859_487_fu_11036_p2;
        add_ln859_488_reg_12080 <= add_ln859_488_fu_11042_p2;
        add_ln859_490_reg_12085 <= add_ln859_490_fu_11048_p2;
        add_ln859_495_reg_12090 <= add_ln859_495_fu_11060_p2;
        add_ln859_496_reg_12095 <= add_ln859_496_fu_11066_p2;
        add_ln859_499_reg_12100 <= add_ln859_499_fu_11072_p2;
        add_ln859_502_reg_12105 <= add_ln859_502_fu_11084_p2;
        add_ln859_507_reg_12110 <= add_ln859_507_fu_11090_p2;
        add_ln859_514_reg_12115 <= add_ln859_514_fu_11096_p2;
        add_ln859_516_reg_12120 <= add_ln859_516_fu_11102_p2;
        add_ln859_reg_11995 <= add_ln859_fu_10902_p2;
        p_read10106_reg_11891 <= p_read10;
        p_read399_reg_11897 <= p_read3;
        p_read_106_reg_11885 <= p_read12;
        trunc_ln17_134_reg_11934 <= {{mul_ln864_99_fu_273_p2[13:5]}};
        trunc_ln17_140_reg_11955 <= {{mul_ln864_104_fu_283_p2[13:5]}};
        trunc_ln17_144_reg_11985 <= {{add_ln864_53_fu_10876_p2[14:5]}};
        trunc_ln17_145_reg_11990 <= {{mul_ln864_109_fu_302_p2[14:5]}};
        trunc_ln5_reg_11909 <= {{r_V_fu_284_p2[15:5]}};
        trunc_ln864_239_reg_11914 <= {{r_V_202_fu_280_p2[15:5]}};
        trunc_ln864_244_reg_11919 <= {{r_V_206_fu_9630_p2[15:5]}};
        trunc_ln864_251_reg_11924 <= {{r_V_212_fu_9835_p2[15:5]}};
        trunc_ln864_257_reg_11929 <= {{r_V_218_fu_267_p2[14:5]}};
        trunc_ln864_261_reg_11949 <= {{r_V_221_fu_292_p2[14:5]}};
        trunc_ln864_272_reg_11960 <= {{sub_ln864_52_fu_10579_p2[14:5]}};
        trunc_ln864_274_reg_11965 <= {{r_V_229_fu_272_p2[14:5]}};
        trunc_ln864_275_reg_11970 <= {{r_V_230_fu_10678_p2[15:5]}};
        trunc_ln864_278_reg_11980 <= {{r_V_233_fu_289_p2[14:5]}};
        trunc_ln_reg_11904 <= {{mul_ln864_fu_303_p2[14:5]}};
        zext_ln1319_222_reg_11975[8 : 0] <= zext_ln1319_222_fu_10700_p1[8 : 0];
        zext_ln17_195_reg_11944[10 : 0] <= zext_ln17_195_fu_10199_p1[10 : 0];
        zext_ln864_193_reg_11939[8 : 0] <= zext_ln864_193_fu_10150_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln859_444_reg_12130 <= add_ln859_444_fu_11308_p2;
        add_ln859_449_reg_12135 <= add_ln859_449_fu_11337_p2;
        add_ln859_454_reg_12140 <= add_ln859_454_fu_11349_p2;
        add_ln859_459_reg_12145 <= add_ln859_459_fu_11361_p2;
        add_ln859_466_reg_12150 <= add_ln859_466_fu_11408_p2;
        add_ln859_473_reg_12155 <= add_ln859_473_fu_11453_p2;
        add_ln859_480_reg_12160 <= add_ln859_480_fu_11501_p2;
        add_ln859_486_reg_12165 <= add_ln859_486_fu_11543_p2;
        add_ln859_493_reg_12170 <= add_ln859_493_fu_11588_p2;
        add_ln859_498_reg_12175 <= add_ln859_498_fu_11610_p2;
        add_ln859_503_reg_12180 <= add_ln859_503_fu_11632_p2;
        add_ln859_506_reg_12185 <= add_ln859_506_fu_11653_p2;
        add_ln859_513_reg_12190 <= add_ln859_513_fu_11708_p2;
        add_ln859_515_reg_12195 <= add_ln859_515_fu_11717_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        trunc_ln864_280_reg_12125 <= {{grp_fu_296_p2[14:5]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_282_p0 = zext_ln864_193_reg_11939;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_282_p0 = zext_ln864_196_fu_10262_p1;
        end else begin
            grp_fu_282_p0 = 'bx;
        end
    end else begin
        grp_fu_282_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_296_p0 = zext_ln1319_222_reg_11975;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_296_p0 = zext_ln1319_196_fu_9651_p1;
        end else begin
            grp_fu_296_p0 = 'bx;
        end
    end else begin
        grp_fu_296_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln859_443_fu_10908_p2 = ($signed(sext_ln1319_86_fu_10022_p1) + $signed(sext_ln1319_89_fu_10220_p1));

assign add_ln859_444_fu_11308_p2 = ($signed(sext_ln859_247_fu_11305_p1) + $signed(sext_ln859_246_fu_11302_p1));

assign add_ln859_445_fu_10914_p2 = (zext_ln17_180_fu_9482_p1 + zext_ln17_199_fu_10349_p1);

assign add_ln859_446_fu_10920_p2 = (add_ln859_445_fu_10914_p2 + zext_ln17_179_fu_9344_p1);

assign add_ln859_447_fu_11317_p2 = ($signed(sext_ln864_100_fu_11169_p1) + $signed(12'd256));

assign add_ln859_448_fu_11327_p2 = ($signed(sext_ln859_248_fu_11323_p1) + $signed(sext_ln70_31_fu_11117_p1));

assign add_ln859_449_fu_11337_p2 = ($signed(sext_ln859_249_fu_11333_p1) + $signed(zext_ln859_fu_11314_p1));

assign add_ln859_450_fu_10926_p2 = (zext_ln17_181_fu_9559_p1 + zext_ln17_200_fu_10397_p1);

assign add_ln859_451_fu_10936_p2 = (zext_ln859_110_fu_10932_p1 + zext_ln17_188_fu_9726_p1);

assign add_ln859_452_fu_10942_p2 = ($signed(sext_ln1319_87_fu_10054_p1) + $signed(sext_ln1319_92_fu_10287_p1));

assign add_ln859_453_fu_10948_p2 = ($signed(add_ln859_452_fu_10942_p2) + $signed(sext_ln864_101_fu_9915_p1));

assign add_ln859_454_fu_11349_p2 = ($signed(sext_ln859_250_fu_11346_p1) + $signed(zext_ln859_111_fu_11343_p1));

assign add_ln859_455_fu_10954_p2 = (zext_ln17_190_fu_9821_p1 + zext_ln17_195_fu_10199_p1);

assign add_ln859_456_fu_10960_p2 = (add_ln859_455_fu_10954_p2 + zext_ln17_178_fu_9330_p1);

assign add_ln859_457_fu_10966_p2 = ($signed(sext_ln864_107_fu_10575_p1) + $signed(11'd2032));

assign add_ln859_458_fu_10976_p2 = ($signed(sext_ln859_252_fu_10972_p1) + $signed(sext_ln864_103_fu_10136_p1));

assign add_ln859_459_fu_11361_p2 = ($signed(sext_ln859_253_fu_11358_p1) + $signed(zext_ln859_112_fu_11355_p1));

assign add_ln859_460_fu_11367_p2 = (zext_ln17_fu_11108_p1 + zext_ln17_195_reg_11944);

assign add_ln859_461_fu_10982_p2 = (zext_ln17_198_fu_10267_p1 + zext_ln17_203_fu_10611_p1);

assign add_ln859_462_fu_11375_p2 = (zext_ln859_113_fu_11372_p1 + add_ln859_460_fu_11367_p2);

assign add_ln859_463_fu_10988_p2 = ($signed(sext_ln864_106_fu_10487_p1) + $signed(sext_ln864_109_fu_10718_p1));

assign add_ln859_464_fu_11388_p2 = (zext_ln17_183_fu_11120_p1 + 10'd32);

assign add_ln859_465_fu_11398_p2 = ($signed(zext_ln859_115_fu_11394_p1) + $signed(sext_ln859_254_fu_11385_p1));

assign add_ln859_466_fu_11408_p2 = ($signed(sext_ln859_255_fu_11404_p1) + $signed(zext_ln859_114_fu_11381_p1));

assign add_ln859_467_fu_10994_p2 = (trunc_ln17_s_fu_9246_p4 + zext_ln17_201_fu_10521_p1);

assign add_ln859_468_fu_11000_p2 = ($signed(zext_ln17_205_fu_10762_p1) + $signed(sext_ln864_95_fu_9414_p1));

assign add_ln859_469_fu_11420_p2 = ($signed(sext_ln859_256_fu_11417_p1) + $signed(zext_ln859_116_fu_11414_p1));

assign add_ln859_470_fu_11006_p2 = ($signed(sext_ln864_97_fu_9598_p1) + $signed(sext_ln1319_85_fu_9779_p1));

assign add_ln859_471_fu_11433_p2 = ($signed(sext_ln1319_91_fu_11181_p1) + $signed(11'd80));

assign add_ln859_472_fu_11443_p2 = ($signed(sext_ln859_259_fu_11439_p1) + $signed(sext_ln859_258_fu_11430_p1));

assign add_ln859_473_fu_11453_p2 = ($signed(sext_ln859_260_fu_11449_p1) + $signed(sext_ln859_257_fu_11426_p1));

assign add_ln859_474_fu_11012_p2 = (trunc_ln17_125_fu_9448_p4 + zext_ln17_182_fu_9612_p1);

assign add_ln859_475_fu_11462_p2 = ($signed(zext_ln1319_215_fu_11230_p1) + $signed(sext_ln864_fu_11111_p1));

assign add_ln859_476_fu_11468_p2 = (add_ln859_475_fu_11462_p2 + zext_ln859_117_fu_11459_p1);

assign add_ln859_477_fu_11018_p2 = ($signed(sext_ln864_102_fu_10068_p1) + $signed(sext_ln864_110_fu_10804_p1));

assign add_ln859_478_fu_11481_p2 = (zext_ln17_183_fu_11120_p1 + 10'd240);

assign add_ln859_479_fu_11491_p2 = ($signed(zext_ln859_118_fu_11487_p1) + $signed(sext_ln859_262_fu_11478_p1));

assign add_ln859_480_fu_11501_p2 = ($signed(sext_ln859_263_fu_11497_p1) + $signed(sext_ln859_261_fu_11474_p1));

assign add_ln859_481_fu_11024_p2 = ($signed(zext_ln17_206_fu_10818_p1) + $signed(sext_ln864_98_fu_9682_p1));

assign add_ln859_482_fu_11510_p2 = ($signed(sext_ln859_264_fu_11507_p1) + $signed(zext_ln864_207_fu_11286_p1));

assign add_ln859_483_fu_11030_p2 = ($signed(sext_ln864_104_fu_10244_p1) + $signed(sext_ln864_105_fu_10301_p1));

assign add_ln859_484_fu_11523_p2 = ($signed(sext_ln1319_94_fu_11290_p1) + $signed(11'd1984));

assign add_ln859_485_fu_11533_p2 = ($signed(sext_ln859_267_fu_11529_p1) + $signed(sext_ln859_266_fu_11520_p1));

assign add_ln859_486_fu_11543_p2 = ($signed(sext_ln859_268_fu_11539_p1) + $signed(sext_ln859_265_fu_11516_p1));

assign add_ln859_487_fu_11036_p2 = (trunc_ln17_121_fu_9266_p4 + zext_ln17_192_fu_9947_p1);

assign add_ln859_488_fu_11042_p2 = (zext_ln17_193_fu_10082_p1 + trunc_ln17_138_fu_10419_p4);

assign add_ln859_489_fu_11555_p2 = (zext_ln859_120_fu_11552_p1 + zext_ln859_119_fu_11549_p1);

assign add_ln859_490_fu_11048_p2 = ($signed(sext_ln1319_83_fu_9626_p1) + $signed(sext_ln864_99_fu_9793_p1));

assign add_ln859_491_fu_11568_p2 = ($signed(sext_ln1319_95_fu_11296_p1) + $signed(11'd96));

assign add_ln859_492_fu_11578_p2 = ($signed(sext_ln859_270_fu_11574_p1) + $signed(sext_ln859_269_fu_11565_p1));

assign add_ln859_493_fu_11588_p2 = ($signed(sext_ln859_271_fu_11584_p1) + $signed(zext_ln859_121_fu_11561_p1));

assign add_ln859_494_fu_11054_p2 = (zext_ln17_177_fu_9286_p1 + zext_ln17_196_fu_10258_p1);

assign add_ln859_495_fu_11060_p2 = (add_ln859_494_fu_11054_p2 + zext_ln17_189_fu_9807_p1);

assign add_ln859_496_fu_11066_p2 = ($signed(sext_ln70_34_fu_10467_p1) + $signed(sext_ln864_111_fu_10842_p1));

assign add_ln859_497_fu_11600_p2 = ($signed(sext_ln859_272_fu_11597_p1) + $signed(sext_ln1319_88_fu_11172_p1));

assign add_ln859_498_fu_11610_p2 = ($signed(sext_ln859_273_fu_11606_p1) + $signed(zext_ln859_122_fu_11594_p1));

assign add_ln859_499_fu_11072_p2 = (zext_ln17_204_fu_10625_p1 + zext_ln17_207_fu_10856_p1);

assign add_ln859_500_fu_11619_p2 = (zext_ln859_123_fu_11616_p1 + zext_ln17_202_fu_11234_p1);

assign add_ln859_501_fu_11078_p2 = ($signed(sext_ln70_35_fu_10501_p1) + $signed(12'd64));

assign add_ln859_502_fu_11084_p2 = ($signed(add_ln859_501_fu_11078_p2) + $signed(sext_ln864_96_fu_9468_p1));

assign add_ln859_503_fu_11632_p2 = ($signed(sext_ln859_274_fu_11629_p1) + $signed(zext_ln859_124_fu_11625_p1));

assign add_ln859_504_fu_11638_p2 = (zext_ln17_185_fu_11165_p1 + zext_ln17_197_fu_11184_p1);

assign add_ln859_505_fu_11644_p2 = (trunc_ln17_144_reg_11985 + 10'd112);

assign add_ln859_506_fu_11653_p2 = (zext_ln859_125_fu_11649_p1 + add_ln859_504_fu_11638_p2);

assign add_ln859_507_fu_11090_p2 = (zext_ln17_186_fu_9696_p1 + zext_ln17_191_fu_9861_p1);

assign add_ln859_508_fu_11662_p2 = (zext_ln17_194_fu_11175_p1 + zext_ln17_208_fu_11299_p1);

assign add_ln859_509_fu_11668_p2 = (add_ln859_508_fu_11662_p2 + zext_ln859_127_fu_11659_p1);

assign add_ln859_510_fu_11678_p2 = ($signed(sext_ln1319_82_fu_11114_p1) + $signed(sext_ln1319_90_fu_11178_p1));

assign add_ln859_511_fu_11688_p2 = ($signed(sext_ln70_37_fu_11293_p1) + $signed(12'd112));

assign add_ln859_512_fu_11698_p2 = ($signed(sext_ln859_276_fu_11694_p1) + $signed(sext_ln859_275_fu_11684_p1));

assign add_ln859_513_fu_11708_p2 = ($signed(sext_ln859_277_fu_11704_p1) + $signed(zext_ln859_128_fu_11674_p1));

assign add_ln859_514_fu_11096_p2 = ($signed(sext_ln70_fu_9358_p1) + $signed(sext_ln70_30_fu_9506_p1));

assign add_ln859_515_fu_11717_p2 = ($signed(sext_ln859_278_fu_11714_p1) + $signed(zext_ln70_11_fu_11240_p1));

assign add_ln859_516_fu_11102_p2 = ($signed(sext_ln70_32_fu_9700_p1) + $signed(sext_ln70_33_fu_9991_p1));

assign add_ln859_517_fu_11771_p2 = ($signed(sext_ln859_245_fu_11723_p1) + $signed(11'd2000));

assign add_ln859_518_fu_11781_p2 = ($signed(sext_ln859_281_fu_11777_p1) + $signed(sext_ln859_280_fu_11768_p1));

assign add_ln859_519_cast_fu_11797_p1 = $signed(add_ln859_519_fu_11791_p2);

assign add_ln859_519_fu_11791_p2 = ($signed(sext_ln859_282_fu_11787_p1) + $signed(sext_ln859_279_fu_11765_p1));

assign add_ln859_fu_10902_p2 = ($signed(zext_ln17_187_fu_9722_p1) + $signed(sext_ln1319_84_fu_9668_p1));

assign add_ln864_48_fu_9314_p2 = (zext_ln864_182_fu_9298_p1 + zext_ln864_183_fu_9310_p1);

assign add_ln864_49_fu_9442_p2 = (zext_ln864_184_fu_9426_p1 + zext_ln864_185_fu_9438_p1);

assign add_ln864_50_fu_9931_p2 = (zext_ln1319_201_fu_9873_p1 + zext_ln864_192_fu_9927_p1);

assign add_ln864_51_fu_10413_p2 = (zext_ln864_199_fu_10361_p1 + zext_ln864_201_fu_10409_p1);

assign add_ln864_52_fu_10746_p2 = (zext_ln864_208_fu_10730_p1 + zext_ln864_209_fu_10742_p1);

assign add_ln864_53_fu_10876_p2 = (zext_ln864_210_fu_10868_p1 + zext_ln864_211_fu_10872_p1);

assign add_ln864_fu_9240_p2 = (zext_ln864_181_fu_9236_p1 + zext_ln864_fu_9204_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = sext_ln859_141_fu_11738_p1;

assign ap_return_1 = sext_ln859_fu_11726_p1;

assign ap_return_10 = sext_ln859_139_fu_11735_p1;

assign ap_return_11 = sext_ln859_135_fu_11729_p1;

assign ap_return_12 = sext_ln859_154_fu_11762_p1;

assign ap_return_13 = add_ln859_519_cast_fu_11797_p1;

assign ap_return_2 = sext_ln859_251_fu_11732_p1;

assign ap_return_3 = sext_ln859_142_fu_11741_p1;

assign ap_return_4 = sext_ln859_145_fu_11744_p1;

assign ap_return_5 = sext_ln859_146_fu_11747_p1;

assign ap_return_6 = sext_ln859_148_fu_11750_p1;

assign ap_return_7 = sext_ln859_150_fu_11753_p1;

assign ap_return_8 = sext_ln859_152_fu_11756_p1;

assign ap_return_9 = zext_ln859_126_fu_11759_p1;

assign grp_fu_282_p1 = 14'd21;

assign grp_fu_296_p1 = 15'd32742;

assign grp_fu_9184_p4 = {{grp_fu_296_p2[14:5]}};

assign grp_fu_9194_p4 = {{grp_fu_282_p2[13:5]}};

assign mul_ln864_100_fu_274_p0 = mul_ln864_100_fu_274_p00;

assign mul_ln864_100_fu_274_p00 = p_read7;

assign mul_ln864_100_fu_274_p1 = 14'd26;

assign mul_ln864_103_fu_264_p0 = zext_ln864_204_fu_10505_p1;

assign mul_ln864_103_fu_264_p1 = 14'd27;

assign mul_ln864_104_fu_283_p0 = zext_ln864_204_fu_10505_p1;

assign mul_ln864_104_fu_283_p1 = 14'd22;

assign mul_ln864_105_fu_275_p0 = zext_ln70_fu_10595_p1;

assign mul_ln864_105_fu_275_p1 = 14'd19;

assign mul_ln864_106_fu_286_p0 = zext_ln70_fu_10595_p1;

assign mul_ln864_106_fu_286_p1 = 14'd25;

assign mul_ln864_107_fu_279_p0 = zext_ln1319_221_fu_10694_p1;

assign mul_ln864_107_fu_279_p1 = 14'd23;

assign mul_ln864_108_fu_294_p0 = zext_ln1319_221_fu_10694_p1;

assign mul_ln864_108_fu_294_p1 = 14'd26;

assign mul_ln864_109_fu_302_p0 = zext_ln1319_222_fu_10700_p1;

assign mul_ln864_109_fu_302_p1 = 15'd44;

assign mul_ln864_88_fu_291_p0 = zext_ln864_fu_9204_p1;

assign mul_ln864_88_fu_291_p1 = 16'd77;

assign mul_ln864_89_fu_278_p0 = zext_ln864_180_fu_9210_p1;

assign mul_ln864_89_fu_278_p1 = 15'd44;

assign mul_ln864_90_fu_288_p0 = zext_ln864_180_fu_9210_p1;

assign mul_ln864_90_fu_288_p1 = 15'd54;

assign mul_ln864_91_fu_299_p0 = zext_ln1319_191_fu_9367_p1;

assign mul_ln864_91_fu_299_p1 = 15'd35;

assign mul_ln864_92_fu_287_p0 = mul_ln864_92_fu_287_p00;

assign mul_ln864_92_fu_287_p00 = p_read2;

assign mul_ln864_92_fu_287_p1 = 13'd13;

assign mul_ln864_93_fu_301_p0 = mul_ln864_93_fu_301_p00;

assign mul_ln864_93_fu_301_p00 = p_read3;

assign mul_ln864_93_fu_301_p1 = 14'd21;

assign mul_ln864_94_fu_297_p0 = zext_ln864_191_fu_9704_p1;

assign mul_ln864_94_fu_297_p1 = 14'd23;

assign mul_ln864_95_fu_271_p0 = zext_ln864_191_fu_9704_p1;

assign mul_ln864_95_fu_271_p1 = 14'd26;

assign mul_ln864_96_fu_277_p0 = zext_ln864_191_fu_9704_p1;

assign mul_ln864_96_fu_277_p1 = 14'd21;

assign mul_ln864_97_fu_298_p0 = zext_ln864_191_fu_9704_p1;

assign mul_ln864_97_fu_298_p1 = 14'd27;

assign mul_ln864_98_fu_293_p0 = zext_ln1319_205_fu_9995_p1;

assign mul_ln864_98_fu_293_p1 = 14'd27;

assign mul_ln864_99_fu_273_p0 = zext_ln1319_205_fu_9995_p1;

assign mul_ln864_99_fu_273_p1 = 14'd22;

assign mul_ln864_fu_303_p0 = zext_ln864_180_fu_9210_p1;

assign mul_ln864_fu_303_p1 = 15'd47;

assign mult_V_29_fu_10752_p4 = {{add_ln864_52_fu_10746_p2[13:5]}};

assign mult_V_30_fu_10808_p4 = {{mul_ln864_107_fu_279_p2[13:5]}};

assign mult_V_fu_9712_p4 = {{mul_ln864_94_fu_297_p2[13:5]}};

assign r_V_199_fu_285_p0 = zext_ln864_180_fu_9210_p1;

assign r_V_199_fu_285_p1 = 15'd32746;

assign r_V_200_fu_9398_p2 = (zext_ln1319_193_fu_9394_p1 - zext_ln1319_192_fu_9382_p1);

assign r_V_201_fu_266_p0 = zext_ln1319_191_fu_9367_p1;

assign r_V_201_fu_266_p1 = 15'd32739;

assign r_V_202_fu_280_p0 = r_V_202_fu_280_p00;

assign r_V_202_fu_280_p00 = p_read1;

assign r_V_202_fu_280_p1 = 16'd65493;

assign r_V_203_fu_260_p0 = zext_ln1319_191_fu_9367_p1;

assign r_V_203_fu_260_p1 = 15'd32749;

assign r_V_204_fu_9582_p2 = ($signed(sext_ln1319_fu_9574_p1) - $signed(zext_ln1319_195_fu_9578_p1));

assign r_V_205_fu_268_p0 = zext_ln1319_194_fu_9563_p1;

assign r_V_205_fu_268_p1 = 16'd65489;

assign r_V_206_fu_9630_p2 = ($signed(sext_ln1319_fu_9574_p1) - $signed(zext_ln1319_194_fu_9563_p1));

assign r_V_207_fu_269_p0 = zext_ln1319_196_fu_9651_p1;

assign r_V_207_fu_269_p1 = 15'd32739;

assign r_V_208_fu_262_p0 = zext_ln1319_196_fu_9651_p1;

assign r_V_208_fu_262_p1 = 15'd32745;

assign r_V_210_fu_9763_p2 = (zext_ln1319_200_fu_9759_p1 - zext_ln1319_199_fu_9747_p1);

assign r_V_211_fu_258_p0 = r_V_211_fu_258_p00;

assign r_V_211_fu_258_p00 = p_read4;

assign r_V_211_fu_258_p1 = 15'd32749;

assign r_V_212_fu_9835_p2 = ($signed(sext_ln1319_28_fu_9831_p1) - $signed(zext_ln1319_197_fu_9730_p1));

assign r_V_213_fu_9899_p2 = ($signed(sext_ln1319_29_fu_9883_p1) - $signed(zext_ln1319_202_fu_9895_p1));

assign r_V_214_fu_9975_p2 = (zext_ln1319_204_fu_9971_p1 - zext_ln1319_203_fu_9959_p1);

assign r_V_215_fu_259_p0 = zext_ln1319_207_fu_10005_p1;

assign r_V_215_fu_259_p1 = 15'd32739;

assign r_V_216_fu_10038_p2 = (zext_ln1319_206_fu_10001_p1 - zext_ln1319_208_fu_10034_p1);

assign r_V_217_fu_265_p0 = zext_ln1319_207_fu_10005_p1;

assign r_V_217_fu_265_p1 = 15'd32742;

assign r_V_218_fu_267_p0 = zext_ln1319_207_fu_10005_p1;

assign r_V_218_fu_267_p1 = 15'd32746;

assign r_V_219_fu_10120_p2 = (zext_ln1319_210_fu_10116_p1 - zext_ln1319_209_fu_10104_p1);

assign r_V_220_fu_261_p0 = zext_ln1319_211_fu_10203_p1;

assign r_V_220_fu_261_p1 = 15'd32739;

assign r_V_221_fu_292_p0 = zext_ln1319_211_fu_10203_p1;

assign r_V_221_fu_292_p1 = 15'd32746;

assign r_V_222_fu_295_p0 = zext_ln1319_211_fu_10203_p1;

assign r_V_222_fu_295_p1 = 15'd32741;

assign r_V_223_fu_263_p0 = zext_ln1319_212_fu_10271_p1;

assign r_V_223_fu_263_p1 = 15'd32745;

assign r_V_224_fu_276_p0 = zext_ln1319_212_fu_10271_p1;

assign r_V_224_fu_276_p1 = 15'd32739;

assign r_V_225_fu_10451_p2 = ($signed(sext_ln1319_30_fu_10447_p1) - $signed(zext_ln864_201_fu_10409_p1));

assign r_V_226_fu_270_p0 = zext_ln1319_214_fu_10471_p1;

assign r_V_226_fu_270_p1 = 16'd65493;

assign r_V_227_fu_290_p0 = zext_ln1319_214_fu_10471_p1;

assign r_V_227_fu_290_p1 = 16'd65487;

assign r_V_228_fu_10559_p2 = (zext_ln1319_217_fu_10555_p1 - zext_ln1319_216_fu_10543_p1);

assign r_V_229_fu_272_p0 = r_V_229_fu_272_p00;

assign r_V_229_fu_272_p00 = p_read13;

assign r_V_229_fu_272_p1 = 15'd32747;

assign r_V_230_fu_10678_p2 = ($signed(sext_ln1319_31_fu_10662_p1) - $signed(zext_ln1319_220_fu_10674_p1));

assign r_V_231_fu_300_p0 = zext_ln1319_222_fu_10700_p1;

assign r_V_231_fu_300_p1 = 15'd32741;

assign r_V_232_fu_10788_p2 = ($signed(sext_ln1319_32_fu_10784_p1) - $signed(zext_ln1319_221_fu_10694_p1));

assign r_V_233_fu_289_p0 = zext_ln1319_222_fu_10700_p1;

assign r_V_233_fu_289_p1 = 15'd32743;

assign r_V_234_fu_281_p0 = zext_ln1319_222_fu_10700_p1;

assign r_V_234_fu_281_p1 = 15'd32745;

assign r_V_fu_284_p0 = zext_ln864_fu_9204_p1;

assign r_V_fu_284_p1 = 16'd65486;

assign sext_ln1319_28_fu_9831_p1 = $signed(sub_ln1319_115_fu_9825_p2);

assign sext_ln1319_29_fu_9883_p1 = $signed(sub_ln1319_117_fu_9877_p2);

assign sext_ln1319_30_fu_10447_p1 = $signed(sub_ln1319_121_fu_10441_p2);

assign sext_ln1319_31_fu_10662_p1 = $signed(sub_ln1319_125_fu_10656_p2);

assign sext_ln1319_32_fu_10784_p1 = $signed(sub_ln1319_127_fu_10778_p2);

assign sext_ln1319_82_fu_11114_p1 = $signed(trunc_ln864_239_reg_11914);

assign sext_ln1319_83_fu_9626_p1 = $signed(trunc_ln864_243_fu_9616_p4);

assign sext_ln1319_84_fu_9668_p1 = $signed(trunc_ln864_245_fu_9658_p4);

assign sext_ln1319_85_fu_9779_p1 = $signed(trunc_ln864_249_fu_9769_p4);

assign sext_ln1319_86_fu_10022_p1 = $signed(trunc_ln864_254_fu_10012_p4);

assign sext_ln1319_87_fu_10054_p1 = $signed(trunc_ln864_255_fu_10044_p4);

assign sext_ln1319_88_fu_11172_p1 = $signed(trunc_ln864_257_reg_11929);

assign sext_ln1319_89_fu_10220_p1 = $signed(trunc_ln864_260_fu_10210_p4);

assign sext_ln1319_90_fu_11178_p1 = trunc_ln864_261_reg_11949;

assign sext_ln1319_91_fu_11181_p1 = trunc_ln864_261_reg_11949;

assign sext_ln1319_92_fu_10287_p1 = $signed(trunc_ln864_263_fu_10277_p4);

assign sext_ln1319_93_fu_11226_p1 = $signed(trunc_ln864_269_fu_11216_p4);

assign sext_ln1319_94_fu_11290_p1 = $signed(trunc_ln864_274_reg_11965);

assign sext_ln1319_95_fu_11296_p1 = $signed(trunc_ln864_278_reg_11980);

assign sext_ln1319_fu_9574_p1 = $signed(sub_ln1319_fu_9568_p2);

assign sext_ln17_45_fu_11161_p1 = $signed(trunc_ln864_247_fu_11151_p4);

assign sext_ln17_46_fu_10195_p1 = $signed(trunc_ln864_259_fu_10185_p4);

assign sext_ln17_47_fu_10345_p1 = $signed(trunc_ln864_265_fu_10335_p4);

assign sext_ln17_48_fu_10393_p1 = $signed(trunc_ln864_266_fu_10383_p4);

assign sext_ln17_fu_9555_p1 = $signed(trunc_ln864_241_fu_9545_p4);

assign sext_ln70_30_fu_9506_p1 = $signed(trunc_ln864_240_fu_9496_p4);

assign sext_ln70_31_fu_11117_p1 = $signed(trunc_ln864_244_reg_11919);

assign sext_ln70_32_fu_9700_p1 = $signed(grp_fu_9184_p4);

assign sext_ln70_33_fu_9991_p1 = $signed(trunc_ln864_253_fu_9981_p4);

assign sext_ln70_34_fu_10467_p1 = $signed(trunc_ln864_267_fu_10457_p4);

assign sext_ln70_35_fu_10501_p1 = $signed(trunc_ln864_270_fu_10491_p4);

assign sext_ln70_36_fu_11237_p1 = $signed(trunc_ln864_272_reg_11960);

assign sext_ln70_37_fu_11293_p1 = $signed(trunc_ln864_275_reg_11970);

assign sext_ln70_fu_9358_p1 = $signed(trunc_ln864_s_fu_9348_p4);

assign sext_ln859_135_fu_11729_p1 = $signed(add_ln859_449_reg_12135);

assign sext_ln859_139_fu_11735_p1 = $signed(add_ln859_459_reg_12145);

assign sext_ln859_141_fu_11738_p1 = $signed(add_ln859_466_reg_12150);

assign sext_ln859_142_fu_11741_p1 = $signed(add_ln859_473_reg_12155);

assign sext_ln859_145_fu_11744_p1 = $signed(add_ln859_480_reg_12160);

assign sext_ln859_146_fu_11747_p1 = $signed(add_ln859_486_reg_12165);

assign sext_ln859_148_fu_11750_p1 = $signed(add_ln859_493_reg_12170);

assign sext_ln859_150_fu_11753_p1 = $signed(add_ln859_498_reg_12175);

assign sext_ln859_152_fu_11756_p1 = $signed(add_ln859_503_reg_12180);

assign sext_ln859_154_fu_11762_p1 = $signed(add_ln859_513_reg_12190);

assign sext_ln859_245_fu_11723_p1 = $signed(trunc_ln864_280_reg_12125);

assign sext_ln859_246_fu_11302_p1 = $signed(add_ln859_reg_11995);

assign sext_ln859_247_fu_11305_p1 = $signed(add_ln859_443_reg_12000);

assign sext_ln859_248_fu_11323_p1 = $signed(add_ln859_447_fu_11317_p2);

assign sext_ln859_249_fu_11333_p1 = $signed(add_ln859_448_fu_11327_p2);

assign sext_ln859_250_fu_11346_p1 = $signed(add_ln859_453_reg_12015);

assign sext_ln859_251_fu_11732_p1 = $signed(add_ln859_454_reg_12140);

assign sext_ln859_252_fu_10972_p1 = $signed(add_ln859_457_fu_10966_p2);

assign sext_ln859_253_fu_11358_p1 = $signed(add_ln859_458_reg_12025);

assign sext_ln859_254_fu_11385_p1 = $signed(add_ln859_463_reg_12035);

assign sext_ln859_255_fu_11404_p1 = $signed(add_ln859_465_fu_11398_p2);

assign sext_ln859_256_fu_11417_p1 = $signed(add_ln859_468_reg_12045);

assign sext_ln859_257_fu_11426_p1 = $signed(add_ln859_469_fu_11420_p2);

assign sext_ln859_258_fu_11430_p1 = $signed(add_ln859_470_reg_12050);

assign sext_ln859_259_fu_11439_p1 = $signed(add_ln859_471_fu_11433_p2);

assign sext_ln859_260_fu_11449_p1 = $signed(add_ln859_472_fu_11443_p2);

assign sext_ln859_261_fu_11474_p1 = $signed(add_ln859_476_fu_11468_p2);

assign sext_ln859_262_fu_11478_p1 = $signed(add_ln859_477_reg_12060);

assign sext_ln859_263_fu_11497_p1 = $signed(add_ln859_479_fu_11491_p2);

assign sext_ln859_264_fu_11507_p1 = $signed(add_ln859_481_reg_12065);

assign sext_ln859_265_fu_11516_p1 = $signed(add_ln859_482_fu_11510_p2);

assign sext_ln859_266_fu_11520_p1 = $signed(add_ln859_483_reg_12070);

assign sext_ln859_267_fu_11529_p1 = $signed(add_ln859_484_fu_11523_p2);

assign sext_ln859_268_fu_11539_p1 = $signed(add_ln859_485_fu_11533_p2);

assign sext_ln859_269_fu_11565_p1 = $signed(add_ln859_490_reg_12085);

assign sext_ln859_270_fu_11574_p1 = $signed(add_ln859_491_fu_11568_p2);

assign sext_ln859_271_fu_11584_p1 = $signed(add_ln859_492_fu_11578_p2);

assign sext_ln859_272_fu_11597_p1 = $signed(add_ln859_496_reg_12095);

assign sext_ln859_273_fu_11606_p1 = $signed(add_ln859_497_fu_11600_p2);

assign sext_ln859_274_fu_11629_p1 = $signed(add_ln859_502_reg_12105);

assign sext_ln859_275_fu_11684_p1 = $signed(add_ln859_510_fu_11678_p2);

assign sext_ln859_276_fu_11694_p1 = $signed(add_ln859_511_fu_11688_p2);

assign sext_ln859_277_fu_11704_p1 = $signed(add_ln859_512_fu_11698_p2);

assign sext_ln859_278_fu_11714_p1 = $signed(add_ln859_514_reg_12115);

assign sext_ln859_279_fu_11765_p1 = $signed(add_ln859_515_reg_12195);

assign sext_ln859_280_fu_11768_p1 = $signed(add_ln859_516_reg_12120);

assign sext_ln859_281_fu_11777_p1 = $signed(add_ln859_517_fu_11771_p2);

assign sext_ln859_282_fu_11787_p1 = $signed(add_ln859_518_fu_11781_p2);

assign sext_ln859_fu_11726_p1 = $signed(add_ln859_444_reg_12130);

assign sext_ln864_100_fu_11169_p1 = $signed(trunc_ln864_251_reg_11924);

assign sext_ln864_101_fu_9915_p1 = $signed(trunc_ln864_252_fu_9905_p4);

assign sext_ln864_102_fu_10068_p1 = $signed(trunc_ln864_256_fu_10058_p4);

assign sext_ln864_103_fu_10136_p1 = $signed(trunc_ln864_258_fu_10126_p4);

assign sext_ln864_104_fu_10244_p1 = $signed(trunc_ln864_262_fu_10234_p4);

assign sext_ln864_105_fu_10301_p1 = $signed(trunc_ln864_264_fu_10291_p4);

assign sext_ln864_106_fu_10487_p1 = $signed(trunc_ln864_268_fu_10477_p4);

assign sext_ln864_107_fu_10575_p1 = $signed(trunc_ln864_271_fu_10565_p4);

assign sext_ln864_108_fu_11282_p1 = $signed(trunc_ln864_273_fu_11272_p4);

assign sext_ln864_109_fu_10718_p1 = $signed(trunc_ln864_276_fu_10708_p4);

assign sext_ln864_110_fu_10804_p1 = $signed(trunc_ln864_277_fu_10794_p4);

assign sext_ln864_111_fu_10842_p1 = $signed(trunc_ln864_279_fu_10832_p4);

assign sext_ln864_95_fu_9414_p1 = $signed(trunc_ln864_237_fu_9404_p4);

assign sext_ln864_96_fu_9468_p1 = $signed(trunc_ln864_238_fu_9458_p4);

assign sext_ln864_97_fu_9598_p1 = $signed(trunc_ln864_242_fu_9588_p4);

assign sext_ln864_98_fu_9682_p1 = $signed(trunc_ln864_246_fu_9672_p4);

assign sext_ln864_99_fu_9793_p1 = $signed(trunc_ln864_250_fu_9783_p4);

assign sext_ln864_fu_11111_p1 = $signed(trunc_ln5_reg_11909);

assign shl_ln1319_85_fu_9739_p3 = {{p_read4}, {5'd0}};

assign shl_ln1319_86_fu_9751_p3 = {{p_read4}, {3'd0}};

assign shl_ln1319_87_fu_9865_p3 = {{p_read5}, {4'd0}};

assign shl_ln1319_88_fu_9887_p3 = {{p_read5}, {1'd0}};

assign shl_ln1319_89_fu_9951_p3 = {{p_read5}, {5'd0}};

assign shl_ln1319_90_fu_9963_p3 = {{p_read5}, {3'd0}};

assign shl_ln1319_91_fu_10096_p3 = {{p_read6}, {5'd0}};

assign shl_ln1319_92_fu_10108_p3 = {{p_read6}, {2'd0}};

assign shl_ln1319_93_fu_10429_p3 = {{p_read9}, {4'd0}};

assign shl_ln1319_94_fu_10535_p3 = {{p_read11}, {5'd0}};

assign shl_ln1319_95_fu_10547_p3 = {{p_read11}, {3'd0}};

assign shl_ln1319_96_fu_10644_p3 = {{p_read13}, {5'd0}};

assign shl_ln1319_97_fu_10666_p3 = {{p_read13}, {2'd0}};

assign shl_ln1319_98_fu_10766_p3 = {{p_read14}, {3'd0}};

assign shl_ln1319_s_fu_9386_p3 = {{p_read1}, {2'd0}};

assign shl_ln3_fu_9374_p3 = {{p_read1}, {6'd0}};

assign shl_ln864_100_fu_9919_p3 = {{p_read5}, {2'd0}};

assign shl_ln864_101_fu_10155_p3 = {{p_read7}, {5'd0}};

assign shl_ln864_102_fu_10167_p3 = {{p_read7}, {3'd0}};

assign shl_ln864_103_fu_10305_p3 = {{p_read8}, {5'd0}};

assign shl_ln864_104_fu_10317_p3 = {{p_read8}, {1'd0}};

assign shl_ln864_105_fu_10353_p3 = {{p_read9}, {5'd0}};

assign shl_ln864_106_fu_10365_p3 = {{p_read9}, {3'd0}};

assign shl_ln864_107_fu_10401_p3 = {{p_read9}, {1'd0}};

assign shl_ln864_108_fu_11188_p3 = {{p_read10106_reg_11891}, {5'd0}};

assign shl_ln864_109_fu_11199_p3 = {{p_read10106_reg_11891}, {2'd0}};

assign shl_ln864_110_fu_11244_p3 = {{p_read_106_reg_11885}, {5'd0}};

assign shl_ln864_111_fu_11255_p3 = {{p_read_106_reg_11885}, {3'd0}};

assign shl_ln864_112_fu_10722_p3 = {{p_read14}, {4'd0}};

assign shl_ln864_113_fu_10734_p3 = {{p_read14}, {2'd0}};

assign shl_ln864_114_fu_10860_p3 = {{p_read14}, {5'd0}};

assign shl_ln864_93_fu_9302_p3 = {{p_read}, {1'd0}};

assign shl_ln864_94_fu_9418_p3 = {{p_read1}, {5'd0}};

assign shl_ln864_95_fu_9430_p3 = {{p_read1}, {1'd0}};

assign shl_ln864_96_fu_9515_p3 = {{p_read2}, {5'd0}};

assign shl_ln864_97_fu_9527_p3 = {{p_read2}, {3'd0}};

assign shl_ln864_98_fu_11123_p3 = {{p_read399_reg_11897}, {5'd0}};

assign shl_ln864_99_fu_11134_p3 = {{p_read399_reg_11897}, {1'd0}};

assign shl_ln864_s_fu_9290_p3 = {{p_read}, {4'd0}};

assign shl_ln_fu_9228_p3 = {{p_read}, {6'd0}};

assign sub_ln1319_115_fu_9825_p2 = (15'd0 - zext_ln1319_199_fu_9747_p1);

assign sub_ln1319_117_fu_9877_p2 = (14'd0 - zext_ln1319_201_fu_9873_p1);

assign sub_ln1319_121_fu_10441_p2 = (14'd0 - zext_ln1319_213_fu_10437_p1);

assign sub_ln1319_125_fu_10656_p2 = (15'd0 - zext_ln1319_219_fu_10652_p1);

assign sub_ln1319_127_fu_10778_p2 = (13'd0 - zext_ln1319_223_fu_10774_p1);

assign sub_ln1319_fu_9568_p2 = (15'd0 - zext_ln864_187_fu_9523_p1);

assign sub_ln864_47_fu_11145_p2 = (zext_ln864_189_fu_11130_p1 - zext_ln864_190_fu_11141_p1);

assign sub_ln864_48_fu_10179_p2 = (zext_ln864_194_fu_10163_p1 - zext_ln864_195_fu_10175_p1);

assign sub_ln864_49_fu_10329_p2 = (zext_ln864_197_fu_10313_p1 - zext_ln864_198_fu_10325_p1);

assign sub_ln864_50_fu_10377_p2 = (zext_ln864_199_fu_10361_p1 - zext_ln864_200_fu_10373_p1);

assign sub_ln864_51_fu_11210_p2 = (zext_ln864_202_fu_11195_p1 - zext_ln864_203_fu_11206_p1);

assign sub_ln864_52_fu_10579_p2 = (zext_ln1319_216_fu_10543_p1 - zext_ln1319_217_fu_10555_p1);

assign sub_ln864_53_fu_11266_p2 = (zext_ln864_205_fu_11251_p1 - zext_ln864_206_fu_11262_p1);

assign sub_ln864_fu_9539_p2 = (zext_ln864_187_fu_9523_p1 - zext_ln864_188_fu_9535_p1);

assign tmp_fu_10026_p3 = {{p_read6}, {6'd0}};

assign trunc_ln17_121_fu_9266_p4 = {{mul_ln864_88_fu_291_p2[15:5]}};

assign trunc_ln17_122_fu_9276_p4 = {{mul_ln864_89_fu_278_p2[14:5]}};

assign trunc_ln17_123_fu_9320_p4 = {{add_ln864_48_fu_9314_p2[13:5]}};

assign trunc_ln17_124_fu_9334_p4 = {{mul_ln864_90_fu_288_p2[14:5]}};

assign trunc_ln17_125_fu_9448_p4 = {{add_ln864_49_fu_9442_p2[14:5]}};

assign trunc_ln17_126_fu_9472_p4 = {{mul_ln864_91_fu_299_p2[14:5]}};

assign trunc_ln17_127_fu_9602_p4 = {{mul_ln864_92_fu_287_p2[12:5]}};

assign trunc_ln17_128_fu_9686_p4 = {{mul_ln864_93_fu_301_p2[13:5]}};

assign trunc_ln17_129_fu_9797_p4 = {{mul_ln864_95_fu_271_p2[13:5]}};

assign trunc_ln17_130_fu_9811_p4 = {{mul_ln864_96_fu_277_p2[13:5]}};

assign trunc_ln17_131_fu_9851_p4 = {{mul_ln864_97_fu_298_p2[13:5]}};

assign trunc_ln17_132_fu_9937_p4 = {{add_ln864_50_fu_9931_p2[13:5]}};

assign trunc_ln17_133_fu_10072_p4 = {{mul_ln864_98_fu_293_p2[13:5]}};

assign trunc_ln17_135_fu_10248_p4 = {{mul_ln864_100_fu_274_p2[13:5]}};

assign trunc_ln17_138_fu_10419_p4 = {{add_ln864_51_fu_10413_p2[14:5]}};

assign trunc_ln17_139_fu_10511_p4 = {{mul_ln864_103_fu_264_p2[13:5]}};

assign trunc_ln17_141_fu_10601_p4 = {{mul_ln864_105_fu_275_p2[13:5]}};

assign trunc_ln17_142_fu_10615_p4 = {{mul_ln864_106_fu_286_p2[13:5]}};

assign trunc_ln17_143_fu_10846_p4 = {{mul_ln864_108_fu_294_p2[13:5]}};

assign trunc_ln17_s_fu_9246_p4 = {{add_ln864_fu_9240_p2[15:5]}};

assign trunc_ln864_237_fu_9404_p4 = {{r_V_200_fu_9398_p2[15:5]}};

assign trunc_ln864_238_fu_9458_p4 = {{r_V_201_fu_266_p2[14:5]}};

assign trunc_ln864_240_fu_9496_p4 = {{r_V_203_fu_260_p2[14:5]}};

assign trunc_ln864_241_fu_9545_p4 = {{sub_ln864_fu_9539_p2[14:5]}};

assign trunc_ln864_242_fu_9588_p4 = {{r_V_204_fu_9582_p2[15:5]}};

assign trunc_ln864_243_fu_9616_p4 = {{r_V_205_fu_268_p2[15:5]}};

assign trunc_ln864_245_fu_9658_p4 = {{r_V_207_fu_269_p2[14:5]}};

assign trunc_ln864_246_fu_9672_p4 = {{r_V_208_fu_262_p2[14:5]}};

assign trunc_ln864_247_fu_11151_p4 = {{sub_ln864_47_fu_11145_p2[14:5]}};

assign trunc_ln864_249_fu_9769_p4 = {{r_V_210_fu_9763_p2[14:5]}};

assign trunc_ln864_250_fu_9783_p4 = {{r_V_211_fu_258_p2[14:5]}};

assign trunc_ln864_252_fu_9905_p4 = {{r_V_213_fu_9899_p2[14:5]}};

assign trunc_ln864_253_fu_9981_p4 = {{r_V_214_fu_9975_p2[14:5]}};

assign trunc_ln864_254_fu_10012_p4 = {{r_V_215_fu_259_p2[14:5]}};

assign trunc_ln864_255_fu_10044_p4 = {{r_V_216_fu_10038_p2[15:5]}};

assign trunc_ln864_256_fu_10058_p4 = {{r_V_217_fu_265_p2[14:5]}};

assign trunc_ln864_258_fu_10126_p4 = {{r_V_219_fu_10120_p2[14:5]}};

assign trunc_ln864_259_fu_10185_p4 = {{sub_ln864_48_fu_10179_p2[14:5]}};

assign trunc_ln864_260_fu_10210_p4 = {{r_V_220_fu_261_p2[14:5]}};

assign trunc_ln864_262_fu_10234_p4 = {{r_V_222_fu_295_p2[14:5]}};

assign trunc_ln864_263_fu_10277_p4 = {{r_V_223_fu_263_p2[14:5]}};

assign trunc_ln864_264_fu_10291_p4 = {{r_V_224_fu_276_p2[14:5]}};

assign trunc_ln864_265_fu_10335_p4 = {{sub_ln864_49_fu_10329_p2[14:5]}};

assign trunc_ln864_266_fu_10383_p4 = {{sub_ln864_50_fu_10377_p2[14:5]}};

assign trunc_ln864_267_fu_10457_p4 = {{r_V_225_fu_10451_p2[14:5]}};

assign trunc_ln864_268_fu_10477_p4 = {{r_V_226_fu_270_p2[15:5]}};

assign trunc_ln864_269_fu_11216_p4 = {{sub_ln864_51_fu_11210_p2[14:5]}};

assign trunc_ln864_270_fu_10491_p4 = {{r_V_227_fu_290_p2[15:5]}};

assign trunc_ln864_271_fu_10565_p4 = {{r_V_228_fu_10559_p2[14:5]}};

assign trunc_ln864_273_fu_11272_p4 = {{sub_ln864_53_fu_11266_p2[14:5]}};

assign trunc_ln864_276_fu_10708_p4 = {{r_V_231_fu_300_p2[14:5]}};

assign trunc_ln864_277_fu_10794_p4 = {{r_V_232_fu_10788_p2[13:5]}};

assign trunc_ln864_279_fu_10832_p4 = {{r_V_234_fu_281_p2[14:5]}};

assign trunc_ln864_s_fu_9348_p4 = {{r_V_199_fu_285_p2[14:5]}};

assign zext_ln1319_191_fu_9367_p1 = p_read1;

assign zext_ln1319_192_fu_9382_p1 = shl_ln3_fu_9374_p3;

assign zext_ln1319_193_fu_9394_p1 = shl_ln1319_s_fu_9386_p3;

assign zext_ln1319_194_fu_9563_p1 = p_read2;

assign zext_ln1319_195_fu_9578_p1 = shl_ln864_97_fu_9527_p3;

assign zext_ln1319_196_fu_9651_p1 = p_read3;

assign zext_ln1319_197_fu_9730_p1 = p_read4;

assign zext_ln1319_199_fu_9747_p1 = shl_ln1319_85_fu_9739_p3;

assign zext_ln1319_200_fu_9759_p1 = shl_ln1319_86_fu_9751_p3;

assign zext_ln1319_201_fu_9873_p1 = shl_ln1319_87_fu_9865_p3;

assign zext_ln1319_202_fu_9895_p1 = shl_ln1319_88_fu_9887_p3;

assign zext_ln1319_203_fu_9959_p1 = shl_ln1319_89_fu_9951_p3;

assign zext_ln1319_204_fu_9971_p1 = shl_ln1319_90_fu_9963_p3;

assign zext_ln1319_205_fu_9995_p1 = p_read6;

assign zext_ln1319_206_fu_10001_p1 = p_read6;

assign zext_ln1319_207_fu_10005_p1 = p_read6;

assign zext_ln1319_208_fu_10034_p1 = tmp_fu_10026_p3;

assign zext_ln1319_209_fu_10104_p1 = shl_ln1319_91_fu_10096_p3;

assign zext_ln1319_210_fu_10116_p1 = shl_ln1319_92_fu_10108_p3;

assign zext_ln1319_211_fu_10203_p1 = p_read7;

assign zext_ln1319_212_fu_10271_p1 = p_read8;

assign zext_ln1319_213_fu_10437_p1 = shl_ln1319_93_fu_10429_p3;

assign zext_ln1319_214_fu_10471_p1 = p_read10;

assign zext_ln1319_215_fu_11230_p1 = $unsigned(sext_ln1319_93_fu_11226_p1);

assign zext_ln1319_216_fu_10543_p1 = shl_ln1319_94_fu_10535_p3;

assign zext_ln1319_217_fu_10555_p1 = shl_ln1319_95_fu_10547_p3;

assign zext_ln1319_219_fu_10652_p1 = shl_ln1319_96_fu_10644_p3;

assign zext_ln1319_220_fu_10674_p1 = shl_ln1319_97_fu_10666_p3;

assign zext_ln1319_221_fu_10694_p1 = p_read14;

assign zext_ln1319_222_fu_10700_p1 = p_read14;

assign zext_ln1319_223_fu_10774_p1 = shl_ln1319_98_fu_10766_p3;

assign zext_ln17_177_fu_9286_p1 = trunc_ln17_122_fu_9276_p4;

assign zext_ln17_178_fu_9330_p1 = trunc_ln17_123_fu_9320_p4;

assign zext_ln17_179_fu_9344_p1 = trunc_ln17_124_fu_9334_p4;

assign zext_ln17_180_fu_9482_p1 = trunc_ln17_126_fu_9472_p4;

assign zext_ln17_181_fu_9559_p1 = $unsigned(sext_ln17_fu_9555_p1);

assign zext_ln17_182_fu_9612_p1 = trunc_ln17_127_fu_9602_p4;

assign zext_ln17_183_fu_11120_p1 = p_read399_reg_11897;

assign zext_ln17_185_fu_11165_p1 = $unsigned(sext_ln17_45_fu_11161_p1);

assign zext_ln17_186_fu_9696_p1 = trunc_ln17_128_fu_9686_p4;

assign zext_ln17_187_fu_9722_p1 = mult_V_fu_9712_p4;

assign zext_ln17_188_fu_9726_p1 = mult_V_fu_9712_p4;

assign zext_ln17_189_fu_9807_p1 = trunc_ln17_129_fu_9797_p4;

assign zext_ln17_190_fu_9821_p1 = trunc_ln17_130_fu_9811_p4;

assign zext_ln17_191_fu_9861_p1 = trunc_ln17_131_fu_9851_p4;

assign zext_ln17_192_fu_9947_p1 = trunc_ln17_132_fu_9937_p4;

assign zext_ln17_193_fu_10082_p1 = trunc_ln17_133_fu_10072_p4;

assign zext_ln17_194_fu_11175_p1 = trunc_ln17_134_reg_11934;

assign zext_ln17_195_fu_10199_p1 = $unsigned(sext_ln17_46_fu_10195_p1);

assign zext_ln17_196_fu_10258_p1 = trunc_ln17_135_fu_10248_p4;

assign zext_ln17_197_fu_11184_p1 = grp_fu_9194_p4;

assign zext_ln17_198_fu_10267_p1 = grp_fu_9194_p4;

assign zext_ln17_199_fu_10349_p1 = $unsigned(sext_ln17_47_fu_10345_p1);

assign zext_ln17_200_fu_10397_p1 = $unsigned(sext_ln17_48_fu_10393_p1);

assign zext_ln17_201_fu_10521_p1 = trunc_ln17_139_fu_10511_p4;

assign zext_ln17_202_fu_11234_p1 = trunc_ln17_140_reg_11955;

assign zext_ln17_203_fu_10611_p1 = trunc_ln17_141_fu_10601_p4;

assign zext_ln17_204_fu_10625_p1 = trunc_ln17_142_fu_10615_p4;

assign zext_ln17_205_fu_10762_p1 = mult_V_29_fu_10752_p4;

assign zext_ln17_206_fu_10818_p1 = mult_V_30_fu_10808_p4;

assign zext_ln17_207_fu_10856_p1 = trunc_ln17_143_fu_10846_p4;

assign zext_ln17_208_fu_11299_p1 = trunc_ln17_145_reg_11990;

assign zext_ln17_fu_11108_p1 = trunc_ln_reg_11904;

assign zext_ln70_11_fu_11240_p1 = $unsigned(sext_ln70_36_fu_11237_p1);

assign zext_ln70_fu_10595_p1 = p_read12;

assign zext_ln859_110_fu_10932_p1 = add_ln859_450_fu_10926_p2;

assign zext_ln859_111_fu_11343_p1 = add_ln859_451_reg_12010;

assign zext_ln859_112_fu_11355_p1 = add_ln859_456_reg_12020;

assign zext_ln859_113_fu_11372_p1 = add_ln859_461_reg_12030;

assign zext_ln859_114_fu_11381_p1 = add_ln859_462_fu_11375_p2;

assign zext_ln859_115_fu_11394_p1 = add_ln859_464_fu_11388_p2;

assign zext_ln859_116_fu_11414_p1 = add_ln859_467_reg_12040;

assign zext_ln859_117_fu_11459_p1 = add_ln859_474_reg_12055;

assign zext_ln859_118_fu_11487_p1 = add_ln859_478_fu_11481_p2;

assign zext_ln859_119_fu_11549_p1 = add_ln859_487_reg_12075;

assign zext_ln859_120_fu_11552_p1 = add_ln859_488_reg_12080;

assign zext_ln859_121_fu_11561_p1 = add_ln859_489_fu_11555_p2;

assign zext_ln859_122_fu_11594_p1 = add_ln859_495_reg_12090;

assign zext_ln859_123_fu_11616_p1 = add_ln859_499_reg_12100;

assign zext_ln859_124_fu_11625_p1 = add_ln859_500_fu_11619_p2;

assign zext_ln859_125_fu_11649_p1 = add_ln859_505_fu_11644_p2;

assign zext_ln859_126_fu_11759_p1 = add_ln859_506_reg_12185;

assign zext_ln859_127_fu_11659_p1 = add_ln859_507_reg_12110;

assign zext_ln859_128_fu_11674_p1 = add_ln859_509_fu_11668_p2;

assign zext_ln859_fu_11314_p1 = add_ln859_446_reg_12005;

assign zext_ln864_180_fu_9210_p1 = p_read;

assign zext_ln864_181_fu_9236_p1 = shl_ln_fu_9228_p3;

assign zext_ln864_182_fu_9298_p1 = shl_ln864_s_fu_9290_p3;

assign zext_ln864_183_fu_9310_p1 = shl_ln864_93_fu_9302_p3;

assign zext_ln864_184_fu_9426_p1 = shl_ln864_94_fu_9418_p3;

assign zext_ln864_185_fu_9438_p1 = shl_ln864_95_fu_9430_p3;

assign zext_ln864_187_fu_9523_p1 = shl_ln864_96_fu_9515_p3;

assign zext_ln864_188_fu_9535_p1 = shl_ln864_97_fu_9527_p3;

assign zext_ln864_189_fu_11130_p1 = shl_ln864_98_fu_11123_p3;

assign zext_ln864_190_fu_11141_p1 = shl_ln864_99_fu_11134_p3;

assign zext_ln864_191_fu_9704_p1 = p_read4;

assign zext_ln864_192_fu_9927_p1 = shl_ln864_100_fu_9919_p3;

assign zext_ln864_193_fu_10150_p1 = p_read7;

assign zext_ln864_194_fu_10163_p1 = shl_ln864_101_fu_10155_p3;

assign zext_ln864_195_fu_10175_p1 = shl_ln864_102_fu_10167_p3;

assign zext_ln864_196_fu_10262_p1 = p_read8;

assign zext_ln864_197_fu_10313_p1 = shl_ln864_103_fu_10305_p3;

assign zext_ln864_198_fu_10325_p1 = shl_ln864_104_fu_10317_p3;

assign zext_ln864_199_fu_10361_p1 = shl_ln864_105_fu_10353_p3;

assign zext_ln864_200_fu_10373_p1 = shl_ln864_106_fu_10365_p3;

assign zext_ln864_201_fu_10409_p1 = shl_ln864_107_fu_10401_p3;

assign zext_ln864_202_fu_11195_p1 = shl_ln864_108_fu_11188_p3;

assign zext_ln864_203_fu_11206_p1 = shl_ln864_109_fu_11199_p3;

assign zext_ln864_204_fu_10505_p1 = p_read11;

assign zext_ln864_205_fu_11251_p1 = shl_ln864_110_fu_11244_p3;

assign zext_ln864_206_fu_11262_p1 = shl_ln864_111_fu_11255_p3;

assign zext_ln864_207_fu_11286_p1 = $unsigned(sext_ln864_108_fu_11282_p1);

assign zext_ln864_208_fu_10730_p1 = shl_ln864_112_fu_10722_p3;

assign zext_ln864_209_fu_10742_p1 = shl_ln864_113_fu_10734_p3;

assign zext_ln864_210_fu_10868_p1 = shl_ln864_114_fu_10860_p3;

assign zext_ln864_211_fu_10872_p1 = shl_ln1319_98_fu_10766_p3;

assign zext_ln864_fu_9204_p1 = p_read;

always @ (posedge ap_clk) begin
    zext_ln864_193_reg_11939[13:9] <= 5'b00000;
    zext_ln17_195_reg_11944[11] <= 1'b0;
    zext_ln1319_222_reg_11975[14:9] <= 6'b000000;
end

endmodule //tau_nn_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config11_s
